export const landingCopy = {
  brandName: "Ventus AI",
  navigation: {
    ariaLabel: "Landing page chapters",
    mobileAriaLabel: "Mobile landing page chapters",
    homeAriaLabel: "Ventus AI home",
    menuAriaLabel: "Toggle section navigation",
    cta: "Request Access",
    sections: [
      { id: "intelligence", label: "Intelligence" },
      { id: "governance", label: "Governance" },
      { id: "activation", label: "Activation" },
    ],
  },
  accessibility: {
    decisionPlane: "Ventus decision intelligence flow",
    decisionFlow: "Approved context flows through Ventus intelligence into an existing workflow",
    valueFramework: "Ventus value framework",
    flowSequence: "Customer context is gathered, evaluated, and routed into an existing workflow",
    intelligenceStages: "Intelligence stages",
    governancePath: "Governance path",
    activationNetwork: "Governed decision routes to existing bank workflows",
  },
  hero: {
    eyebrow: "Decision intelligence for personalized banking",
    title: "Turn customer context into better banking decisions.",
    body: "Ventus AI brings customer signals, bank policy, and activation together in one governed intelligence layer.",
    cta: "Request Access",
    audience: "For bank executives and their product, growth, wealth, digital, and data leaders.",
    brandLabel: "VENTUS AI",
    status: "GOVERNED",
    cues: [
      { title: "Shared context", body: "One view of the customer relationship." },
      { title: "Governed decisions", body: "Relevance and bank policy, decided together." },
      { title: "Existing workflows", body: "Action through the systems teams already use." },
    ],
    plane: [
      { label: "APPROVED CONTEXT", items: ["Transactions", "Products", "Digital"] },
      { label: "VENTUS INTELLIGENCE", items: ["Context", "Policy", "Objective"] },
      { label: "EXISTING WORKFLOW", items: ["Decision", "Owner", "Channel"] },
    ],
  },
  intelligence: {
    eyebrow: "Intelligence",
    title: "A shared understanding of the customer.",
    body: "Customer context is spread across transactions, product relationships, digital behavior, and teams. Ventus organizes what the bank has approved into one view, so every decision starts from the whole relationship.",
    stages: [
      { title: "Understand", body: "Organize approved context into one view of the relationship." },
      { title: "Decide", body: "Prioritize the next relevant action for this customer, within bank policy." },
      { title: "Activate", body: "Route the decision into the workflow that already owns it." },
    ],
    planeTitle: "VENTUS DECISION PATH",
    plane: [
      { label: "APPROVED CONTEXT", items: ["Transactions", "Products", "Digital"] },
      { label: "VENTUS INTELLIGENCE", items: ["Context", "Policy", "Objective"] },
      { label: "EXISTING WORKFLOW", items: ["Owner", "Channel", "Decision"] },
    ],
  },
  governance: {
    eyebrow: "Governance",
    title: "Personalization under the bank’s rules.",
    body: "Governance is part of the decision itself. Approved context, policy checks, review thresholds, and the decision record stay connected in one visible path.",
    planeTitle: "DECISION CONTROL",
    status: "POLICY ACTIVE",
    rows: [
      { title: "Approved context", body: "Only permitted signal families enter the decision." },
      { title: "Policy checks", body: "Institution-defined rules shape what can happen next." },
      { title: "Review threshold", body: "Human involvement stays visible where required." },
      { title: "Decision record", body: "The rationale and the destination remain connected." },
    ],
  },
  activation: {
    eyebrow: "Activation",
    title: "Intelligence that works through the bank you already run.",
    body: "A governed decision is only useful when it reaches the right team and channel. Ventus delivers decisions into existing workflows rather than adding another one.",
    networkFrom: "GOVERNED DECISION",
    networkTo: "APPROVED DESTINATION",
    destinations: ["Digital banking", "CRM", "Marketing", "Rewards", "Advisor"],
    closingTitle: "Make every customer interaction informed by the full relationship.",
    closingBody: "Tell us which customer decision your team wants to improve first.",
    cta: "Request Access",
  },
  footer: {
    copyright: "© 2026 Ventus Financial Technologies Inc.",
    email: "info@ventusai.com",
  },
  request: {
    kicker: "Ventus AI",
    title: "Request access",
    description: "Tell us about your institution and the customer decision you want to improve.",
    submit: "Submit request",
    submitting: "Sending…",
    resultTitle: "Request received",
    success: "Request received. We will reply from info@ventusai.com within two business days.",
    failure: "We could not send this request. Email info@ventusai.com and we will follow up.",
    fields: {
      name: "Name",
      workEmail: "Work email",
      institution: "Institution",
      role: "Role",
      decision: "Which customer decision would you improve first?",
      optional: "Optional",
      website: "Website",
    },
    errors: {
      name: "Enter your name",
      workEmail: "Enter a valid work email",
      institution: "Enter your institution",
      role: "Enter your role",
    },
  },
} as const;
