import type { CategoryExtensionOpportunity } from '@/types/bankwide';

export const CATEGORY_EXTENSION_OPPORTUNITIES: CategoryExtensionOpportunity[] = [
  // ==========================================
  // SPORTS & ACTIVE LIVING (5)
  // ==========================================
  {
    id: 'ski-action-cams',
    sourcePillar: 'Sports & Active Living',
    sourceCategory: 'Winter Sports',
    sourceSubcategory: 'Ski Equipment & Resorts',
    behavioralSignal: 'Spends $2,400+/year on ski resorts, lift tickets, and equipment',
    extensionProduct: 'Action Cameras',
    extensionMerchant: 'GoPro / Insta360 / DJI',
    extensionCategory: 'Technology & Digital Life',
    whyItFits: '96% of action camera buyers are active winter sports enthusiasts. Ski content is the #1 use case for action camera purchases.',
    mccDisconnectNote: 'MCC 5732 (Electronics Stores) has zero overlap with MCC 7941 (Sports Facilities). Traditional MCC-based targeting completely misses this connection.',
    addressableUsers: 1_200_000,
    estimatedRevenue: 85_000_000,
    projectedConversionRate: 14.2,
    confidenceScore: 96,
    matchingPersonas: ['Ski Enthusiast', 'Adventure Traveler', 'Content Creator'],
    topAgeRanges: ['25-34', '35-44'],
    topRegions: ['Mountain West', 'Pacific Northwest', 'Northeast'],
    peakSpendingWeeks: 'Weeks 44-48',
    optimalDeploymentWindow: 'Oct 15 - Nov 30 (Pre-Season)',
    deploymentRationale: 'Deploy 2 weeks before ski equipment peak (Week 44) to capture gear-up shoppers bundling accessories.',
    priority: 'high',
    merchantDetails: [
      { name: 'GoPro', product: 'HERO13 Black', msrp: '$399.99', link: 'https://gopro.com' },
      { name: 'Insta360', product: 'X4', msrp: '$499.99', link: 'https://www.insta360.com' },
      { name: 'DJI', product: 'Osmo Action 5 Pro', msrp: '$379.00', link: 'https://www.dji.com' },
    ],
  },
  {
    id: 'ski-outerwear',
    sourcePillar: 'Sports & Active Living',
    sourceCategory: 'Winter Sports',
    sourceSubcategory: 'Ski Equipment & Resorts',
    behavioralSignal: 'Books ski resort stays averaging 4+ nights in Colorado/Utah/Vermont',
    extensionProduct: 'Premium Outerwear',
    extensionMerchant: 'The North Face / Patagonia / Arc\'teryx',
    extensionCategory: 'Style & Beauty',
    whyItFits: '89% of premium ski lodge guests purchase outerwear in the same season. Brand crossover between ski resorts and premium outerwear is near-total.',
    mccDisconnectNote: 'MCC 5651 (Family Clothing) is completely unrelated to MCC 7011 (Lodging). No MCC logic connects hotel stays to jacket purchases.',
    addressableUsers: 980_000,
    estimatedRevenue: 62_000_000,
    projectedConversionRate: 11.8,
    confidenceScore: 89,
    matchingPersonas: ['Ski Enthusiast', 'Outdoor Explorer', 'Premium Lifestyle'],
    topAgeRanges: ['30-44', '45-54'],
    topRegions: ['Mountain West', 'Northeast', 'Pacific Northwest'],
    peakSpendingWeeks: 'Weeks 42-47',
    optimalDeploymentWindow: 'Oct 1 - Nov 15',
    deploymentRationale: 'Outerwear purchases precede resort bookings by ~2 weeks. Deploy early to catch the gear-first, book-second pattern.',
    priority: 'high',
    merchantDetails: [
      { name: 'The North Face', product: 'ThermoBall Eco Jacket', msrp: '$230.00', link: 'https://www.thenorthface.com' },
      { name: 'Patagonia', product: 'Nano Puff Jacket', msrp: '$279.00', link: 'https://www.patagonia.com' },
      { name: "Arc'teryx", product: 'Beta LT Jacket', msrp: '$575.00', link: 'https://www.arcteryx.com' },
    ],
  },
  {
    id: 'marathon-massage',
    sourcePillar: 'Sports & Active Living',
    sourceCategory: 'Running & Endurance',
    sourceSubcategory: 'Race Entry Fees & Running Gear',
    behavioralSignal: 'Registers for 3+ races/year with avg $150+ entry fees plus running store purchases',
    extensionProduct: 'Sports Massage & Recovery',
    extensionMerchant: 'Massage Envy / Hand & Stone / Elements Massage',
    extensionCategory: 'Health & Wellness',
    whyItFits: '78% of marathon finishers use massage therapy within 2 weeks post-race. Recovery spending is a near-universal behavior for endurance athletes.',
    mccDisconnectNote: 'MCC 7298 (Health Spa) has no connection to MCC 7941 (Athletic Events). MCCs treat spa visits and race entries as unrelated activities.',
    addressableUsers: 2_100_000,
    estimatedRevenue: 48_000_000,
    projectedConversionRate: 16.5,
    confidenceScore: 78,
    matchingPersonas: ['Marathon Runner', 'Fitness Devotee', 'Health Optimizer'],
    topAgeRanges: ['25-34', '35-44', '45-54'],
    topRegions: ['Northeast', 'Pacific', 'Southeast'],
    peakSpendingWeeks: 'Weeks 14-18, 38-42',
    optimalDeploymentWindow: 'Mar 1 - Apr 30, Sep 1 - Oct 31',
    deploymentRationale: 'Spring and fall marathon seasons drive predictable recovery spending. Deploy 1 week before major race weekends.',
    priority: 'medium',
    merchantDetails: [
      { name: 'Massage Envy', product: 'Sports Recovery Session', msrp: '$99.99/session', link: 'https://www.massageenvy.com' },
      { name: 'Hand & Stone', product: 'Deep Tissue Massage', msrp: '$109.95/session', link: 'https://www.handandstone.com' },
      { name: 'Elements Massage', product: 'Sports Massage', msrp: '$119.00/session', link: 'https://www.elementsmassage.com' },
    ],
  },
  {
    id: 'marathon-compression',
    sourcePillar: 'Sports & Active Living',
    sourceCategory: 'Running & Endurance',
    sourceSubcategory: 'Running Shoes & Apparel',
    behavioralSignal: 'Spends $800+/year on running shoes and apparel at specialty retailers',
    extensionProduct: 'Compression & Recovery Gear',
    extensionMerchant: 'Fleet Feet / Road Runner Sports / CEP',
    extensionCategory: 'Health & Wellness',
    whyItFits: '72% of runners spending $800+/year on shoes also purchase compression and recovery products. The correlation is strongest among 35-54 age group.',
    mccDisconnectNote: 'MCC 5941 (Sporting Goods) and MCC 5947 (Gift/Novelty) capture these differently. No MCC signals the athletic recovery intent.',
    addressableUsers: 1_600_000,
    estimatedRevenue: 34_000_000,
    projectedConversionRate: 12.1,
    confidenceScore: 72,
    matchingPersonas: ['Marathon Runner', 'Weekend Warrior', 'Fitness Devotee'],
    topAgeRanges: ['35-44', '45-54'],
    topRegions: ['Northeast', 'Pacific', 'Mountain West'],
    peakSpendingWeeks: 'Weeks 1-6, 14-18',
    optimalDeploymentWindow: 'Jan 1 - Feb 15, Mar 15 - May 1',
    deploymentRationale: 'New Year resolution runners and spring marathon training windows drive highest demand for recovery products.',
    priority: 'medium',
    merchantDetails: [
      { name: 'Fleet Feet', product: 'CEP Compression Socks', msrp: '$59.99', link: 'https://www.fleetfeet.com' },
      { name: 'Road Runner Sports', product: 'R-Gear Recovery Tights', msrp: '$79.99', link: 'https://www.roadrunnersports.com' },
      { name: 'CEP', product: 'Recovery Pro Tights', msrp: '$89.99', link: 'https://www.cepcompression.com' },
    ],
  },
  {
    id: 'cycling-nutrition',
    sourcePillar: 'Sports & Active Living',
    sourceCategory: 'Cycling',
    sourceSubcategory: 'Cycling Gear & Events',
    behavioralSignal: 'Spends $1,500+/year on cycling gear, event entries, and bike shop visits',
    extensionProduct: 'Sports Nutrition Bars',
    extensionMerchant: 'Clif Bar / RXBAR / GoMacro',
    extensionCategory: 'Health & Wellness',
    whyItFits: '74% of committed cyclists consuming $1,500+/year in gear regularly purchase sports nutrition. Long rides (2+ hours) make on-bike fueling essential.',
    mccDisconnectNote: 'MCC 5941 (Sporting Goods) and MCC 5499 (Misc Food Stores) are entirely separate. MCCs cannot connect bike shop visits to nutrition bar purchases.',
    addressableUsers: 1_400_000,
    estimatedRevenue: 28_000_000,
    projectedConversionRate: 13.7,
    confidenceScore: 74,
    matchingPersonas: ['Cyclist', 'Endurance Athlete', 'Health Optimizer'],
    topAgeRanges: ['30-44', '45-54'],
    topRegions: ['Pacific', 'Mountain West', 'Northeast'],
    peakSpendingWeeks: 'Weeks 14-30',
    optimalDeploymentWindow: 'Apr - Jul (peak cycling season)',
    deploymentRationale: 'Spring and summer cycling season drives the highest volume of long rides and corresponding nutrition needs.',
    priority: 'medium',
    merchantDetails: [
      { name: 'Clif Bar', product: 'Energy Bar Variety Pack', msrp: '$14.99/12pk', link: 'https://www.clifbar.com' },
      { name: 'RXBAR', product: 'Protein Bar Variety Pack', msrp: '$29.99/12pk', link: 'https://www.rxbar.com' },
      { name: 'GoMacro', product: 'MacroBar Variety', msrp: '$27.99/12pk', link: 'https://www.gomacro.com' },
    ],
  },

  // ==========================================
  // FAMILY & COMMUNITY (5)
  // ==========================================
  {
    id: 'newparents-homesecurity',
    sourcePillar: 'Family & Community',
    sourceCategory: 'Childcare & Education',
    sourceSubcategory: 'Baby Products & Maternity',
    behavioralSignal: 'New parents with $5K+ baby spend who also have mortgage payments',
    extensionProduct: 'Home Security Systems',
    extensionMerchant: 'Ring / SimpliSafe / ADT',
    extensionCategory: 'Home & Living',
    whyItFits: '68% of new homeowner parents install home security within 6 months of a child\'s birth. Safety concern spikes dramatically post-baby.',
    mccDisconnectNote: 'MCC 7382 (Security Services) has no connection to MCC 5945 (Baby Products). Traditional systems can\'t detect the parenting → security behavior chain.',
    addressableUsers: 1_800_000,
    estimatedRevenue: 54_000_000,
    projectedConversionRate: 18.6,
    confidenceScore: 68,
    matchingPersonas: ['New Parent', 'Homeowner', 'Safety-Conscious'],
    topAgeRanges: ['28-38'],
    topRegions: ['Suburbs nationwide', 'Southeast', 'Midwest'],
    peakSpendingWeeks: 'Year-round (life event triggered)',
    optimalDeploymentWindow: '30-60 days after baby product cluster + mortgage detected',
    deploymentRationale: 'Nesting instinct peaks in the month before and after birth. Home security is a natural extension of the protective mindset.',
    priority: 'medium',
    merchantDetails: [
      { name: 'Ring', product: 'Alarm Pro Security Kit', msrp: '$299.99', link: 'https://ring.com' },
      { name: 'SimpliSafe', product: 'The Essentials System', msrp: '$249.99', link: 'https://simplisafe.com' },
      { name: 'ADT', product: 'Smart Home Starter', msrp: '$199.99 + $28.99/mo', link: 'https://www.adt.com' },
    ],
  },
  {
    id: 'family-entertainment',
    sourcePillar: 'Family & Community',
    sourceCategory: 'Family Entertainment',
    sourceSubcategory: 'Theme Parks & Family Activities',
    behavioralSignal: 'Families spending $4K+/year on kids activities, theme parks, and family dining',
    extensionProduct: 'Streaming & Theme Park Bundles',
    extensionMerchant: 'Disney / Universal / Merlin Entertainments',
    extensionCategory: 'Entertainment & Culture',
    whyItFits: '82% of families with $4K+ activity spend are active or lapsed streaming subscribers. Theme park visitors convert to streaming at 2.3x the general population rate.',
    mccDisconnectNote: 'MCC 7996 (Amusement Parks) and MCC 4899 (Cable/Streaming) are separate. MCCs can\'t detect that a family spending on LEGOLAND would also convert on a Disney+ bundle.',
    addressableUsers: 3_800_000,
    estimatedRevenue: 66_000_000,
    projectedConversionRate: 14.6,
    confidenceScore: 82,
    matchingPersonas: ['Family Adventurer', 'Suburban Parent', 'Experience Seeker'],
    topAgeRanges: ['30-44', '35-49'],
    topRegions: ['Southeast', 'Pacific', 'Northeast', 'Southwest'],
    peakSpendingWeeks: 'Weeks 22-32, 50-52',
    optimalDeploymentWindow: 'May - Aug (summer), Dec (holiday break)',
    deploymentRationale: 'Summer vacation and holiday break are peak family entertainment periods. Bundle streaming + ticket deals during planning windows.',
    priority: 'medium',
    merchantDetails: [
      { name: 'Disney', product: 'Disney Bundle (Disney+ / Hulu / ESPN+)', msrp: '$14.99/mo', link: 'https://www.disneyplus.com' },
      { name: 'Universal', product: 'Universal+ Annual Pass', msrp: '$399.99/yr', link: 'https://www.universalorlando.com' },
      { name: 'Merlin Entertainments', product: 'Merlin Annual Pass', msrp: '$189.99/yr', link: 'https://www.merlinannualpass.com' },
    ],
  },
  {
    id: 'schoolkids-eduboxes',
    sourcePillar: 'Family & Community',
    sourceCategory: 'Childcare & Education',
    sourceSubcategory: 'Kids Activities & Enrichment',
    behavioralSignal: 'Parents spending $300+/month on tutoring, enrichment, and educational activities',
    extensionProduct: 'Educational Subscription Boxes',
    extensionMerchant: 'KiwiCo / Little Passports / MEL Science',
    extensionCategory: 'Entertainment & Culture',
    whyItFits: '66% of parents investing heavily in enrichment activities also subscribe to educational boxes. The education-as-entertainment mindset translates directly.',
    mccDisconnectNote: 'MCC 8299 (Educational Services) and MCC 5947 (Gift/Novelty) are separate. MCCs can\'t detect that tutoring spend predicts subscription box interest.',
    addressableUsers: 2_100_000,
    estimatedRevenue: 38_000_000,
    projectedConversionRate: 12.4,
    confidenceScore: 66,
    matchingPersonas: ['Enrichment Parent', 'Education-First', 'Discovery Seeker'],
    topAgeRanges: ['30-44'],
    topRegions: ['Northeast', 'Pacific', 'Southeast'],
    peakSpendingWeeks: 'Weeks 32-38, 48-52',
    optimalDeploymentWindow: 'Aug (back-to-school), Nov-Dec (holiday gifting)',
    deploymentRationale: 'Back-to-school and holiday periods drive highest parent interest in educational products. Subscription boxes make ideal gifts.',
    priority: 'medium',
    merchantDetails: [
      { name: 'KiwiCo', product: 'Tinker Crate (Ages 9-16)', msrp: '$29.95/mo', link: 'https://www.kiwico.com' },
      { name: 'Little Passports', product: 'World Edition', msrp: '$26.95/mo', link: 'https://www.littlepassports.com' },
      { name: 'MEL Science', product: 'MEL Chemistry Kit', msrp: '$34.90/mo', link: 'https://melscience.com' },
    ],
  },
  {
    id: 'family-mealkits',
    sourcePillar: 'Family & Community',
    sourceCategory: 'Family Dining',
    sourceSubcategory: 'Grocery & Meal Planning',
    behavioralSignal: 'Families with $800+/month grocery spend and 3+ kids-related merchant visits/week',
    extensionProduct: 'Meal Kit Subscriptions',
    extensionMerchant: 'HelloFresh / Blue Apron / Home Chef',
    extensionCategory: 'Food & Dining',
    whyItFits: '59% of high-grocery-spend families with children have tried or are interested in meal kits. Convenience and variety are the top motivators for time-strapped parents.',
    mccDisconnectNote: 'MCC 5411 (Grocery) and MCC 5499 (Misc Food) are separate. MCCs can\'t identify that a busy family grocery shopper is a prime meal kit subscriber.',
    addressableUsers: 2_800_000,
    estimatedRevenue: 52_000_000,
    projectedConversionRate: 10.8,
    confidenceScore: 59,
    matchingPersonas: ['Busy Parent', 'Family Planner', 'Convenience Seeker'],
    topAgeRanges: ['30-44', '35-49'],
    topRegions: ['Southeast', 'Midwest', 'Northeast'],
    peakSpendingWeeks: 'Weeks 2-10, 36-42',
    optimalDeploymentWindow: 'Jan (New Year healthy eating), Sep (back-to-routine)',
    deploymentRationale: 'New Year healthy eating resolutions and back-to-school routine resets are peak meal kit trial periods.',
    priority: 'low',
    merchantDetails: [
      { name: 'HelloFresh', product: 'Family Plan (4 servings)', msrp: '$9.99/serving', link: 'https://www.hellofresh.com' },
      { name: 'Blue Apron', product: 'Signature Family Box', msrp: '$8.99/serving', link: 'https://www.blueapron.com' },
      { name: 'Home Chef', product: 'Family Meal Kit', msrp: '$10.49/serving', link: 'https://www.homechef.com' },
    ],
  },
  {
    id: 'youthsports-photos',
    sourcePillar: 'Family & Community',
    sourceCategory: 'Youth Sports',
    sourceSubcategory: 'Kids Sports Leagues & Gear',
    behavioralSignal: 'Parents spending $2K+/year on youth sports leagues, travel teams, and gear',
    extensionProduct: 'Team Photo & Video Services',
    extensionMerchant: 'Hudl / GameChanger / Shutterfly',
    extensionCategory: 'Technology & Digital Life',
    whyItFits: '71% of travel team parents record or photograph games. High-engagement sports parents are eager to capture and share their kids\' achievements.',
    mccDisconnectNote: 'MCC 7941 (Sports Events) and MCC 7332 (Photo Studios) are separate. MCCs can\'t detect that youth sports registration predicts photo/video service demand.',
    addressableUsers: 1_600_000,
    estimatedRevenue: 24_000_000,
    projectedConversionRate: 9.2,
    confidenceScore: 71,
    matchingPersonas: ['Sports Parent', 'Team Mom/Dad', 'Memory Keeper'],
    topAgeRanges: ['35-49'],
    topRegions: ['Southeast', 'Midwest', 'Southwest'],
    peakSpendingWeeks: 'Weeks 8-12, 34-38',
    optimalDeploymentWindow: 'Mar (spring season), Aug-Sep (fall season start)',
    deploymentRationale: 'Season kickoff windows create natural demand for capturing the new team experience.',
    priority: 'low',
    merchantDetails: [
      { name: 'Hudl', product: 'Hudl Focus Camera', msrp: '$199.00/season', link: 'https://www.hudl.com' },
      { name: 'GameChanger', product: 'Team Subscription', msrp: '$16.99/mo', link: 'https://gc.com' },
      { name: 'Shutterfly', product: 'Custom Team Photo Book', msrp: '$39.99', link: 'https://www.shutterfly.com' },
    ],
  },

  // ==========================================
  // HOME & LIVING (5)
  // ==========================================
  {
    id: 'renovators-smarthome',
    sourcePillar: 'Home & Living',
    sourceCategory: 'Home Improvement',
    sourceSubcategory: 'Renovation & Remodeling',
    behavioralSignal: 'Spends $8K+ at Home Depot/Lowe\'s in a 6-month window (renovation pattern)',
    extensionProduct: 'Smart Home Devices',
    extensionMerchant: 'Google Nest / Amazon Echo / Ecobee',
    extensionCategory: 'Technology & Digital Life',
    whyItFits: '71% of homeowners who complete major renovations add smart home tech within 3 months. New installations create a natural \'upgrade moment\' for smart thermostats, locks, and cameras.',
    mccDisconnectNote: 'MCC 5200 (Home Supply) and MCC 5732 (Electronics) are separate categories. MCCs can\'t detect the renovation → smart home upgrade behavior sequence.',
    addressableUsers: 2_800_000,
    estimatedRevenue: 78_000_000,
    projectedConversionRate: 13.4,
    confidenceScore: 71,
    matchingPersonas: ['Homeowner', 'Tech Adopter', 'Home Improver'],
    topAgeRanges: ['30-44', '45-54'],
    topRegions: ['Southeast', 'Southwest', 'Midwest'],
    peakSpendingWeeks: 'Weeks 14-28',
    optimalDeploymentWindow: 'Apr - Jul (peak renovation season)',
    deploymentRationale: 'Spring/summer renovation peak creates a 3-month window where smart home upsell conversion is highest.',
    priority: 'medium',
    merchantDetails: [
      { name: 'Google Nest', product: 'Nest Learning Thermostat', msrp: '$249.99', link: 'https://store.google.com/nest' },
      { name: 'Amazon', product: 'Echo Show 15', msrp: '$249.99', link: 'https://www.amazon.com/echo' },
      { name: 'Ecobee', product: 'Smart Thermostat Premium', msrp: '$249.99', link: 'https://www.ecobee.com' },
    ],
  },
  {
    id: 'gardeners-farmbox',
    sourcePillar: 'Home & Living',
    sourceCategory: 'Garden & Outdoor',
    sourceSubcategory: 'Garden Centers & Nurseries',
    behavioralSignal: 'Spends $600+/year at garden centers and nurseries with spring peak',
    extensionProduct: 'Farm Box & CSA Delivery',
    extensionMerchant: 'Local Harvest / Misfits Market / Imperfect Foods',
    extensionCategory: 'Food & Dining',
    whyItFits: '58% of avid gardeners are also regular farmers market shoppers. The farm-to-table mindset connects growing plants to sourcing fresh, local food.',
    mccDisconnectNote: 'MCC 5261 (Nurseries/Garden) and MCC 5411 (Grocery) are separate. MCCs treat garden spending and food sourcing as unrelated behaviors.',
    addressableUsers: 2_200_000,
    estimatedRevenue: 28_000_000,
    projectedConversionRate: 8.2,
    confidenceScore: 58,
    matchingPersonas: ['Home Gardener', 'Farm-to-Table', 'Eco-Conscious'],
    topAgeRanges: ['35-44', '45-54', '55-64'],
    topRegions: ['Pacific', 'Northeast', 'Midwest'],
    peakSpendingWeeks: 'Weeks 14-26',
    optimalDeploymentWindow: 'Apr - Jun (spring planting season)',
    deploymentRationale: 'Spring gardening season and farmers market openings coincide perfectly. Deploy when the grow-your-own mindset is strongest.',
    priority: 'low',
    merchantDetails: [
      { name: 'Local Harvest', product: 'CSA Share Finder', msrp: '$25-50/week', link: 'https://www.localharvest.org' },
      { name: 'Misfits Market', product: 'Weekly Produce Box', msrp: '$26.00/box', link: 'https://www.misfitsmarket.com' },
      { name: 'Imperfect Foods', product: 'Custom Grocery Box', msrp: '$30.00/box', link: 'https://www.imperfectfoods.com' },
    ],
  },
  {
    id: 'furniture-fragrance',
    sourcePillar: 'Home & Living',
    sourceCategory: 'Home Furnishings',
    sourceSubcategory: 'Furniture & Décor',
    behavioralSignal: 'Spends $3K+ on furniture and home décor in a 6-month window',
    extensionProduct: 'Candles & Home Fragrance',
    extensionMerchant: 'Yankee Candle / Diptyque / Bath & Body Works',
    extensionCategory: 'Style & Beauty',
    whyItFits: '63% of furniture shoppers purchase candles or diffusers within 30 days of a major décor purchase. The "finishing touches" mindset drives fragrance add-ons.',
    mccDisconnectNote: 'MCC 5712 (Furniture) and MCC 5977 (Cosmetics) are separate. MCCs can\'t link furniture shopping to scented candle buying behavior.',
    addressableUsers: 1_900_000,
    estimatedRevenue: 22_000_000,
    projectedConversionRate: 9.4,
    confidenceScore: 63,
    matchingPersonas: ['Nester', 'Interior Design Enthusiast', 'Premium Lifestyle'],
    topAgeRanges: ['28-38', '35-44'],
    topRegions: ['Northeast', 'Pacific', 'Southeast'],
    peakSpendingWeeks: 'Weeks 36-44, 48-52',
    optimalDeploymentWindow: 'Sep-Nov (fall nesting), Dec (holiday gifting)',
    deploymentRationale: 'Fall nesting instinct and holiday entertaining drive peak candle/fragrance purchases alongside furniture buying.',
    priority: 'low',
    merchantDetails: [
      { name: 'Yankee Candle', product: 'Large Jar Candle', msrp: '$31.99', link: 'https://www.yankeecandle.com' },
      { name: 'Diptyque', product: 'Baies Candle', msrp: '$74.00', link: 'https://www.diptyqueparis.com' },
      { name: 'Bath & Body Works', product: '3-Wick Candle', msrp: '$26.95', link: 'https://www.bathandbodyworks.com' },
    ],
  },
  {
    id: 'homecooks-cookware',
    sourcePillar: 'Home & Living',
    sourceCategory: 'Kitchen & Appliances',
    sourceSubcategory: 'Kitchen Upgrades & Remodels',
    behavioralSignal: 'Spends $2K+ on kitchen appliances/remodel and regularly shops at specialty grocery stores',
    extensionProduct: 'Specialty Cookware',
    extensionMerchant: 'Le Creuset / All-Clad / Staub',
    extensionCategory: 'Home & Living',
    whyItFits: '69% of kitchen remodelers purchase premium cookware within 3 months. A new kitchen triggers a complete cooking setup refresh.',
    mccDisconnectNote: 'MCC 5722 (Appliances) and MCC 5719 (Misc Home) are separate. MCCs can\'t detect the renovation-to-cookware upgrade sequence.',
    addressableUsers: 1_500_000,
    estimatedRevenue: 35_000_000,
    projectedConversionRate: 11.2,
    confidenceScore: 69,
    matchingPersonas: ['Home Chef', 'Kitchen Renovator', 'Quality Seeker'],
    topAgeRanges: ['35-44', '45-54'],
    topRegions: ['Northeast', 'Pacific', 'Southeast'],
    peakSpendingWeeks: 'Weeks 14-28, 44-52',
    optimalDeploymentWindow: 'Apr-Jul (post-renovation), Nov-Dec (holiday gifting)',
    deploymentRationale: 'Post-renovation glow and holiday entertaining are the two peak cookware purchase windows.',
    priority: 'medium',
    merchantDetails: [
      { name: 'Le Creuset', product: 'Signature Dutch Oven 5.5 Qt', msrp: '$399.95', link: 'https://www.lecreuset.com' },
      { name: 'All-Clad', product: 'D5 Stainless 10-Piece Set', msrp: '$799.95', link: 'https://www.all-clad.com' },
      { name: 'Staub', product: 'Round Cocotte 5.5 Qt', msrp: '$379.99', link: 'https://www.staub-usa.com' },
    ],
  },
  {
    id: 'lawncare-outdoor-furniture',
    sourcePillar: 'Home & Living',
    sourceCategory: 'Garden & Outdoor',
    sourceSubcategory: 'Lawn Care & Landscaping',
    behavioralSignal: 'Spends $1,200+/year on lawn care services, landscaping, and outdoor maintenance',
    extensionProduct: 'Outdoor Furniture',
    extensionMerchant: 'Wayfair / Pottery Barn / Article',
    extensionCategory: 'Home & Living',
    whyItFits: '61% of homeowners investing heavily in landscaping also upgrade their outdoor furniture. A beautiful yard demands comfortable seating.',
    mccDisconnectNote: 'MCC 780 (Landscaping) and MCC 5712 (Furniture) are separate. MCCs can\'t connect lawn care spending to patio furniture purchases.',
    addressableUsers: 2_000_000,
    estimatedRevenue: 42_000_000,
    projectedConversionRate: 10.1,
    confidenceScore: 61,
    matchingPersonas: ['Homeowner', 'Outdoor Entertainer', 'Suburban Lifestyle'],
    topAgeRanges: ['35-44', '45-54', '55-64'],
    topRegions: ['Southeast', 'Southwest', 'Midwest'],
    peakSpendingWeeks: 'Weeks 10-22',
    optimalDeploymentWindow: 'Mar - May (pre-summer prep)',
    deploymentRationale: 'Spring landscaping season creates a natural window for outdoor furniture purchases before summer entertaining begins.',
    priority: 'low',
    merchantDetails: [
      { name: 'Wayfair', product: 'Patio Conversation Set', msrp: '$599.99', link: 'https://www.wayfair.com' },
      { name: 'Pottery Barn', product: 'Indio Lounge Collection', msrp: '$1,299.00', link: 'https://www.potterybarn.com' },
      { name: 'Article', product: 'Ora Outdoor Sofa', msrp: '$849.00', link: 'https://www.article.com' },
    ],
  },

  // ==========================================
  // TRAVEL & EXPLORATION (5)
  // ==========================================
  {
    id: 'frequentflyers-headphones',
    sourcePillar: 'Travel & Exploration',
    sourceCategory: 'Air Travel',
    sourceSubcategory: 'Airline Tickets & Upgrades',
    behavioralSignal: 'Books 8+ flights/year with average ticket price $450+',
    extensionProduct: 'Noise-Canceling Headphones',
    extensionMerchant: 'Sony / Bose / Apple',
    extensionCategory: 'Technology & Digital Life',
    whyItFits: '83% of frequent flyers (8+ flights/year) own or are actively shopping for noise-canceling headphones. It\'s the most universal travel accessory purchase.',
    mccDisconnectNote: 'MCC 4511 (Airlines) and MCC 5732 (Electronics) are entirely separate. MCCs cannot detect that someone who flies frequently is a prime headphone buyer.',
    addressableUsers: 2_600_000,
    estimatedRevenue: 92_000_000,
    projectedConversionRate: 15.7,
    confidenceScore: 83,
    matchingPersonas: ['Business Traveler', 'Frequent Flyer', 'Tech Enthusiast'],
    topAgeRanges: ['30-44', '45-54'],
    topRegions: ['Northeast', 'Pacific', 'Southeast'],
    peakSpendingWeeks: 'Weeks 44-52',
    optimalDeploymentWindow: 'Nov 1 - Dec 25 (Holiday gifting + year-end travel)',
    deploymentRationale: 'Holiday season combines gift-giving with peak business travel. Noise-canceling headphones are the #1 tech gift for travelers.',
    priority: 'high',
    merchantDetails: [
      { name: 'Sony', product: 'WH-1000XM5', msrp: '$399.99', link: 'https://electronics.sony.com' },
      { name: 'Bose', product: 'QuietComfort Ultra', msrp: '$429.99', link: 'https://www.bose.com' },
      { name: 'Apple', product: 'AirPods Max', msrp: '$549.00', link: 'https://www.apple.com/airpods-max' },
    ],
  },
  {
    id: 'hotel-luggage',
    sourcePillar: 'Travel & Exploration',
    sourceCategory: 'Hotels & Lodging',
    sourceSubcategory: 'Hotel Bookings & Loyalty',
    behavioralSignal: 'Spends $6K+/year on hotel stays with loyalty program enrollment',
    extensionProduct: 'Luggage & Travel Gear',
    extensionMerchant: 'Away / Samsonite / Tumi',
    extensionCategory: 'Style & Beauty',
    whyItFits: '77% of frequent hotel guests upgrade luggage every 2-3 years. Premium travel habits drive premium gear expectations.',
    mccDisconnectNote: 'MCC 7011 (Lodging) and MCC 5948 (Luggage) are separate. MCCs can\'t detect that a loyalty hotel guest is due for a luggage upgrade.',
    addressableUsers: 2_200_000,
    estimatedRevenue: 68_000_000,
    projectedConversionRate: 12.3,
    confidenceScore: 77,
    matchingPersonas: ['Business Traveler', 'Luxury Traveler', 'Frequent Flyer'],
    topAgeRanges: ['30-44', '45-54'],
    topRegions: ['Northeast', 'Pacific', 'Southeast'],
    peakSpendingWeeks: 'Weeks 44-52, 1-4',
    optimalDeploymentWindow: 'Nov - Jan (holiday gifting + New Year travel plans)',
    deploymentRationale: 'Holiday gifting and New Year travel planning create peak luggage purchase demand.',
    priority: 'high',
    merchantDetails: [
      { name: 'Away', product: 'The Bigger Carry-On', msrp: '$295.00', link: 'https://www.awaytravel.com' },
      { name: 'Samsonite', product: 'Proxis Spinner 55', msrp: '$349.99', link: 'https://www.samsonite.com' },
      { name: 'Tumi', product: 'Alpha 3 International Carry-On', msrp: '$795.00', link: 'https://www.tumi.com' },
    ],
  },
  {
    id: 'international-language',
    sourcePillar: 'Travel & Exploration',
    sourceCategory: 'International Travel',
    sourceSubcategory: 'International Flights & Bookings',
    behavioralSignal: 'Books 3+ international trips/year to non-English-speaking destinations',
    extensionProduct: 'Language Learning Apps',
    extensionMerchant: 'Babbel / Rosetta Stone / Duolingo Plus',
    extensionCategory: 'Technology & Digital Life',
    whyItFits: '56% of international travelers express interest in learning basic phrases before trips. Subscription starts spike 4-6 weeks before departure dates.',
    mccDisconnectNote: 'MCC 4511 (Airlines) and MCC 5815 (Digital Goods) are separate. MCCs can\'t connect international flight bookings to language app subscriptions.',
    addressableUsers: 1_800_000,
    estimatedRevenue: 32_000_000,
    projectedConversionRate: 8.9,
    confidenceScore: 56,
    matchingPersonas: ['World Traveler', 'Culture Explorer', 'Self-Improver'],
    topAgeRanges: ['25-34', '35-44'],
    topRegions: ['Northeast', 'Pacific', 'Southeast'],
    peakSpendingWeeks: 'Weeks 1-8, 18-22',
    optimalDeploymentWindow: 'Jan-Feb (planning), Apr-May (summer trip prep)',
    deploymentRationale: 'New Year travel planning and pre-summer trip preparation are the two peak windows for language learning sign-ups.',
    priority: 'low',
    merchantDetails: [
      { name: 'Babbel', product: '12-Month Subscription', msrp: '$83.88/yr', link: 'https://www.babbel.com' },
      { name: 'Rosetta Stone', product: 'Lifetime Subscription', msrp: '$179.99', link: 'https://www.rosettastone.com' },
      { name: 'Duolingo', product: 'Super Duolingo Annual', msrp: '$83.99/yr', link: 'https://www.duolingo.com' },
    ],
  },
  {
    id: 'roadtrip-car-accessories',
    sourcePillar: 'Travel & Exploration',
    sourceCategory: 'Road Trips',
    sourceSubcategory: 'Rental Cars & Road Travel',
    behavioralSignal: 'Rents cars 4+ times/year and spends $500+ on road trip lodging/food',
    extensionProduct: 'Car Accessories & Roadside Gear',
    extensionMerchant: 'WeatherTech / Thule / AAA',
    extensionCategory: 'Home & Living',
    whyItFits: '65% of frequent road trippers purchase cargo carriers, floor mats, or roadside kits. The road trip lifestyle drives practical vehicle accessory purchases.',
    mccDisconnectNote: 'MCC 7512 (Car Rental) and MCC 5531 (Auto Parts) are separate. MCCs can\'t connect rental car patterns to car accessory interest.',
    addressableUsers: 1_400_000,
    estimatedRevenue: 26_000_000,
    projectedConversionRate: 9.5,
    confidenceScore: 65,
    matchingPersonas: ['Road Tripper', 'Family Traveler', 'Adventure Seeker'],
    topAgeRanges: ['30-44', '35-49'],
    topRegions: ['Southeast', 'Midwest', 'Southwest'],
    peakSpendingWeeks: 'Weeks 18-26',
    optimalDeploymentWindow: 'May - Jun (pre-summer road trip season)',
    deploymentRationale: 'Pre-summer planning window is when road trip gear purchases peak. Deploy before Memorial Day weekend.',
    priority: 'low',
    merchantDetails: [
      { name: 'WeatherTech', product: 'FloorLiner Set', msrp: '$189.95', link: 'https://www.weathertech.com' },
      { name: 'Thule', product: 'Motion XT Cargo Box', msrp: '$699.95', link: 'https://www.thule.com' },
      { name: 'AAA', product: 'Premier Membership', msrp: '$124.00/yr', link: 'https://www.aaa.com' },
    ],
  },
  {
    id: 'beach-sun-protection',
    sourcePillar: 'Travel & Exploration',
    sourceCategory: 'Beach & Resort',
    sourceSubcategory: 'Resort Bookings & Beach Vacations',
    behavioralSignal: 'Books 2+ beach/resort vacations per year with $3K+ total spend',
    extensionProduct: 'Swimwear & Sun Protection',
    extensionMerchant: 'Maui Jim / Vuori / Supergoop',
    extensionCategory: 'Style & Beauty',
    whyItFits: '79% of repeat beach vacationers purchase new swimwear and suncare products before each trip. The refresh cycle is nearly universal.',
    mccDisconnectNote: 'MCC 7011 (Lodging) and MCC 5651 (Clothing) are separate. MCCs can\'t connect resort bookings to swimwear and sun protection purchases.',
    addressableUsers: 2_400_000,
    estimatedRevenue: 44_000_000,
    projectedConversionRate: 14.1,
    confidenceScore: 79,
    matchingPersonas: ['Beach Lover', 'Resort Traveler', 'Wellness Seeker'],
    topAgeRanges: ['25-34', '35-44', '45-54'],
    topRegions: ['Southeast', 'Pacific', 'Northeast'],
    peakSpendingWeeks: 'Weeks 10-18, 22-26',
    optimalDeploymentWindow: 'Mar - Apr (spring break), May - Jun (summer prep)',
    deploymentRationale: 'Spring break and pre-summer windows drive peak swimwear and suncare purchases. Deploy 3-4 weeks before typical booking dates.',
    priority: 'medium',
    merchantDetails: [
      { name: 'Maui Jim', product: 'Peahi Polarized Sunglasses', msrp: '$339.00', link: 'https://www.mauijim.com' },
      { name: 'Vuori', product: 'Kore Short', msrp: '$68.00', link: 'https://vuoriclothing.com' },
      { name: 'Supergoop', product: 'Unseen Sunscreen SPF 40', msrp: '$38.00', link: 'https://supergoop.com' },
    ],
  },

  // ==========================================
  // FOOD & DINING (5)
  // ==========================================
  {
    id: 'foodies-cookingclass',
    sourcePillar: 'Food & Dining',
    sourceCategory: 'Dining Out',
    sourceSubcategory: 'Fine Dining & Specialty Restaurants',
    behavioralSignal: 'Dines at fine dining restaurants 4+ times/month with avg check $150+',
    extensionProduct: 'Cooking Classes',
    extensionMerchant: 'Sur La Table / Williams Sonoma / local studios',
    extensionCategory: 'Entertainment & Culture',
    whyItFits: '62% of frequent fine diners express interest in culinary skills. The same passion that drives dining out also drives cooking at home.',
    mccDisconnectNote: 'MCC 5812 (Restaurants) and MCC 8299 (Educational Services) are entirely separate. MCCs can\'t connect dining passion to culinary education interest.',
    addressableUsers: 1_400_000,
    estimatedRevenue: 32_000_000,
    projectedConversionRate: 9.8,
    confidenceScore: 62,
    matchingPersonas: ['Foodie', 'Culinary Explorer', 'Experience Seeker'],
    topAgeRanges: ['30-44', '45-54', '55-64'],
    topRegions: ['Pacific', 'Northeast', 'Southeast'],
    peakSpendingWeeks: 'Weeks 1-10, 36-44',
    optimalDeploymentWindow: 'Jan-Mar (New Year resolution cooks), Sep-Nov (fall entertaining)',
    deploymentRationale: 'New Year and fall entertaining seasons create natural spikes in culinary curiosity.',
    priority: 'low',
    merchantDetails: [
      { name: 'Sur La Table', product: 'In-Person Cooking Class', msrp: '$89.00/class', link: 'https://www.surlatable.com' },
      { name: 'Williams Sonoma', product: 'Virtual Cooking Class', msrp: '$49.95/class', link: 'https://www.williams-sonoma.com' },
      { name: 'Local Studios', product: 'Private Group Class', msrp: '$75-150/class', link: 'https://www.classbento.com' },
    ],
  },
  {
    id: 'coffee-espresso',
    sourcePillar: 'Food & Dining',
    sourceCategory: 'Coffee & Beverages',
    sourceSubcategory: 'Specialty Coffee Shops',
    behavioralSignal: 'Visits specialty coffee shops 15+ times/month with avg spend $6.50+/visit ($100+/mo)',
    extensionProduct: 'Home Espresso Equipment',
    extensionMerchant: 'Breville / Fellow / De\'Longhi',
    extensionCategory: 'Home & Living',
    whyItFits: '64% of daily specialty coffee drinkers spending $100+/month eventually invest in home espresso equipment. Average home setup purchase is $450-$800.',
    mccDisconnectNote: 'MCC 5814 (Fast Food/Coffee) and MCC 5719 (Misc Home Furnishings) are entirely separate. MCCs see coffee shop visits and appliance purchases as unrelated.',
    addressableUsers: 5_100_000,
    estimatedRevenue: 82_000_000,
    projectedConversionRate: 11.8,
    confidenceScore: 64,
    matchingPersonas: ['Coffee Connoisseur', 'Home Chef', 'Quality Seeker'],
    topAgeRanges: ['28-38', '35-44'],
    topRegions: ['Pacific', 'Northeast', 'Mountain West'],
    peakSpendingWeeks: 'Weeks 44-52',
    optimalDeploymentWindow: 'Nov 1 - Dec 25 (Holiday gifting)',
    deploymentRationale: 'Espresso machines are the #3 kitchen gift item. Deploy to high-frequency coffee shop visitors whose partners are likely looking for gift ideas.',
    priority: 'medium',
    merchantDetails: [
      { name: 'Breville', product: 'Barista Express Impress', msrp: '$749.95', link: 'https://www.breville.com' },
      { name: 'Fellow', product: 'Opus Conical Burr Grinder', msrp: '$195.00', link: 'https://fellowproducts.com' },
      { name: "De'Longhi", product: 'La Specialista Prestigio', msrp: '$799.95', link: 'https://www.delonghi.com' },
    ],
  },
  {
    id: 'wine-clubs',
    sourcePillar: 'Food & Dining',
    sourceCategory: 'Wine & Spirits',
    sourceSubcategory: 'Wine Bars & Restaurants',
    behavioralSignal: 'Spends $200+/month at wine bars, wine shops, and wine-paired dining',
    extensionProduct: 'Wine Club Subscriptions',
    extensionMerchant: 'Winc / Naked Wines / Wine.com',
    extensionCategory: 'Food & Dining',
    whyItFits: '68% of wine bar regulars are interested in curated wine subscriptions. The desire for discovery and variety translates directly from on-premise to at-home enjoyment.',
    mccDisconnectNote: 'MCC 5813 (Bars) and MCC 5921 (Liquor Stores) are separate. MCCs can\'t distinguish a wine enthusiast from a casual bar visitor.',
    addressableUsers: 1_800_000,
    estimatedRevenue: 36_000_000,
    projectedConversionRate: 13.2,
    confidenceScore: 68,
    matchingPersonas: ['Wine Enthusiast', 'Culinary Explorer', 'Experience Seeker'],
    topAgeRanges: ['35-44', '45-54', '55-64'],
    topRegions: ['Pacific', 'Northeast', 'Southeast'],
    peakSpendingWeeks: 'Weeks 44-52, 1-4',
    optimalDeploymentWindow: 'Nov - Jan (holiday entertaining & gifting)',
    deploymentRationale: 'Holiday entertaining and New Year create peak demand for wine subscriptions as both self-purchases and gifts.',
    priority: 'medium',
    merchantDetails: [
      { name: 'Winc', product: '4-Bottle Monthly Box', msrp: '$59.96/mo', link: 'https://www.winc.com' },
      { name: 'Naked Wines', product: 'Angel Membership', msrp: '$40.00/mo credit', link: 'https://www.nakedwines.com' },
      { name: 'Wine.com', product: 'StewardShip Membership', msrp: '$49.00/yr', link: 'https://www.wine.com' },
    ],
  },
  {
    id: 'takeout-kitchen-gadgets',
    sourcePillar: 'Food & Dining',
    sourceCategory: 'Delivery & Takeout',
    sourceSubcategory: 'Food Delivery Apps',
    behavioralSignal: 'Spends $400+/month on DoorDash, Uber Eats, and food delivery platforms',
    extensionProduct: 'Kitchen Gadgets',
    extensionMerchant: 'Ninja / Instant Pot / Our Place',
    extensionCategory: 'Home & Living',
    whyItFits: '55% of heavy delivery spenders express interest in cooking at home if it were easier. Kitchen gadgets that simplify cooking are the bridge from delivery dependency to home cooking.',
    mccDisconnectNote: 'MCC 5812 (Restaurants) and MCC 5722 (Appliances) are separate. MCCs can\'t detect that a DoorDash power user is a prime air fryer buyer.',
    addressableUsers: 3_200_000,
    estimatedRevenue: 48_000_000,
    projectedConversionRate: 8.6,
    confidenceScore: 55,
    matchingPersonas: ['Convenience Seeker', 'Time-Strapped Professional', 'Aspiring Home Cook'],
    topAgeRanges: ['22-34', '25-34'],
    topRegions: ['Pacific', 'Northeast', 'Southeast'],
    peakSpendingWeeks: 'Weeks 1-8, 44-52',
    optimalDeploymentWindow: 'Jan (New Year cooking goals), Nov-Dec (holiday gifting)',
    deploymentRationale: 'New Year resolution to cook more and holiday gift season create dual peaks for kitchen gadget purchases.',
    priority: 'low',
    merchantDetails: [
      { name: 'Ninja', product: 'Foodi 6-in-1 Air Fryer', msrp: '$129.99', link: 'https://www.ninjakitchen.com' },
      { name: 'Instant Pot', product: 'Duo Plus 6-Quart', msrp: '$89.99', link: 'https://www.instantpot.com' },
      { name: 'Our Place', product: 'Always Pan 2.0', msrp: '$150.00', link: 'https://fromourplace.com' },
    ],
  },
  {
    id: 'organic-farmbox',
    sourcePillar: 'Food & Dining',
    sourceCategory: 'Grocery',
    sourceSubcategory: 'Organic & Natural Grocers',
    behavioralSignal: 'Spends $600+/month at Whole Foods, Sprouts, or specialty organic grocers',
    extensionProduct: 'Farm Box Delivery',
    extensionMerchant: 'Misfits Market / Imperfect Foods / Thrive Market',
    extensionCategory: 'Food & Dining',
    whyItFits: '62% of organic grocery shoppers are interested in farm-direct delivery services. The values alignment (sustainability, quality, freshness) is near-perfect.',
    mccDisconnectNote: 'MCC 5411 (Grocery) can\'t distinguish organic from conventional shoppers. MCCs miss the organic-to-farm-box behavioral pipeline entirely.',
    addressableUsers: 2_600_000,
    estimatedRevenue: 44_000_000,
    projectedConversionRate: 11.4,
    confidenceScore: 62,
    matchingPersonas: ['Eco-Conscious', 'Health Optimizer', 'Farm-to-Table'],
    topAgeRanges: ['28-38', '35-44', '45-54'],
    topRegions: ['Pacific', 'Northeast', 'Mountain West'],
    peakSpendingWeeks: 'Weeks 1-10, 14-22',
    optimalDeploymentWindow: 'Jan-Mar (healthy eating goals), Apr-May (spring produce)',
    deploymentRationale: 'New Year healthy eating and spring produce season create two strong windows for farm box trial sign-ups.',
    priority: 'medium',
    merchantDetails: [
      { name: 'Misfits Market', product: 'Weekly Produce Box', msrp: '$26.00/box', link: 'https://www.misfitsmarket.com' },
      { name: 'Imperfect Foods', product: 'Custom Grocery Box', msrp: '$30.00/box', link: 'https://www.imperfectfoods.com' },
      { name: 'Thrive Market', product: 'Annual Membership + Box', msrp: '$59.95/yr', link: 'https://thrivemarket.com' },
    ],
  },

  // ==========================================
  // HEALTH & WELLNESS (5)
  // ==========================================
  {
    id: 'homegym-nutrition',
    sourcePillar: 'Health & Wellness',
    sourceCategory: 'Fitness & Exercise',
    sourceSubcategory: 'Gym Memberships & Equipment',
    behavioralSignal: 'Spends $200+/month on gym memberships or $2K+ on home fitness equipment',
    extensionProduct: 'Sports Supplements',
    extensionMerchant: 'GNC / Vitamin Shoppe / AG1',
    extensionCategory: 'Health & Wellness',
    whyItFits: '81% of gym members spending $200+/month also purchase supplements. Fitness commitment and nutrition spending are tightly correlated behaviors.',
    mccDisconnectNote: 'MCC 7941 (Health Clubs) and MCC 5912 (Drug Stores) track differently. MCCs can\'t distinguish a supplement buyer at CVS from a cold medicine buyer.',
    addressableUsers: 3_800_000,
    estimatedRevenue: 72_000_000,
    projectedConversionRate: 20.4,
    confidenceScore: 81,
    matchingPersonas: ['Fitness Devotee', 'Health Optimizer', 'Resolution Maker'],
    topAgeRanges: ['22-34', '35-44'],
    topRegions: ['Pacific', 'Northeast', 'Southeast', 'Southwest'],
    peakSpendingWeeks: 'Weeks 1-8',
    optimalDeploymentWindow: 'Dec 26 - Feb 28 (New Year fitness surge)',
    deploymentRationale: 'New Year resolution gym spending creates a massive nutrition supplement upsell window. 88% of new memberships happen in Weeks 1-6.',
    priority: 'high',
    merchantDetails: [
      { name: 'GNC', product: 'Pro Performance Whey Protein', msrp: '$49.99', link: 'https://www.gnc.com' },
      { name: 'Vitamin Shoppe', product: 'BodyTech Whey Isolate', msrp: '$39.99', link: 'https://www.vitaminshoppe.com' },
      { name: 'AG1', product: 'Athletic Greens Monthly', msrp: '$79.00/mo', link: 'https://drinkag1.com' },
    ],
  },
  {
    id: 'wellness-greenjuice',
    sourcePillar: 'Health & Wellness',
    sourceCategory: 'Nutrition & Supplements',
    sourceSubcategory: 'Health Foods & Beverages',
    behavioralSignal: 'High wellness spend ($150+/mo gym, yoga, spa) AND high sports spend ($100+/mo gear, events)',
    extensionProduct: 'Green Juice & Superfood Blends',
    extensionMerchant: 'AG1 / Live It Up / Pressed Juicery / Daily Harvest',
    extensionCategory: 'Health & Wellness',
    whyItFits: '87% of consumers who spend on both fitness and wellness are already buying or actively researching green juice/superfood supplements. This is the highest-intent DTC nutrition audience.',
    mccDisconnectNote: 'MCC 7941 (Health Clubs) and MCC 5499 (Misc Food Stores) are unrelated. MCCs cannot detect that a gym member + yoga practitioner is a prime AG1 subscriber.',
    addressableUsers: 4_600_000,
    estimatedRevenue: 118_000_000,
    projectedConversionRate: 23.1,
    confidenceScore: 87,
    matchingPersonas: ['Fitness Devotee', 'Wellness Seeker', 'Health Optimizer', 'Weekend Warrior'],
    topAgeRanges: ['25-34', '35-44'],
    topRegions: ['Pacific', 'Northeast', 'Mountain West', 'Southeast'],
    peakSpendingWeeks: 'Weeks 1-8, 14-18',
    optimalDeploymentWindow: 'Jan 1 - Feb 28 (New Year wellness surge), Apr 1 - May 15 (spring reset)',
    deploymentRationale: 'New Year resolution + spring detox windows are the two highest-conversion periods. AG1 reports 3x subscription starts in January vs. average month.',
    priority: 'high',
    merchantDetails: [
      { name: 'AG1', product: 'Athletic Greens Starter Kit', msrp: '$79.00/mo', link: 'https://drinkag1.com' },
      { name: 'Live It Up', product: 'Super Greens Powder', msrp: '$49.95/mo', link: 'https://liveitup.com' },
      { name: 'Pressed Juicery', product: 'Greens 2 Cold-Pressed Juice', msrp: '$7.50/bottle', link: 'https://www.pressedjuicery.com' },
      { name: 'Daily Harvest', product: 'Smoothie Subscription', msrp: '$8.49/smoothie', link: 'https://www.daily-harvest.com' },
    ],
  },
  {
    id: 'yoga-athleisure',
    sourcePillar: 'Health & Wellness',
    sourceCategory: 'Mind & Body',
    sourceSubcategory: 'Yoga & Pilates Studios',
    behavioralSignal: 'Spends $150+/month on yoga/pilates studio memberships with 3+ visits/week',
    extensionProduct: 'Premium Athleisure',
    extensionMerchant: 'Lululemon / Alo Yoga / Athleta',
    extensionCategory: 'Style & Beauty',
    whyItFits: '91% of frequent yoga practitioners (3+/week) purchase premium athleisure. Studio-to-apparel conversion is the strongest cross-category signal in wellness.',
    mccDisconnectNote: 'MCC 7941 (Health Clubs) and MCC 5651 (Family Clothing) are separate. MCCs can\'t distinguish a yoga studio member from a CrossFit member — but their apparel preferences are completely different.',
    addressableUsers: 3_200_000,
    estimatedRevenue: 96_000_000,
    projectedConversionRate: 19.4,
    confidenceScore: 91,
    matchingPersonas: ['Yoga Devotee', 'Wellness Seeker', 'Athleisure Lifestyle'],
    topAgeRanges: ['25-34', '35-44', '45-54'],
    topRegions: ['Pacific', 'Northeast', 'Southeast'],
    peakSpendingWeeks: 'Weeks 1-6, 36-40',
    optimalDeploymentWindow: 'Jan (New Year), Sep (back-to-routine)',
    deploymentRationale: 'January resolution sign-ups and September back-to-routine periods drive highest studio enrollment and apparel purchases simultaneously.',
    priority: 'high',
    merchantDetails: [
      { name: 'Lululemon', product: 'Align High-Rise Pant 25"', msrp: '$98.00', link: 'https://www.lululemon.com' },
      { name: 'Alo Yoga', product: 'Airlift High-Waist Legging', msrp: '$118.00', link: 'https://www.aloyoga.com' },
      { name: 'Athleta', product: 'Elation Ultra High Rise Tight', msrp: '$109.00', link: 'https://athleta.gap.com' },
    ],
  },
  {
    id: 'spa-skincare',
    sourcePillar: 'Health & Wellness',
    sourceCategory: 'Self-Care',
    sourceSubcategory: 'Spas & Beauty Treatments',
    behavioralSignal: 'Spends $250+/month on spa treatments, facials, and self-care services',
    extensionProduct: 'Skincare Subscriptions',
    extensionMerchant: 'Dermstore / Sephora / The Ordinary',
    extensionCategory: 'Style & Beauty',
    whyItFits: '73% of regular spa-goers maintain a curated at-home skincare routine. Spa visits create product awareness and brand loyalty that translates to recurring purchases.',
    mccDisconnectNote: 'MCC 7298 (Health Spa) and MCC 5977 (Cosmetics) are separate. MCCs can\'t detect that a frequent spa visitor is a premium skincare subscriber.',
    addressableUsers: 2_400_000,
    estimatedRevenue: 56_000_000,
    projectedConversionRate: 15.8,
    confidenceScore: 73,
    matchingPersonas: ['Self-Care Enthusiast', 'Beauty Devotee', 'Wellness Seeker'],
    topAgeRanges: ['25-34', '35-44', '45-54'],
    topRegions: ['Pacific', 'Northeast', 'Southeast'],
    peakSpendingWeeks: 'Weeks 1-8, 18-22, 44-52',
    optimalDeploymentWindow: 'Jan (self-care goals), May (pre-summer), Nov-Dec (gifting)',
    deploymentRationale: 'New Year self-care resolutions, pre-summer prep, and holiday gifting create three strong windows for skincare subscriptions.',
    priority: 'medium',
    merchantDetails: [
      { name: 'Dermstore', product: 'BeautyFIX Monthly Box', msrp: '$24.95/mo', link: 'https://www.dermstore.com' },
      { name: 'Sephora', product: 'Favorites Skincare Set', msrp: '$68.00', link: 'https://www.sephora.com' },
      { name: 'The Ordinary', product: 'The Balance Set', msrp: '$29.00', link: 'https://theordinary.com' },
    ],
  },
  {
    id: 'sleep-bedding',
    sourcePillar: 'Health & Wellness',
    sourceCategory: 'Sleep & Recovery',
    sourceSubcategory: 'Sleep Products & Supplements',
    behavioralSignal: 'Purchases sleep trackers, melatonin, or sleep supplements regularly ($50+/month)',
    extensionProduct: 'Premium Bedding',
    extensionMerchant: 'Casper / Brooklinen / Parachute',
    extensionCategory: 'Home & Living',
    whyItFits: '67% of sleep-supplement buyers who also use sleep trackers upgrade their bedding within 6 months. Data-driven sleep optimizers naturally invest in their sleep environment.',
    mccDisconnectNote: 'MCC 5912 (Drug Stores) and MCC 5719 (Home Furnishings) are separate. MCCs can\'t detect that melatonin purchases predict premium sheet demand.',
    addressableUsers: 1_600_000,
    estimatedRevenue: 38_000_000,
    projectedConversionRate: 11.6,
    confidenceScore: 67,
    matchingPersonas: ['Sleep Optimizer', 'Health Optimizer', 'Quality Seeker'],
    topAgeRanges: ['28-38', '35-44'],
    topRegions: ['Pacific', 'Northeast', 'Southeast'],
    peakSpendingWeeks: 'Weeks 1-8, 36-42',
    optimalDeploymentWindow: 'Jan (sleep improvement goals), Sep (fall bedroom refresh)',
    deploymentRationale: 'New Year wellness resolutions and fall nesting instincts create two natural windows for bedding upgrades.',
    priority: 'medium',
    merchantDetails: [
      { name: 'Casper', product: 'Wave Hybrid Snow Mattress', msrp: '$2,695.00', link: 'https://casper.com' },
      { name: 'Brooklinen', product: 'Luxe Core Sheet Set', msrp: '$178.00', link: 'https://www.brooklinen.com' },
      { name: 'Parachute', product: 'Percale Sheet Set', msrp: '$169.00', link: 'https://www.parachutehome.com' },
    ],
  },

  // ==========================================
  // ENTERTAINMENT & CULTURE (5)
  // ==========================================
  {
    id: 'footballfans-tailgating',
    sourcePillar: 'Entertainment & Culture',
    sourceCategory: 'Live Events & Sports',
    sourceSubcategory: 'Sporting Event Tickets',
    behavioralSignal: 'Purchases 4+ football game tickets/season plus sports bar spending during game days',
    extensionProduct: 'Tailgating & Outdoor Cooking Gear',
    extensionMerchant: 'Weber / YETI / Traeger',
    extensionCategory: 'Home & Living',
    whyItFits: '67% of season ticket holders spend $500+ annually on tailgating gear. The stadium parking lot is an extension of their entertainment experience.',
    mccDisconnectNote: 'MCC 7941 (Sports Events) and MCC 5251 (Hardware/Home) are entirely separate. MCCs can\'t link game tickets to grill purchases.',
    addressableUsers: 3_100_000,
    estimatedRevenue: 58_000_000,
    projectedConversionRate: 11.3,
    confidenceScore: 67,
    matchingPersonas: ['Sports Fan', 'Tailgater', 'Social Entertainer'],
    topAgeRanges: ['25-34', '35-44', '45-54'],
    topRegions: ['Southeast', 'Midwest', 'Southwest'],
    peakSpendingWeeks: 'Weeks 32-38',
    optimalDeploymentWindow: 'Aug 1 - Sep 15 (Pre-season / Season opener)',
    deploymentRationale: 'Tailgating gear purchases peak before the football season starts. Deploy when excitement is highest and pre-season games begin.',
    priority: 'medium',
    merchantDetails: [
      { name: 'Weber', product: 'Spirit II E-310 Gas Grill', msrp: '$459.00', link: 'https://www.weber.com' },
      { name: 'YETI', product: 'Tundra 45 Hard Cooler', msrp: '$325.00', link: 'https://www.yeti.com' },
      { name: 'Traeger', product: 'Ranger Portable Grill', msrp: '$449.99', link: 'https://www.traeger.com' },
    ],
  },
  {
    id: 'concerts-audio',
    sourcePillar: 'Entertainment & Culture',
    sourceCategory: 'Live Events & Music',
    sourceSubcategory: 'Concert & Festival Tickets',
    behavioralSignal: 'Spends $1,500+/year on concerts, festivals, and live music venues',
    extensionProduct: 'Vinyl & Audio Equipment',
    extensionMerchant: 'Sonos / Audio-Technica / Crosley',
    extensionCategory: 'Technology & Digital Life',
    whyItFits: '71% of frequent concert-goers invest in quality home audio equipment. The live music passion extends to high-fidelity home listening experiences.',
    mccDisconnectNote: 'MCC 7922 (Theaters) and MCC 5732 (Electronics) are separate. MCCs can\'t connect concert ticket purchases to turntable and speaker buying behavior.',
    addressableUsers: 2_200_000,
    estimatedRevenue: 46_000_000,
    projectedConversionRate: 12.8,
    confidenceScore: 71,
    matchingPersonas: ['Music Lover', 'Audiophile', 'Experience Seeker'],
    topAgeRanges: ['22-34', '35-44'],
    topRegions: ['Pacific', 'Northeast', 'Southeast'],
    peakSpendingWeeks: 'Weeks 44-52, 18-22',
    optimalDeploymentWindow: 'Nov-Dec (holiday gifting), May (pre-festival season)',
    deploymentRationale: 'Holiday gifting and pre-festival season are the two windows when music fans most actively shop for audio equipment.',
    priority: 'medium',
    merchantDetails: [
      { name: 'Sonos', product: 'Era 300 Speaker', msrp: '$449.00', link: 'https://www.sonos.com' },
      { name: 'Audio-Technica', product: 'AT-LP120XUSB Turntable', msrp: '$249.00', link: 'https://www.audio-technica.com' },
      { name: 'Crosley', product: 'Voyager Turntable', msrp: '$89.95', link: 'https://www.crosleyradio.com' },
    ],
  },
  {
    id: 'museum-art',
    sourcePillar: 'Entertainment & Culture',
    sourceCategory: 'Museums & Galleries',
    sourceSubcategory: 'Museum Memberships & Gallery Visits',
    behavioralSignal: 'Holds 2+ museum memberships or visits galleries 6+ times/year',
    extensionProduct: 'Art Print Subscriptions',
    extensionMerchant: 'Society6 / Minted / Saatchi Art',
    extensionCategory: 'Home & Living',
    whyItFits: '59% of museum members purchase art prints or décor for their homes. The gallery-to-home pipeline is a strong behavioral signal that MCCs completely miss.',
    mccDisconnectNote: 'MCC 7991 (Museums) and MCC 5999 (Misc Retail) are separate. MCCs can\'t detect that a museum member is an art print buyer.',
    addressableUsers: 1_200_000,
    estimatedRevenue: 18_000_000,
    projectedConversionRate: 8.4,
    confidenceScore: 59,
    matchingPersonas: ['Art Enthusiast', 'Culture Seeker', 'Interior Design'],
    topAgeRanges: ['30-44', '45-54', '55-64'],
    topRegions: ['Northeast', 'Pacific', 'Southeast'],
    peakSpendingWeeks: 'Weeks 44-52, 10-16',
    optimalDeploymentWindow: 'Nov-Dec (holiday gifting), Mar-Apr (spring gallery season)',
    deploymentRationale: 'Holiday gifting and spring gallery openings create two natural art print purchase windows.',
    priority: 'low',
    merchantDetails: [
      { name: 'Society6', product: 'Framed Art Print', msrp: '$39.99-79.99', link: 'https://society6.com' },
      { name: 'Minted', product: 'Limited Edition Print', msrp: '$68.00-198.00', link: 'https://www.minted.com' },
      { name: 'Saatchi Art', product: 'Original Artwork', msrp: '$200.00-2,000.00', link: 'https://www.saatchiart.com' },
    ],
  },
  {
    id: 'books-audiobooks',
    sourcePillar: 'Entertainment & Culture',
    sourceCategory: 'Reading & Literature',
    sourceSubcategory: 'Bookstores & Book Clubs',
    behavioralSignal: 'Spends $100+/month at bookstores with 3+ purchases/month',
    extensionProduct: 'E-Reader & Audiobook Subscriptions',
    extensionMerchant: 'Kindle / Audible / Libro.fm',
    extensionCategory: 'Technology & Digital Life',
    whyItFits: '64% of high-frequency bookstore shoppers also use audiobooks or e-readers. Avid readers consume across formats — physical and digital complement each other.',
    mccDisconnectNote: 'MCC 5942 (Book Stores) and MCC 5815 (Digital Goods) are separate. MCCs can\'t detect that a frequent bookstore visitor is a prime audiobook subscriber.',
    addressableUsers: 2_800_000,
    estimatedRevenue: 42_000_000,
    projectedConversionRate: 14.2,
    confidenceScore: 64,
    matchingPersonas: ['Avid Reader', 'Knowledge Seeker', 'Commuter'],
    topAgeRanges: ['25-34', '35-44', '45-54'],
    topRegions: ['Northeast', 'Pacific', 'Midwest'],
    peakSpendingWeeks: 'Weeks 44-52, 22-30',
    optimalDeploymentWindow: 'Nov-Dec (holiday), Jun-Jul (summer reading)',
    deploymentRationale: 'Holiday gifting and summer reading season create two strong windows for digital reading subscriptions.',
    priority: 'medium',
    merchantDetails: [
      { name: 'Amazon', product: 'Kindle Paperwhite Signature', msrp: '$189.99', link: 'https://www.amazon.com/kindle' },
      { name: 'Audible', product: 'Premium Plus Annual', msrp: '$149.50/yr', link: 'https://www.audible.com' },
      { name: 'Libro.fm', product: 'Monthly Audiobook Membership', msrp: '$14.99/mo', link: 'https://libro.fm' },
    ],
  },
  {
    id: 'movies-streaming',
    sourcePillar: 'Entertainment & Culture',
    sourceCategory: 'Film & Cinema',
    sourceSubcategory: 'Movie Theaters',
    behavioralSignal: 'Visits movie theaters 3+ times/month with avg spend $30+/visit',
    extensionProduct: 'Premium Streaming & Cinema Memberships',
    extensionMerchant: 'AMC A-List / Criterion Channel / MUBI',
    extensionCategory: 'Entertainment & Culture',
    whyItFits: '76% of frequent moviegoers subscribe to 2+ streaming services. Cinema enthusiasts are omnivorous content consumers who value curation.',
    mccDisconnectNote: 'MCC 7832 (Movie Theaters) and MCC 4899 (Cable/Streaming) are separate. MCCs can\'t connect theater ticket frequency to premium streaming interest.',
    addressableUsers: 3_400_000,
    estimatedRevenue: 52_000_000,
    projectedConversionRate: 16.8,
    confidenceScore: 76,
    matchingPersonas: ['Film Buff', 'Entertainment Enthusiast', 'Culture Seeker'],
    topAgeRanges: ['22-34', '35-44'],
    topRegions: ['Pacific', 'Northeast', 'Southeast'],
    peakSpendingWeeks: 'Weeks 44-52, 22-30',
    optimalDeploymentWindow: 'Nov-Dec (awards season), Jun-Jul (summer blockbusters)',
    deploymentRationale: 'Awards season and summer blockbuster periods drive highest cinema engagement and streaming sign-up intent.',
    priority: 'medium',
    merchantDetails: [
      { name: 'AMC', product: 'A-List Membership', msrp: '$24.99/mo', link: 'https://www.amctheatres.com/alist' },
      { name: 'Criterion Channel', product: 'Annual Subscription', msrp: '$99.99/yr', link: 'https://www.criterionchannel.com' },
      { name: 'MUBI', product: 'Annual Membership', msrp: '$95.88/yr', link: 'https://mubi.com' },
    ],
  },

  // ==========================================
  // TECHNOLOGY & DIGITAL LIFE (5)
  // ==========================================
  {
    id: 'gamers-ergonomic',
    sourcePillar: 'Technology & Digital Life',
    sourceCategory: 'Gaming',
    sourceSubcategory: 'Gaming Hardware & Subscriptions',
    behavioralSignal: 'Spends $1,200+/year on gaming hardware, subscriptions, and in-game purchases',
    extensionProduct: 'Ergonomic Gaming Chairs',
    extensionMerchant: 'Secretlab / Herman Miller / Razer',
    extensionCategory: 'Home & Living',
    whyItFits: '73% of gamers spending $1,200+/year prioritize ergonomic setups. Extended gaming sessions (avg 14 hrs/week) make comfort a necessity.',
    mccDisconnectNote: 'MCC 5734 (Computer Software) and MCC 5712 (Furniture) are entirely separate. MCCs can\'t detect that a software subscription buyer needs a better chair.',
    addressableUsers: 2_400_000,
    estimatedRevenue: 52_000_000,
    projectedConversionRate: 10.6,
    confidenceScore: 73,
    matchingPersonas: ['Gamer', 'Tech Enthusiast', 'Remote Worker'],
    topAgeRanges: ['18-24', '25-34'],
    topRegions: ['Pacific', 'Southwest', 'Northeast'],
    peakSpendingWeeks: 'Weeks 44-52',
    optimalDeploymentWindow: 'Nov 1 - Dec 31 (Holiday + Black Friday)',
    deploymentRationale: 'Black Friday and holiday gifting season is when gaming setup upgrades peak. Bundle chair deals with gaming hardware promotions.',
    priority: 'medium',
    merchantDetails: [
      { name: 'Secretlab', product: 'TITAN Evo', msrp: '$519.00', link: 'https://secretlab.co' },
      { name: 'Herman Miller', product: 'Aeron Chair - Gaming Edition', msrp: '$1,395.00', link: 'https://www.hermanmiller.com' },
      { name: 'Razer', product: 'Iskur V2 Gaming Chair', msrp: '$499.99', link: 'https://www.razer.com' },
    ],
  },
  {
    id: 'smarthome-networking',
    sourcePillar: 'Technology & Digital Life',
    sourceCategory: 'Smart Home',
    sourceSubcategory: 'Smart Home Devices & Hubs',
    behavioralSignal: 'Purchases 3+ smart home devices (lights, locks, cameras) in a 12-month window',
    extensionProduct: 'Home Networking Equipment',
    extensionMerchant: 'eero / Google Nest WiFi / Ubiquiti',
    extensionCategory: 'Technology & Digital Life',
    whyItFits: '78% of multi-device smart home adopters upgrade their WiFi infrastructure. More devices = more bandwidth demand = networking upgrade trigger.',
    mccDisconnectNote: 'MCC 5732 (Electronics) captures both categories but can\'t detect that multiple smart home purchases predict a networking upgrade.',
    addressableUsers: 1_800_000,
    estimatedRevenue: 34_000_000,
    projectedConversionRate: 14.2,
    confidenceScore: 78,
    matchingPersonas: ['Tech Adopter', 'Smart Home Builder', 'Homeowner'],
    topAgeRanges: ['28-38', '35-44'],
    topRegions: ['Pacific', 'Northeast', 'Southeast'],
    peakSpendingWeeks: 'Weeks 44-52',
    optimalDeploymentWindow: 'Nov-Dec (holiday smart home gifting)',
    deploymentRationale: 'Holiday smart home device gifting creates a surge in networking upgrade need when new devices join the household.',
    priority: 'medium',
    merchantDetails: [
      { name: 'eero', product: 'eero Pro 6E (3-pack)', msrp: '$399.99', link: 'https://eero.com' },
      { name: 'Google', product: 'Nest Wifi Pro (3-pack)', msrp: '$399.99', link: 'https://store.google.com' },
      { name: 'Ubiquiti', product: 'UniFi Dream Router', msrp: '$199.00', link: 'https://ui.com' },
    ],
  },
  {
    id: 'photography-prints',
    sourcePillar: 'Technology & Digital Life',
    sourceCategory: 'Photography',
    sourceSubcategory: 'Camera Gear & Accessories',
    behavioralSignal: 'Spends $1,000+/year on camera gear, lenses, and photography accessories',
    extensionProduct: 'Photo Printing Services',
    extensionMerchant: 'Shutterfly / Artifact Uprising / Mixbook',
    extensionCategory: 'Home & Living',
    whyItFits: '63% of active photographers who invest in gear also spend on professional-quality printing. The creative pipeline demands a physical output.',
    mccDisconnectNote: 'MCC 5946 (Camera Stores) and MCC 7332 (Photo Services) are separate. MCCs can\'t detect that a camera gear buyer is a prime photo printing customer.',
    addressableUsers: 1_400_000,
    estimatedRevenue: 22_000_000,
    projectedConversionRate: 9.8,
    confidenceScore: 63,
    matchingPersonas: ['Photographer', 'Creative Hobbyist', 'Memory Keeper'],
    topAgeRanges: ['30-44', '45-54'],
    topRegions: ['Pacific', 'Northeast', 'Mountain West'],
    peakSpendingWeeks: 'Weeks 44-52, 18-22',
    optimalDeploymentWindow: 'Nov-Dec (holiday photo books), May (spring/wedding season)',
    deploymentRationale: 'Holiday photo book season and spring wedding/event photography create two strong printing demand windows.',
    priority: 'low',
    merchantDetails: [
      { name: 'Shutterfly', product: 'Premium Photo Book', msrp: '$49.99', link: 'https://www.shutterfly.com' },
      { name: 'Artifact Uprising', product: 'Hardcover Photo Book', msrp: '$69.00', link: 'https://www.artifactuprising.com' },
      { name: 'Mixbook', product: 'Custom Photo Book', msrp: '$39.99', link: 'https://www.mixbook.com' },
    ],
  },
  {
    id: 'podcast-microphones',
    sourcePillar: 'Technology & Digital Life',
    sourceCategory: 'Audio & Content Creation',
    sourceSubcategory: 'Podcast & Streaming Subscriptions',
    behavioralSignal: 'Subscribes to 5+ podcasts and spends on audio content platforms ($30+/month)',
    extensionProduct: 'Microphone & Audio Gear',
    extensionMerchant: 'Blue Yeti / Shure / Rode',
    extensionCategory: 'Technology & Digital Life',
    whyItFits: '48% of heavy podcast consumers are interested in starting their own podcast or content creation. Audio gear purchases spike among power listeners.',
    mccDisconnectNote: 'MCC 5815 (Digital Goods) and MCC 5732 (Electronics) are separate. MCCs can\'t detect that a podcast subscription buyer is a future microphone purchaser.',
    addressableUsers: 1_200_000,
    estimatedRevenue: 18_000_000,
    projectedConversionRate: 7.2,
    confidenceScore: 48,
    matchingPersonas: ['Content Creator', 'Audio Enthusiast', 'Side Hustler'],
    topAgeRanges: ['22-34', '25-34'],
    topRegions: ['Pacific', 'Northeast', 'Southeast'],
    peakSpendingWeeks: 'Weeks 1-8, 44-52',
    optimalDeploymentWindow: 'Jan (New Year projects), Nov-Dec (holiday gifting)',
    deploymentRationale: 'New Year "start a podcast" resolutions and holiday gifting drive two distinct microphone purchase windows.',
    priority: 'low',
    merchantDetails: [
      { name: 'Blue', product: 'Yeti X USB Microphone', msrp: '$169.99', link: 'https://www.logitechg.com/blue' },
      { name: 'Shure', product: 'MV7+ Podcast Microphone', msrp: '$269.00', link: 'https://www.shure.com' },
      { name: 'Rode', product: 'PodMic USB', msrp: '$199.00', link: 'https://www.rode.com' },
    ],
  },
  {
    id: 'productivity-desks',
    sourcePillar: 'Technology & Digital Life',
    sourceCategory: 'Productivity & Work',
    sourceSubcategory: 'Productivity App Subscriptions',
    behavioralSignal: 'Subscribes to 3+ productivity apps (Notion, Todoist, etc.) totaling $50+/month',
    extensionProduct: 'Ergonomic Desk Accessories',
    extensionMerchant: 'Autonomous / Uplift / Fully',
    extensionCategory: 'Home & Living',
    whyItFits: '61% of productivity tool power users invest in ergonomic desk setups. The digital optimization mindset extends to physical workspace optimization.',
    mccDisconnectNote: 'MCC 5815 (Digital Goods) and MCC 5712 (Furniture) are separate. MCCs can\'t detect that a Notion subscriber is a standing desk buyer.',
    addressableUsers: 1_600_000,
    estimatedRevenue: 32_000_000,
    projectedConversionRate: 10.4,
    confidenceScore: 61,
    matchingPersonas: ['Remote Worker', 'Productivity Enthusiast', 'Tech Professional'],
    topAgeRanges: ['25-34', '35-44'],
    topRegions: ['Pacific', 'Northeast', 'Mountain West'],
    peakSpendingWeeks: 'Weeks 1-8, 36-40',
    optimalDeploymentWindow: 'Jan (workspace refresh), Sep (back-to-work)',
    deploymentRationale: 'New Year workspace upgrades and September back-to-work energy create two natural ergonomic furniture purchase windows.',
    priority: 'medium',
    merchantDetails: [
      { name: 'Autonomous', product: 'SmartDesk Pro', msrp: '$529.00', link: 'https://www.autonomous.ai' },
      { name: 'Uplift', product: 'V2 Standing Desk', msrp: '$599.00', link: 'https://www.upliftdesk.com' },
      { name: 'Fully', product: 'Jarvis Bamboo Standing Desk', msrp: '$579.00', link: 'https://www.fully.com' },
    ],
  },

  // ==========================================
  // PETS (5)
  // ==========================================
  {
    id: 'dogowners-subscriptions',
    sourcePillar: 'Pets',
    sourceCategory: 'Pet Care',
    sourceSubcategory: 'Veterinary & Pet Health',
    behavioralSignal: 'Spends $1,500+/year on vet visits and pet supplies with increasing frequency',
    extensionProduct: 'Pet Subscription Boxes',
    extensionMerchant: 'BarkBox / Chewy / Petco',
    extensionCategory: 'Pets',
    whyItFits: '76% of pet owners spending $1,500+/year on vet and supplies are receptive to curated subscription boxes. Convenience + discovery drives high LTV.',
    mccDisconnectNote: 'MCC 742 (Veterinary Services) and MCC 5995 (Pet Stores) are tracked separately. MCCs can\'t distinguish a high-engagement pet parent from an occasional buyer.',
    addressableUsers: 4_200_000,
    estimatedRevenue: 74_000_000,
    projectedConversionRate: 17.8,
    confidenceScore: 76,
    matchingPersonas: ['Pet Parent', 'Animal Lover', 'Subscription Enthusiast'],
    topAgeRanges: ['25-34', '35-44', '55-64'],
    topRegions: ['Pacific', 'Northeast', 'Southeast'],
    peakSpendingWeeks: 'Year-round (strongest after large vet bills)',
    optimalDeploymentWindow: '7-14 days after a vet bill exceeding $300 is detected',
    deploymentRationale: 'Post-vet-visit is the highest engagement moment for pet parents. Subscription offers convert best when pet care is top-of-mind.',
    priority: 'high',
    merchantDetails: [
      { name: 'BarkBox', product: 'Monthly Toy & Treat Box', msrp: '$35.00/mo', link: 'https://www.barkbox.com' },
      { name: 'Chewy', product: 'Autoship Subscription', msrp: 'Varies (5-10% off)', link: 'https://www.chewy.com' },
      { name: 'Petco', product: 'Vital Care Membership', msrp: '$19.99/mo', link: 'https://www.petco.com' },
    ],
  },
  {
    id: 'pet-grooming',
    sourcePillar: 'Pets',
    sourceCategory: 'Pet Care',
    sourceSubcategory: 'Pet Grooming & Boarding',
    behavioralSignal: 'Spends $200+/month on pet grooming, boarding, and daycare services',
    extensionProduct: 'Pet Grooming Services',
    extensionMerchant: 'PetSmart Grooming / Wag / Rover',
    extensionCategory: 'Pets',
    whyItFits: '69% of high-spend pet owners use multiple grooming and care services. Cross-platform loyalty is low — presenting alternatives at the right moment drives switching.',
    mccDisconnectNote: 'MCC 742 (Veterinary) and MCC 7299 (Misc Personal Services) are separate. MCCs can\'t detect that boarding spend predicts grooming service demand.',
    addressableUsers: 2_600_000,
    estimatedRevenue: 48_000_000,
    projectedConversionRate: 13.4,
    confidenceScore: 69,
    matchingPersonas: ['Pet Parent', 'Convenience Seeker', 'Premium Pet Owner'],
    topAgeRanges: ['28-38', '35-44'],
    topRegions: ['Pacific', 'Northeast', 'Southeast'],
    peakSpendingWeeks: 'Year-round (peaks before holidays)',
    optimalDeploymentWindow: 'Nov-Dec (holiday grooming), Jun-Jul (summer boarding)',
    deploymentRationale: 'Holiday grooming rush and summer travel boarding needs create two peak demand windows for pet services.',
    priority: 'medium',
    merchantDetails: [
      { name: 'PetSmart', product: 'Full Grooming Package', msrp: '$75.00/session', link: 'https://www.petsmart.com/grooming' },
      { name: 'Wag', product: 'Dog Walking Membership', msrp: '$9.99/mo + per walk', link: 'https://wagwalking.com' },
      { name: 'Rover', product: 'Premium Boarding', msrp: '$45-85/night', link: 'https://www.rover.com' },
    ],
  },
  {
    id: 'pet-portraits',
    sourcePillar: 'Pets',
    sourceCategory: 'Pet Lifestyle',
    sourceSubcategory: 'Pet Treats & Toys',
    behavioralSignal: 'Spends $100+/month on premium pet treats, toys, and accessories',
    extensionProduct: 'Custom Pet Portraits',
    extensionMerchant: 'Crown & Paw / West & Willow / PetPortraits',
    extensionCategory: 'Home & Living',
    whyItFits: '52% of premium pet treat buyers have purchased or expressed interest in custom pet art. Pet humanization drives the desire to display their animals as family members.',
    mccDisconnectNote: 'MCC 5995 (Pet Stores) and MCC 5999 (Misc Retail) are separate. MCCs can\'t connect premium treat buying to custom art commissioning.',
    addressableUsers: 1_800_000,
    estimatedRevenue: 22_000_000,
    projectedConversionRate: 7.8,
    confidenceScore: 52,
    matchingPersonas: ['Pet Parent', 'Gift Giver', 'Home Decorator'],
    topAgeRanges: ['25-34', '35-44'],
    topRegions: ['Pacific', 'Northeast', 'Southeast'],
    peakSpendingWeeks: 'Weeks 44-52, 5-8',
    optimalDeploymentWindow: 'Nov-Dec (holiday gifting), Feb (Valentine\'s/pet appreciation)',
    deploymentRationale: 'Holiday and Valentine\'s Day create two strong gift-giving windows for custom pet portraits.',
    priority: 'low',
    merchantDetails: [
      { name: 'Crown & Paw', product: 'Renaissance Pet Portrait', msrp: '$49.99', link: 'https://crownandpaw.com' },
      { name: 'West & Willow', product: 'Custom Pet Portrait', msrp: '$69.95', link: 'https://westandwillow.com' },
      { name: 'PetPortraits', product: 'Watercolor Pet Portrait', msrp: '$59.99', link: 'https://petportraits.com' },
    ],
  },
  {
    id: 'multipet-feeders',
    sourcePillar: 'Pets',
    sourceCategory: 'Pet Tech',
    sourceSubcategory: 'Pet Supplies & Equipment',
    behavioralSignal: 'Purchases pet food for 2+ pets (detected via frequency and volume of pet store visits)',
    extensionProduct: 'Automatic Pet Feeders',
    extensionMerchant: 'PetSafe / SureFeed / Petlibro',
    extensionCategory: 'Technology & Digital Life',
    whyItFits: '64% of multi-pet households are interested in automated feeding to manage different diets and portions. Complexity of multi-pet feeding drives tech adoption.',
    mccDisconnectNote: 'MCC 5995 (Pet Stores) and MCC 5732 (Electronics) are separate. MCCs can\'t detect that a multi-pet buyer needs smart feeding technology.',
    addressableUsers: 2_200_000,
    estimatedRevenue: 32_000_000,
    projectedConversionRate: 10.2,
    confidenceScore: 64,
    matchingPersonas: ['Multi-Pet Household', 'Tech Adopter', 'Convenience Seeker'],
    topAgeRanges: ['28-38', '35-44'],
    topRegions: ['Pacific', 'Southeast', 'Midwest'],
    peakSpendingWeeks: 'Weeks 44-52, 1-4',
    optimalDeploymentWindow: 'Nov-Dec (holiday), Jan (New Year pet routine optimization)',
    deploymentRationale: 'Holiday gifting and New Year "get organized" energy drive automated feeder purchases.',
    priority: 'medium',
    merchantDetails: [
      { name: 'PetSafe', product: 'Smart Feed 2.0', msrp: '$149.95', link: 'https://www.petsafe.net' },
      { name: 'SureFeed', product: 'Microchip Pet Feeder Connect', msrp: '$179.99', link: 'https://www.surepetcare.com' },
      { name: 'Petlibro', product: 'Granary Camera Feeder', msrp: '$119.99', link: 'https://www.petlibro.com' },
    ],
  },
  {
    id: 'dogpark-walking',
    sourcePillar: 'Pets',
    sourceCategory: 'Pet Activities',
    sourceSubcategory: 'Dog Parks & Daycare',
    behavioralSignal: 'Spends $300+/month on dog daycare, dog parks, and pet-friendly activities',
    extensionProduct: 'Dog Walking & Sitting Apps',
    extensionMerchant: 'Rover / Wag / Care.com',
    extensionCategory: 'Pets',
    whyItFits: '72% of dog daycare users also use on-demand dog walking services. The active dog lifestyle requires flexible care options beyond scheduled daycare.',
    mccDisconnectNote: 'MCC 742 (Veterinary) and MCC 7299 (Personal Services) are separate. MCCs can\'t detect that daycare spend predicts on-demand walking app adoption.',
    addressableUsers: 1_600_000,
    estimatedRevenue: 28_000_000,
    projectedConversionRate: 14.6,
    confidenceScore: 72,
    matchingPersonas: ['Active Dog Owner', 'Busy Professional', 'Pet Parent'],
    topAgeRanges: ['25-34', '35-44'],
    topRegions: ['Pacific', 'Northeast', 'Southeast'],
    peakSpendingWeeks: 'Year-round (peaks during travel seasons)',
    optimalDeploymentWindow: 'May-Jun (summer travel), Nov-Dec (holiday travel)',
    deploymentRationale: 'Travel seasons create peak demand for on-demand pet care when regular daycare isn\'t enough.',
    priority: 'medium',
    merchantDetails: [
      { name: 'Rover', product: 'Dog Walking (30 min)', msrp: '$15-25/walk', link: 'https://www.rover.com' },
      { name: 'Wag', product: 'Premium Walking Plan', msrp: '$9.99/mo + per walk', link: 'https://wagwalking.com' },
      { name: 'Care.com', product: 'Premium Pet Care Membership', msrp: '$39.99/mo', link: 'https://www.care.com' },
    ],
  },
];

// Aggregate stats for dashboard header
export function getCategoryExtensionSummary() {
  const totalRevenue = CATEGORY_EXTENSION_OPPORTUNITIES.reduce((sum, o) => sum + o.estimatedRevenue, 0);
  const totalUsers = CATEGORY_EXTENSION_OPPORTUNITIES.reduce((sum, o) => sum + o.addressableUsers, 0);
  const highPriority = CATEGORY_EXTENSION_OPPORTUNITIES.filter(o => o.priority === 'high').length;
  const avgConfidence = CATEGORY_EXTENSION_OPPORTUNITIES.reduce((sum, o) => sum + o.confidenceScore, 0) / CATEGORY_EXTENSION_OPPORTUNITIES.length;

  return {
    totalOpportunities: CATEGORY_EXTENSION_OPPORTUNITIES.length,
    totalEstimatedRevenue: totalRevenue,
    totalAddressableUsers: totalUsers,
    highPriorityCount: highPriority,
    avgConfidenceScore: Math.round(avgConfidence),
  };
}
