import type { CategoryExtensionOpportunity } from '@/types/bankwide';

export const CATEGORY_EXTENSION_OPPORTUNITIES: CategoryExtensionOpportunity[] = [
  {
    id: 'ski-gopro',
    sourcePillar: 'Sports & Active Living',
    sourceCategory: 'Winter Sports',
    sourceSubcategory: 'Ski Equipment & Resorts',
    behavioralSignal: 'Spends $2,400+/year on ski resorts, lift tickets, and equipment',
    extensionProduct: 'GoPro HERO13 Black',
    extensionMerchant: 'GoPro / Best Buy',
    extensionCategory: 'Technology & Digital Life',
    whyItFits: '96% of action camera buyers are active winter sports enthusiasts. Ski content is the #1 use case for GoPro purchases.',
    mccDisconnectNote: 'MCC 5732 (Electronics Stores) has zero overlap with MCC 7941 (Sports Facilities). Traditional MCC-based targeting completely misses this connection.',
    addressableUsers: 1_200_000,
    estimatedRevenue: 85_000_000,
    projectedConversionRate: 14.2,
    confidenceScore: 96,
    matchingPersonas: ['Ski Enthusiast', 'Adventure Traveler', 'Content Creator'],
    topAgeRanges: ['25-34', '35-44'],
    topRegions: ['Mountain West', 'Pacific Northwest', 'Northeast'],
    peakSpendingWeeks: 'Weeks 44-48',
    optimalDeploymentWindow: 'Oct 15 - Nov 30 (Pre-Season)',
    deploymentRationale: 'Deploy 2 weeks before ski equipment peak (Week 44) to capture gear-up shoppers bundling accessories.',
    priority: 'high',
  },
  {
    id: 'ski-northface',
    sourcePillar: 'Sports & Active Living',
    sourceCategory: 'Winter Sports',
    sourceSubcategory: 'Ski Equipment & Resorts',
    behavioralSignal: 'Books ski resort stays averaging 4+ nights in Colorado/Utah/Vermont',
    extensionProduct: 'The North Face ThermoBall Jacket',
    extensionMerchant: 'The North Face / REI',
    extensionCategory: 'Style & Beauty',
    whyItFits: '89% of premium ski lodge guests purchase outerwear in the same season. Brand crossover between ski resorts and premium outerwear is near-total.',
    mccDisconnectNote: 'MCC 5651 (Family Clothing) is completely unrelated to MCC 7011 (Lodging). No MCC logic connects hotel stays to jacket purchases.',
    addressableUsers: 980_000,
    estimatedRevenue: 62_000_000,
    projectedConversionRate: 11.8,
    confidenceScore: 89,
    matchingPersonas: ['Ski Enthusiast', 'Outdoor Explorer', 'Premium Lifestyle'],
    topAgeRanges: ['30-44', '45-54'],
    topRegions: ['Mountain West', 'Northeast', 'Pacific Northwest'],
    peakSpendingWeeks: 'Weeks 42-47',
    optimalDeploymentWindow: 'Oct 1 - Nov 15',
    deploymentRationale: 'Outerwear purchases precede resort bookings by ~2 weeks. Deploy early to catch the gear-first, book-second pattern.',
    priority: 'high',
  },
  {
    id: 'marathon-massage',
    sourcePillar: 'Sports & Active Living',
    sourceCategory: 'Running & Endurance',
    sourceSubcategory: 'Race Entry Fees & Running Gear',
    behavioralSignal: 'Registers for 3+ races/year with avg $150+ entry fees plus running store purchases',
    extensionProduct: 'Sports Massage & Recovery Packages',
    extensionMerchant: 'Massage Envy / Hand & Stone',
    extensionCategory: 'Health & Wellness',
    whyItFits: '78% of marathon finishers use massage therapy within 2 weeks post-race. Recovery spending is a near-universal behavior for endurance athletes.',
    mccDisconnectNote: 'MCC 7298 (Health Spa) has no connection to MCC 7941 (Athletic Events). MCCs treat spa visits and race entries as unrelated activities.',
    addressableUsers: 2_100_000,
    estimatedRevenue: 48_000_000,
    projectedConversionRate: 16.5,
    confidenceScore: 78,
    matchingPersonas: ['Marathon Runner', 'Fitness Devotee', 'Health Optimizer'],
    topAgeRanges: ['25-34', '35-44', '45-54'],
    topRegions: ['Northeast', 'Pacific', 'Southeast'],
    peakSpendingWeeks: 'Weeks 14-18, 38-42',
    optimalDeploymentWindow: 'Mar 1 - Apr 30, Sep 1 - Oct 31',
    deploymentRationale: 'Spring and fall marathon seasons drive predictable recovery spending. Deploy 1 week before major race weekends.',
    priority: 'medium',
  },
  {
    id: 'marathon-compression',
    sourcePillar: 'Sports & Active Living',
    sourceCategory: 'Running & Endurance',
    sourceSubcategory: 'Running Shoes & Apparel',
    behavioralSignal: 'Spends $800+/year on running shoes and apparel at specialty retailers',
    extensionProduct: 'CEP Compression Socks & Recovery Gear',
    extensionMerchant: 'Fleet Feet / Road Runner Sports',
    extensionCategory: 'Health & Wellness',
    whyItFits: '72% of runners spending $800+/year on shoes also purchase compression and recovery products. The correlation is strongest among 35-54 age group.',
    mccDisconnectNote: 'MCC 5941 (Sporting Goods) and MCC 5947 (Gift/Novelty) capture these differently. No MCC signals the athletic recovery intent.',
    addressableUsers: 1_600_000,
    estimatedRevenue: 34_000_000,
    projectedConversionRate: 12.1,
    confidenceScore: 72,
    matchingPersonas: ['Marathon Runner', 'Weekend Warrior', 'Fitness Devotee'],
    topAgeRanges: ['35-44', '45-54'],
    topRegions: ['Northeast', 'Pacific', 'Mountain West'],
    peakSpendingWeeks: 'Weeks 1-6, 14-18',
    optimalDeploymentWindow: 'Jan 1 - Feb 15, Mar 15 - May 1',
    deploymentRationale: 'New Year resolution runners and spring marathon training windows drive highest demand for recovery products.',
    priority: 'medium',
  },
  {
    id: 'newparents-lifeinsurance',
    sourcePillar: 'Family & Community',
    sourceCategory: 'Childcare & Education',
    sourceSubcategory: 'Baby Products & Maternity',
    behavioralSignal: 'First-time baby product purchases (strollers, cribs, maternity) totaling $3K+ in 90 days',
    extensionProduct: 'Term Life Insurance Policies',
    extensionMerchant: 'Haven Life / Ladder Insurance',
    extensionCategory: 'Financial & Aspirational',
    whyItFits: '85% of new parents purchase life insurance within 12 months of their first child. Becoming a parent is the single strongest trigger for financial protection.',
    mccDisconnectNote: 'MCC 6300 (Insurance) has zero linkage to MCC 5945 (Hobby/Toy Stores) or MCC 5641 (Children\'s Apparel). MCCs cannot detect life stage transitions.',
    addressableUsers: 3_400_000,
    estimatedRevenue: 142_000_000,
    projectedConversionRate: 22.4,
    confidenceScore: 85,
    matchingPersonas: ['New Parent', 'Growing Family', 'Financial Planner'],
    topAgeRanges: ['25-34', '30-39'],
    topRegions: ['Southeast', 'Midwest', 'Southwest'],
    peakSpendingWeeks: 'Year-round (life event triggered)',
    optimalDeploymentWindow: '60-90 days after first baby purchase cluster detected',
    deploymentRationale: 'Behavioral signal is strongest 2-3 months after baby product spending begins — parents have settled into routines and are thinking long-term.',
    priority: 'high',
  },
  {
    id: 'newparents-homesecurity',
    sourcePillar: 'Family & Community',
    sourceCategory: 'Childcare & Education',
    sourceSubcategory: 'Baby Products & Maternity',
    behavioralSignal: 'New parents with $5K+ baby spend who also have mortgage payments',
    extensionProduct: 'Ring / SimpliSafe Home Security',
    extensionMerchant: 'Ring / Amazon / Best Buy',
    extensionCategory: 'Home & Living',
    whyItFits: '68% of new homeowner parents install home security within 6 months of a child\'s birth. Safety concern spikes dramatically post-baby.',
    mccDisconnectNote: 'MCC 7382 (Security Services) has no connection to MCC 5945 (Baby Products). Traditional systems can\'t detect the parenting → security behavior chain.',
    addressableUsers: 1_800_000,
    estimatedRevenue: 54_000_000,
    projectedConversionRate: 18.6,
    confidenceScore: 68,
    matchingPersonas: ['New Parent', 'Homeowner', 'Safety-Conscious'],
    topAgeRanges: ['28-38'],
    topRegions: ['Suburbs nationwide', 'Southeast', 'Midwest'],
    peakSpendingWeeks: 'Year-round (life event triggered)',
    optimalDeploymentWindow: '30-60 days after baby product cluster + mortgage detected',
    deploymentRationale: 'Nesting instinct peaks in the month before and after birth. Home security is a natural extension of the protective mindset.',
    priority: 'medium',
  },
  {
    id: 'newparents-529',
    sourcePillar: 'Family & Community',
    sourceCategory: 'Childcare & Education',
    sourceSubcategory: 'Baby Products & Maternity',
    behavioralSignal: 'New parents with household income $120K+ and existing investment accounts',
    extensionProduct: '529 College Savings Plans',
    extensionMerchant: 'Fidelity / Vanguard / State Plans',
    extensionCategory: 'Financial & Aspirational',
    whyItFits: '74% of high-income new parents open a 529 plan within 18 months. Early contributions have 18+ years of compound growth — urgency messaging works.',
    mccDisconnectNote: 'MCC 6211 (Security Brokers) is disconnected from all family-related MCCs. Financial product targeting based on life stage is impossible with MCCs alone.',
    addressableUsers: 1_200_000,
    estimatedRevenue: 96_000_000,
    projectedConversionRate: 15.8,
    confidenceScore: 74,
    matchingPersonas: ['New Parent', 'Financial Planner', 'High Earner'],
    topAgeRanges: ['28-38', '35-44'],
    topRegions: ['Northeast', 'Pacific', 'Mountain West'],
    peakSpendingWeeks: 'Year-round (strongest Q4 for tax benefits)',
    optimalDeploymentWindow: 'Oct-Dec (tax planning season) for parents with babies <12 months',
    deploymentRationale: 'Year-end tax planning creates natural urgency. Combine with new-parent behavioral signal for highest conversion.',
    priority: 'high',
  },
  {
    id: 'renovators-smarthome',
    sourcePillar: 'Home & Living',
    sourceCategory: 'Home Improvement',
    sourceSubcategory: 'Renovation & Remodeling',
    behavioralSignal: 'Spends $8K+ at Home Depot/Lowe\'s in a 6-month window (renovation pattern)',
    extensionProduct: 'Nest / Ecobee Smart Home Bundle',
    extensionMerchant: 'Google Store / Amazon / Best Buy',
    extensionCategory: 'Technology & Digital Life',
    whyItFits: '71% of homeowners who complete major renovations add smart home tech within 3 months. New installations create a natural \'upgrade moment\' for smart thermostats, locks, and cameras.',
    mccDisconnectNote: 'MCC 5200 (Home Supply) and MCC 5732 (Electronics) are separate categories. MCCs can\'t detect the renovation → smart home upgrade behavior sequence.',
    addressableUsers: 2_800_000,
    estimatedRevenue: 78_000_000,
    projectedConversionRate: 13.4,
    confidenceScore: 71,
    matchingPersonas: ['Homeowner', 'Tech Adopter', 'Home Improver'],
    topAgeRanges: ['30-44', '45-54'],
    topRegions: ['Southeast', 'Southwest', 'Midwest'],
    peakSpendingWeeks: 'Weeks 14-28',
    optimalDeploymentWindow: 'Apr - Jul (peak renovation season)',
    deploymentRationale: 'Spring/summer renovation peak creates a 3-month window where smart home upsell conversion is highest.',
    priority: 'medium',
  },
  {
    id: 'foodies-cookingclass',
    sourcePillar: 'Food & Dining',
    sourceCategory: 'Dining Out',
    sourceSubcategory: 'Fine Dining & Specialty Restaurants',
    behavioralSignal: 'Dines at fine dining restaurants 4+ times/month with avg check $150+',
    extensionProduct: 'Sur La Table / Williams Sonoma Cooking Classes',
    extensionMerchant: 'Sur La Table / Williams Sonoma',
    extensionCategory: 'Entertainment & Culture',
    whyItFits: '62% of frequent fine diners express interest in culinary skills. The same passion that drives dining out also drives cooking at home — these are food lovers, not just restaurant-goers.',
    mccDisconnectNote: 'MCC 5812 (Restaurants) and MCC 8299 (Educational Services) are entirely separate. MCCs can\'t connect dining passion to culinary education interest.',
    addressableUsers: 1_400_000,
    estimatedRevenue: 32_000_000,
    projectedConversionRate: 9.8,
    confidenceScore: 62,
    matchingPersonas: ['Foodie', 'Culinary Explorer', 'Experience Seeker'],
    topAgeRanges: ['30-44', '45-54', '55-64'],
    topRegions: ['Pacific', 'Northeast', 'Southeast'],
    peakSpendingWeeks: 'Weeks 1-10, 36-44',
    optimalDeploymentWindow: 'Jan-Mar (New Year resolution cooks), Sep-Nov (fall entertaining)',
    deploymentRationale: 'New Year and fall entertaining seasons create natural spikes in culinary curiosity. Partner during these windows for maximum enrollment.',
    priority: 'low',
  },
  {
    id: 'petowners-insurance',
    sourcePillar: 'Pets',
    sourceCategory: 'Pet Care',
    sourceSubcategory: 'Veterinary & Pet Health',
    behavioralSignal: 'Spends $1,500+/year on vet visits and pet supplies with increasing frequency',
    extensionProduct: 'Lemonade / Trupanion Pet Insurance',
    extensionMerchant: 'Lemonade / Trupanion',
    extensionCategory: 'Financial & Aspirational',
    whyItFits: '70% of pet owners who spend $1,500+/year on vet care are highly receptive to pet insurance. Rising vet costs create urgency — one emergency can cost $5K+.',
    mccDisconnectNote: 'MCC 742 (Veterinary Services) and MCC 6300 (Insurance) are completely unrelated categories. MCCs can\'t connect pet health spending to insurance readiness.',
    addressableUsers: 4_200_000,
    estimatedRevenue: 68_000_000,
    projectedConversionRate: 19.2,
    confidenceScore: 70,
    matchingPersonas: ['Pet Parent', 'Animal Lover', 'Risk-Aware'],
    topAgeRanges: ['25-34', '35-44', '55-64'],
    topRegions: ['Pacific', 'Northeast', 'Southeast'],
    peakSpendingWeeks: 'Year-round (strongest after large vet bills)',
    optimalDeploymentWindow: '7-14 days after a vet bill exceeding $500 is detected',
    deploymentRationale: 'Post-emergency vet bills are the highest-conversion moment for pet insurance. Strike while the financial pain is fresh.',
    priority: 'high',
  },
  {
    id: 'frequentflyers-headphones',
    sourcePillar: 'Travel & Exploration',
    sourceCategory: 'Air Travel',
    sourceSubcategory: 'Airline Tickets & Upgrades',
    behavioralSignal: 'Books 8+ flights/year with average ticket price $450+',
    extensionProduct: 'Sony WH-1000XM5 / Bose QuietComfort Ultra',
    extensionMerchant: 'Sony / Bose / Best Buy',
    extensionCategory: 'Technology & Digital Life',
    whyItFits: '83% of frequent flyers (8+ flights/year) own or are actively shopping for noise-canceling headphones. It\'s the most universal travel accessory purchase.',
    mccDisconnectNote: 'MCC 4511 (Airlines) and MCC 5732 (Electronics) are entirely separate. MCCs cannot detect that someone who flies frequently is a prime headphone buyer.',
    addressableUsers: 2_600_000,
    estimatedRevenue: 92_000_000,
    projectedConversionRate: 15.7,
    confidenceScore: 83,
    matchingPersonas: ['Business Traveler', 'Frequent Flyer', 'Tech Enthusiast'],
    topAgeRanges: ['30-44', '45-54'],
    topRegions: ['Northeast', 'Pacific', 'Southeast'],
    peakSpendingWeeks: 'Weeks 44-52',
    optimalDeploymentWindow: 'Nov 1 - Dec 25 (Holiday gifting + year-end travel)',
    deploymentRationale: 'Holiday season combines gift-giving with peak business travel. Noise-canceling headphones are the #1 tech gift for travelers.',
    priority: 'high',
  },
  {
    id: 'footballfans-tailgating',
    sourcePillar: 'Entertainment & Culture',
    sourceCategory: 'Live Events & Sports',
    sourceSubcategory: 'Sporting Event Tickets',
    behavioralSignal: 'Purchases 4+ football game tickets/season plus sports bar spending during game days',
    extensionProduct: 'Weber Grill / YETI Cooler Tailgating Bundle',
    extensionMerchant: 'Weber / YETI / Dick\'s Sporting Goods',
    extensionCategory: 'Home & Living',
    whyItFits: '67% of season ticket holders spend $500+ annually on tailgating gear. The stadium parking lot is an extension of their entertainment experience.',
    mccDisconnectNote: 'MCC 7941 (Sports Events) and MCC 5251 (Hardware/Home) are entirely separate. MCCs can\'t link game tickets to grill purchases.',
    addressableUsers: 3_100_000,
    estimatedRevenue: 58_000_000,
    projectedConversionRate: 11.3,
    confidenceScore: 67,
    matchingPersonas: ['Sports Fan', 'Tailgater', 'Social Entertainer'],
    topAgeRanges: ['25-34', '35-44', '45-54'],
    topRegions: ['Southeast', 'Midwest', 'Southwest'],
    peakSpendingWeeks: 'Weeks 32-38',
    optimalDeploymentWindow: 'Aug 1 - Sep 15 (Pre-season / Season opener)',
    deploymentRationale: 'Tailgating gear purchases peak before the football season starts. Deploy when excitement is highest and pre-season games begin.',
    priority: 'medium',
  },
  {
    id: 'travelers-insurance',
    sourcePillar: 'Travel & Exploration',
    sourceCategory: 'International Travel',
    sourceSubcategory: 'International Flights & Hotels',
    behavioralSignal: 'Books 2+ international trips/year with total travel spend $8K+',
    extensionProduct: 'Allianz / World Nomads Travel Insurance',
    extensionMerchant: 'Allianz / World Nomads',
    extensionCategory: 'Financial & Aspirational',
    whyItFits: '76% of international travelers spending $8K+/year purchase trip insurance. High-value trips create natural insurance buying behavior.',
    mccDisconnectNote: 'MCC 4511 (Airlines) and MCC 6300 (Insurance) are separate. Traditional systems can\'t connect international booking patterns to insurance purchase intent.',
    addressableUsers: 1_900_000,
    estimatedRevenue: 44_000_000,
    projectedConversionRate: 18.9,
    confidenceScore: 76,
    matchingPersonas: ['International Traveler', 'Adventure Seeker', 'Risk-Aware'],
    topAgeRanges: ['35-44', '45-54', '55-64'],
    topRegions: ['Pacific', 'Northeast', 'Southeast'],
    peakSpendingWeeks: 'Weeks 2-12, 22-28',
    optimalDeploymentWindow: 'Jan-Mar (spring/summer trip booking), Jun-Jul (fall trip booking)',
    deploymentRationale: 'Insurance purchase intent peaks at the moment of booking. Offer at checkout or within 48 hours of flight purchase.',
    priority: 'medium',
  },
  {
    id: 'homegym-nutrition',
    sourcePillar: 'Health & Wellness',
    sourceCategory: 'Fitness & Exercise',
    sourceSubcategory: 'Gym Memberships & Equipment',
    behavioralSignal: 'Spends $200+/month on gym memberships or $2K+ on home fitness equipment',
    extensionProduct: 'Athletic Greens / Optimum Nutrition Supplements',
    extensionMerchant: 'GNC / Amazon / Vitamin Shoppe',
    extensionCategory: 'Health & Wellness',
    whyItFits: '81% of gym members spending $200+/month also purchase supplements. Fitness commitment and nutrition spending are tightly correlated behaviors.',
    mccDisconnectNote: 'MCC 7941 (Health Clubs) and MCC 5912 (Drug Stores) track differently. MCCs can\'t distinguish a supplement buyer at CVS from a cold medicine buyer.',
    addressableUsers: 3_800_000,
    estimatedRevenue: 72_000_000,
    projectedConversionRate: 20.4,
    confidenceScore: 81,
    matchingPersonas: ['Fitness Devotee', 'Health Optimizer', 'Resolution Maker'],
    topAgeRanges: ['22-34', '35-44'],
    topRegions: ['Pacific', 'Northeast', 'Southeast', 'Southwest'],
    peakSpendingWeeks: 'Weeks 1-8',
    optimalDeploymentWindow: 'Dec 26 - Feb 28 (New Year fitness surge)',
    deploymentRationale: 'New Year resolution gym spending creates a massive nutrition supplement upsell window. 88% of new memberships happen in Weeks 1-6.',
    priority: 'high',
  },
  {
    id: 'gardeners-farmersmarket',
    sourcePillar: 'Home & Living',
    sourceCategory: 'Garden & Outdoor',
    sourceSubcategory: 'Garden Centers & Nurseries',
    behavioralSignal: 'Spends $600+/year at garden centers and nurseries with spring peak',
    extensionProduct: 'CSA Memberships / Farmers Market Gift Cards',
    extensionMerchant: 'Local Harvest / farmersmarket.com',
    extensionCategory: 'Food & Dining',
    whyItFits: '58% of avid gardeners are also regular farmers market shoppers. The farm-to-table mindset connects growing plants to sourcing fresh, local food.',
    mccDisconnectNote: 'MCC 5261 (Nurseries/Garden) and MCC 5411 (Grocery) are separate. MCCs treat garden spending and food sourcing as unrelated behaviors.',
    addressableUsers: 2_200_000,
    estimatedRevenue: 28_000_000,
    projectedConversionRate: 8.2,
    confidenceScore: 58,
    matchingPersonas: ['Home Gardener', 'Farm-to-Table', 'Eco-Conscious'],
    topAgeRanges: ['35-44', '45-54', '55-64'],
    topRegions: ['Pacific', 'Northeast', 'Midwest'],
    peakSpendingWeeks: 'Weeks 14-26',
    optimalDeploymentWindow: 'Apr - Jun (spring planting season)',
    deploymentRationale: 'Spring gardening season and farmers market openings coincide perfectly. Deploy when the grow-your-own mindset is strongest.',
    priority: 'low',
  },
  {
    id: 'gamers-ergonomic',
    sourcePillar: 'Technology & Digital Life',
    sourceCategory: 'Gaming',
    sourceSubcategory: 'Gaming Hardware & Subscriptions',
    behavioralSignal: 'Spends $1,200+/year on gaming hardware, subscriptions, and in-game purchases',
    extensionProduct: 'Secretlab / Herman Miller Gaming Chair',
    extensionMerchant: 'Secretlab / Herman Miller / Amazon',
    extensionCategory: 'Home & Living',
    whyItFits: '73% of gamers spending $1,200+/year prioritize ergonomic setups. Extended gaming sessions (avg 14 hrs/week for this cohort) make comfort a necessity, not a luxury.',
    mccDisconnectNote: 'MCC 5734 (Computer Software) and MCC 5712 (Furniture) are entirely separate. MCCs can\'t detect that a software subscription buyer needs a better chair.',
    addressableUsers: 2_400_000,
    estimatedRevenue: 52_000_000,
    projectedConversionRate: 10.6,
    confidenceScore: 73,
    matchingPersonas: ['Gamer', 'Tech Enthusiast', 'Remote Worker'],
    topAgeRanges: ['18-24', '25-34'],
    topRegions: ['Pacific', 'Southwest', 'Northeast'],
    peakSpendingWeeks: 'Weeks 44-52',
    optimalDeploymentWindow: 'Nov 1 - Dec 31 (Holiday + Black Friday)',
    deploymentRationale: 'Black Friday and holiday gifting season is when gaming setup upgrades peak. Bundle chair deals with gaming hardware promotions.',
    priority: 'medium',
  },
];

// Aggregate stats for dashboard header
export function getCategoryExtensionSummary() {
  const totalRevenue = CATEGORY_EXTENSION_OPPORTUNITIES.reduce((sum, o) => sum + o.estimatedRevenue, 0);
  const totalUsers = CATEGORY_EXTENSION_OPPORTUNITIES.reduce((sum, o) => sum + o.addressableUsers, 0);
  const highPriority = CATEGORY_EXTENSION_OPPORTUNITIES.filter(o => o.priority === 'high').length;
  const avgConfidence = CATEGORY_EXTENSION_OPPORTUNITIES.reduce((sum, o) => sum + o.confidenceScore, 0) / CATEGORY_EXTENSION_OPPORTUNITIES.length;

  return {
    totalOpportunities: CATEGORY_EXTENSION_OPPORTUNITIES.length,
    totalEstimatedRevenue: totalRevenue,
    totalAddressableUsers: totalUsers,
    highPriorityCount: highPriority,
    avgConfidenceScore: Math.round(avgConfidence),
  };
}
