export type DeckmoBeatId = "opener" | "visibility" | "living-view" | "assembly" | "ricky" | "immediate" | "mid-term" | "long-term" | "bank-tools" | "close";

export const DECKMO = {
  chrome: {
    progress: "Story progress",
    presenterHint: "Press P for presenter view",
    presenterTitle: "Presenter navigator",
    presenterClose: "Close presenter navigator",
    previous: "Previous",
    next: "Next",
    exit: "Exit",
    desktopTitle: "Desktop Required",
    desktopBody: "This conference experience is designed for screens at least 1024 pixels wide.",
    returnHome: "Return to Home",
    gateTagline: "A scripted customer intelligence story for bank leaders",
    gateBullets: ["Customer intelligence", "Personalized experiences", "Bank-wide orchestration"],
  },
  beats: [
    { id: "opener", nav: "Opening", steps: 3 },
    { id: "visibility", nav: "The visibility gap", steps: 2 },
    { id: "living-view", nav: "One customer view", steps: 2 },
    { id: "assembly", nav: "System assembly", steps: 4 },
    { id: "ricky", nav: "Meet Ricky", steps: 2 },
    { id: "immediate", nav: "Immediate value", steps: 4 },
    { id: "mid-term", nav: "Mid-term value", steps: 5 },
    { id: "long-term", nav: "Long-term value", steps: 3 },
    { id: "bank-tools", nav: "Tools for the bank", steps: 3 },
    { id: "close", nav: "Close", steps: 4 },
  ],
  opener: {
    eyebrow: "VENTUS AI",
    lines: [
      "Banking is personal. Or at least, it used to be.",
      "We cannot speak to millions of digital customers. And if we cannot see the person, we cannot personalize.",
      "Your personalization is your differentiation.",
    ],
  },
  visibility: {
    eyebrow: "THE VISIBILITY GAP",
    title: "You cannot personalize what you cannot see.",
    subtitle: "First-party transaction data is observed, but lagging and partial. It ends at the institution's walls.",
    inside: { header: "INSIDE THE WALLS", caption: "What the ledger records", status: "visible", rows: ["Some checks", "Some wires", "Some card swipes with rough category codes", "Some transfers"] },
    outside: { header: "OUTSIDE THE WALLS", caption: "What else goes on", status: "not visible", empty: "The rest of the customer remains out of view", rows: ["Bought a house", "Changed to a new job", "Got married", "Started a business", "Took a trip overseas", "Children going to college", "And everything in between"] },
  },
  livingView: {
    eyebrow: "THE COMPLETE PICTURE",
    title: "Ventus AI: Holistic AI Customer Intelligence",
    subtitle: "Combining and synthesizing internal and external data to gain a dynamic understanding of each customer",
    inside: { header: "INSIDE THE WALLS", title: "Rail-agnostic transaction enrichment", chips: ["Checks", "Wires", "Zelle", "Card swipes", "P2P", "Digital telemetry"] },
    outside: { header: "OUTSIDE THE WALLS", title: "Source-agnostic behavioral intelligence", chips: ["Credit bureaus", "Data compilers", "National databases"], note: "For marketing and personalization only" },
    result: { header: "ONE LIVING CUSTOMER VIEW", body: "What they do, and what do they need next?" },
  },
  assembly: {
    eyebrow: "THE SYSTEM",
    title: "From understanding to action",
    subtitle: "One intelligence layer orchestrates personalized experiences across the bank.",
    columns: ["TRANSACTIONS", "MODULAR PLATFORM", "FEATURE ORCHESTRATION", "NEXT-GEN BANKING EXPERIENCE"],
    engine: "Ventus AI Module Suites",
    sources: ["Internal enrichment", "External intelligence", "Living profile"],
    modules: ["Customer Intelligence", "AI & UX", "Rewards", "Relationship"],
    rows: [
      { name: "Experience", question: "Make every transaction easier to understand", capabilities: ["Lifestyle pillars", "Outflow insights", "Financial guidance"], result: "Personalized AI & UX" },
      { name: "Rewards", question: "Anticipate what matters next", capabilities: ["Next-purchase intelligence", "Local experiences", "Deal personalization"], result: "Personalized Rewards" },
      { name: "Relationship", question: "Show up for the next life moment", capabilities: ["Life-event detection", "Product automation", "Advisor intelligence"], result: "Personalized Relationship" },
    ],
  },
  ricky: {
    eyebrow: "ONE CUSTOMER, FIVE SIGNAL FAMILIES",
    title: "Meet Ricky",
    subtitle: "A handful of ledger entries become a living view of the person behind the account.",
    rawLabel: "RAW TRANSACTION STRINGS",
    signalLabel: "SYNTHESIZED CUSTOMER SIGNALS",
    raw: ["MCC 5941 SPORTING GOODS", "MCC 4722 TRAVEL AGENCIES", "MCC 5812 EATING PLACES", "WIRE", "CHECK", "ACH TRANSFER"],
    signals: [
      { family: "Behavioral", label: "Bi-weekly advanced tennis", tone: "blue" },
      { family: "Behavioral", label: "Annual Hawaiian vacation", tone: "blue" },
      { family: "Life Events", label: "Buying a house above $1.5M", tone: "amber" },
      { family: "Financial", label: "Recurring transfer to brokerage", tone: "emerald" },
      { family: "Demographics", label: "Small business owner", tone: "violet" },
      { family: "Risk", label: "Increasing sports betting", tone: "rose" },
    ],
    profileTitle: "Ricky's living profile",
    profileBody: "Affluent homeowner, active traveler, tennis regular, business owner, and an emerging relationship opportunity.",
  },
  immediate: {
    eyebrow: "IMMEDIATE",
    title: "Make every transaction understandable",
    subtitle: "Enriched transaction experiences that make charges easier to recognize and can reduce transaction-related service calls and inquiries.",
    phoneTitle: "Recent activity",
    account: "Our Bank checking",
    transactions: [
      { raw: "SQ *NORTHSTAR 4471", clean: "Northstar Market", meta: "Groceries · Food & Dining", badge: "Recurring" },
      { raw: "TST*COURTSIDE NYC", clean: "Courtside Tennis Club", meta: "Fitness · Sports & Active Living", badge: "Every other week" },
      { raw: "HNL AIR 006121", clean: "Hawaiian Airlines", meta: "Air travel · Travel & Exploration", badge: "Trip detected" },
      { raw: "POS DEBIT 59382", clean: "Home Design Studio", meta: "Home improvement · Home & Living", badge: "New pattern" },
    ],
    popups: [
      { title: "A clean merchant identity", body: "A cryptic ledger string resolves into a recognizable merchant and location." },
      { title: "Lifestyle context", body: "Each charge receives a category and a broader lifestyle pillar." },
      { title: "Patterns, not just purchases", body: "Recurring activity and subscriptions become visible automatically." },
      { title: "A useful explanation", body: "A tap explains the charge in plain language, with context from the customer's own activity." },
    ],
    explainer: { title: "Recognize this charge?", body: "This appears to be your recurring tennis club visit. It matches your usual every-other-week pattern.", action: "Yes, that's mine" },
  },
  midTerm: {
    eyebrow: "MID-TERM",
    title: "Turn understanding into relevant growth",
    subtitle: "Hyper-personalized card-linked offers and cross-sell programs create new revenue opportunities while helping identify the right banking product for each customer at the right moment.",
    phoneTitle: "Selected for Ricky",
    topPick: { label: "TOP PICK", title: "Your next island escape", body: "Travel benefits shaped around Ricky's annual vacation pattern.", benefit: "Roughly $150 in value on a similar trip", action: "View travel benefits", family: "Behavioral" },
    categories: ["For you", "Travel", "Tennis", "Dining", "Home"],
    deals: [
      { title: "Airport lounge access", detail: "Before the next Hawaii trip", family: "Behavioral" },
      { title: "Premium racquet fitting", detail: "For the next tennis season", family: "Behavioral" },
      { title: "Home design consultation", detail: "Timed to the home purchase journey", family: "Life Events" },
    ],
    product: { title: "Home lending relationship", body: "A tailored home loan relationship can support the next move.", benefit: "0.5% lower APR", action: "Explore options", family: "Life Events" },
    placement: { title: "One asset, placed everywhere", channels: ["Digital banking", "Email", "Relationship manager", "Marketing/CRM automation"] },
    popups: ["Top pick built from observed behavior", "Interests become browsable collections", "Every recommendation traces to a signal", "Benefits are made concrete", "The same experience travels across channels"],
  },
  longTerm: {
    eyebrow: "LONG-TERM",
    title: "Build a relationship that evolves",
    subtitle: "A more personalized banking relationship can deepen engagement, improve retention and NPS, and help the bank grow primary banking relationships and share of wallet.",
    phoneTitle: "Ricky's relationship",
    event: { label: "LIFE EVENT DETECTED", title: "Home purchase journey", body: "A sustained cluster of housing-related activity indicates Ricky may be preparing for a move." },
    advisor: { label: "NEXT CONVERSATION", title: "Talk through the new home plan", body: "A relationship manager receives the context, timing, and a concise conversation guide." },
    outreach: { label: "FOLLOW-UP READY", title: "A personal note, already drafted", body: "Ricky receives relevant help without exposing sensitive or risk-related signals.", action: "Review draft" },
    popups: ["Detect the life moment", "Prepare the next conversation", "Coordinate thoughtful outreach"],
  },
  bankTools: {
    eyebrow: "TOOLS FOR THE BANK",
    title: "Possible for Ricky because it is possible for every customer",
    subtitle: "The same intelligence becomes an operating system for teams across your bank.",
    screens: [
      {
        id: "database", tab: "INTELLIGENCE DATABASE", title: "Every signal opens the segment behind it", description: "Explore customer groups, export audiences, automate reports, connect through APIs, or ask embedded AI a free-form question.",
        families: [
          { label: "Behavioral", count: 11, tone: "blue" }, { label: "Life Event", count: 9, tone: "amber" }, { label: "Financial", count: 9, tone: "emerald" }, { label: "Demographic", count: 13, tone: "violet" }, { label: "Risk", count: 14, tone: "rose" },
        ],
        actions: ["Open segment", "Export audience", "Ask Ventus AI"],
      },
      {
        id: "flows", tab: "AUTOMATED FLOWS", title: "Products activated by the right signals", description: "Teams can edit each signal, define exclusions, and set guardrails before any experience reaches a customer.",
        flows: [
          { name: "529 College Savings", triggers: ["New child", "College-bound child", "Tutoring spend spike"] },
          { name: "Home Equity Line", triggers: ["Homeowner", "Renovation", "Tuition or medical liquidity need"] },
        ],
        guardrail: { label: "POLICY GUARDRAIL", title: "Increasing sports betting", body: "Visible to authorized bank teams. Excluded from every customer-facing offer, product, and message." },
      },
      {
        id: "coworker", tab: "AI COWORKER", title: "Intelligence delivered like a teammate", description: "Daily digests, reply threads, drafted documents, and ready-to-review relationship tasks, tailored by role.",
        inbox: [
          { role: "Bank leadership", subject: "Weekly trends and emerging opportunities", preview: "The strongest patterns, customer needs, and actions to consider this week." },
          { role: "Relationship manager", subject: "Three conversations worth having", preview: "Client A is buying a home. Client B is preparing for retirement. Client C fits the premium travel card." },
          { role: "Product and growth", subject: "New high-fit segments ready for review", preview: "Product opportunities with signal rationale, exclusions, and draft activation plans." },
        ],
        reply: "Reply to ask a follow-up, request a draft, or route the next action.",
      },
    ],
  },
  close: {
    eyebrow: "PERSONALIZATION BECOMES DIFFERENTIATION",
    lines: [
      "Too many banking experiences are generic and replaceable.",
      "With Ventus, the experience evolves with every customer.",
      "Personalization becomes differentiation.",
    ],
    outcomes: ["More card spend", "More products", "More deposits"],
    cta: "Schedule a conversation",
    href: "/contact",
    exhibit: "Come find us in the exhibit hall.",
  },
} as const;

export const DECKMO_STEPS = DECKMO.beats.flatMap((beat, section) =>
  Array.from({ length: beat.steps }, (_, step) => ({ section, step, id: `${beat.id}-${step}` })),
);
