import {
  GraduationCap,
  Home,
  Briefcase,
  Car,
  Building2,
  Building,
  PiggyBank,
  Plane,
  Store,
  HandCoins,
  Shield,
  Wallet,
  Banknote,
  Landmark,
  CreditCard,
  Receipt,
  TrendingUp,
  Wrench,
  LineChart,
  Bot,
  UserCheck,
  Crown,
  FileSpreadsheet,
  HeartHandshake,
  Umbrella,
  RefreshCw,
  Tag,
  Gem,
  Leaf,
  Scale,
  Globe,
  Heart,
  Truck,
  Gift,
  Ship,
  Bike,
  Hammer,
  Key,
  BarChart3,
  Smile,
  Lock,
  Backpack,
  PawPrint,
  Fingerprint,
  HeartPulse,
  Accessibility,
  type LucideIcon,
} from "lucide-react";

export type FlowCategory =
  | "Lending"
  | "Wealth"
  | "Deposits"
  | "Cards"
  | "Insurance";

export type SignalType = "life-event" | "behavioral";

export interface FlowSignal {
  label: string;
  evidence: string;
  type: SignalType;
}

export interface ProductFlow {
  id: string;
  name: string;
  category: FlowCategory;
  icon: LucideIcon;
  positioning: string;
  signals: FlowSignal[];
  estimatedAudience: number; // out of ~250M
  penetration: number; // 0-1, share of base eligible
  defaultActive?: boolean;
}

export const PRODUCT_FLOWS: ProductFlow[] = [
  // ===== WEALTH =====
  {
    id: "529-plan",
    name: "529 College Savings Plan",
    category: "Wealth",
    icon: GraduationCap,
    positioning: "Tax-advantaged education savings for families with young or college-bound children.",
    signals: [
      { label: "Newborn / toddler expense cluster", evidence: "Clustered spend at baby supply retailers, pediatric specialist copays (card), and daycare tuition (ACH) post-birth record.", type: "life-event" },
      { label: "College-bound dependent inferred", evidence: "Tuition payments to academic institutions (ACH/bill-pay), standardized test fees (card), and out-of-town travel to university towns.", type: "life-event" },
      { label: "Education savings visibility", evidence: "Outbound ACH transfers to known 529 plan providers or brokerage education accounts, alongside internal transfers.", type: "behavioral" },
    ],
    estimatedAudience: 28_400_000,
    penetration: 0.057,
    defaultActive: true,
  },
  {
    id: "self-directed-brokerage",
    name: "Self-Directed Brokerage",
    category: "Wealth",
    icon: LineChart,
    positioning: "Commission-free online trading for customers who want to manage their own portfolio.",
    signals: [
      { label: "External brokerage funding", evidence: "Regular ACH transfers or bill-pay to self-directed investment platforms beyond bank's offerings.", type: "behavioral" },
      { label: "Diversified crypto exposure", evidence: "Card or ACH outflows to multiple cryptocurrency exchanges, including 'VEN*Crypto' or 'SQC*Coinbase'.", type: "behavioral" },
      { label: "Investment research & cash hoarding", evidence: "Sustained high checking balances coupled with subscription payments to investment research services or financial news.", type: "behavioral" },
    ],
    estimatedAudience: 44_000_000,
    penetration: 0.088,
    defaultActive: true,
  },
  {
    id: "robo-portfolio",
    name: "Robo / Guided Portfolio",
    category: "Wealth",
    icon: Bot,
    positioning: "Algorithm-built diversified portfolio for hands-off investors at low cost.",
    signals: [
      { label: "New investor building capital", evidence: "Multiple small-dollar P2P transfers and recurring ACH debits to investment platforms/brokerages like 'VEN*ACORN', 'CHASE INV' after initial funding.", type: "behavioral" },
      { label: "Competitive wealth product funding", evidence: "Significant outbound ACH transfers/wires from DDA to external brokerage or robo-advisor (~$5k+) not associated with existing bank-managed investments.", type: "behavioral" },
      { label: "Late-career asset consolidation", evidence: "Large, infrequent inbound ACH credits/wires from pension or 401k administrators, followed by transfers to a new singular brokerage account with robo-advisor features.", type: "life-event" },
    ],
    estimatedAudience: 35_000_000,
    penetration: 0.070,
  },
  {
    id: "hybrid-advisor-portfolio",
    name: "Hybrid Advisor Portfolio",
    category: "Wealth",
    icon: UserCheck,
    positioning: "Managed portfolio with on-demand human advisor for mass-affluent households.",
    signals: [
      { label: "Wealth Accumulation Trigger", evidence: "Significant inflows from estate disbursement or business sale, followed by outflows to brokerage accounts or investment platforms.", type: "life-event" },
      { label: "Competitive Wealth Product Engagement", evidence: "Recurring outbound ACH transfers to external brokerage firms or investment robo-advisors; no matching inbound investment income.", type: "behavioral" },
      { label: "Professional Financial Guidance Seeking", evidence: "Frequent bill-pay to wealth management firms, financial advisors, or estate planning attorneys, coupled with large-value bank transfers.", type: "behavioral" },
    ],
    estimatedAudience: 18_400_000,
    penetration: 0.037,
  },
  {
    id: "wealth-management",
    name: "Wealth Management",
    category: "Wealth",
    icon: Briefcase,
    positioning: "Holistic advisory for high-net-worth households and complex balance sheets.",
    signals: [
      { label: "Diversified equity compensation inflows", evidence: "Significant quarterly inflows from corporate payroll (ACH) and brokerage (wire) indicating RSU vest, ESPP buyback, or option exercise.", type: "behavioral" },
      { label: "Multi-institution wealth management", evidence: "Consistent outbound ACHs over $10k to external brokerage or private bank names, coupled with wire transfers.", type: "behavioral" },
      { label: "Luxury lifestyle memberships", evidence: "Recurring card charges and ACH payments to canonical private clubs, golf courses, or fractional jet operators.", type: "behavioral" },
      { label: "Complex asset liquidation event", evidence: "Large inbound wire transfer from an estate counsel IOLTA or real estate attorney, following irregular outflows.", type: "life-event" },
    ],
    estimatedAudience: 12_800_000,
    penetration: 0.026,
    defaultActive: true,
  },
  {
    id: "private-wealth",
    name: "Private Wealth Management",
    category: "Wealth",
    icon: Crown,
    positioning: "Ultra-high-net-worth advisory with dedicated team, lending, and trust services.",
    signals: [
      { label: "Significant Liquidity Event", evidence: "Large inbound ACH or wire transfers from M&A escrow, trust disbursement, or capital gains, exceeding $5M.", type: "life-event" },
      { label: "Distributed Real Estate Portfolio", evidence: "Recurring property tax payments via ACH or bill-pay to multiple distinct municipal or county entities.", type: "behavioral" },
      { label: "Complex Financial Management", evidence: "Multiple payroll ACH outflows, inter-entity transfers, and recurring wire payments to various specialized financial counterparties (e.g., trust, legal).", type: "behavioral" },
    ],
    estimatedAudience: 1_700_000,
    penetration: 0.003,
  },
  {
    id: "ira",
    name: "Individual Retirement Account",
    category: "Wealth",
    icon: PiggyBank,
    positioning: "Tax-advantaged retirement account with Traditional, Roth, and Rollover options.",
    signals: [
      { label: "Retirement Account Consolidation", evidence: "Direct ACH transfers from external brokerage accounts (", type: "life-event" },
      { label: "Diversified Investment Strategy", evidence: "Regular, simultaneous ACH transfers to multiple investment platforms (brokerage, robo-advisor, alternative assets).", type: "behavioral" },
      { label: "Pre-Retirement Windfall", evidence: "Large, one-time inbound wire or ACH, followed by significant outbound investment vehicle funding transfers.", type: "life-event" },
    ],
    estimatedAudience: 56_000_000,
    penetration: 0.112,
    defaultActive: true,
  },
  {
    id: "trust-estate",
    name: "Trust & Estate Services",
    category: "Wealth",
    icon: Scale,
    positioning: "Multi-generational wealth structuring, trusteeship, and estate administration.",
    signals: [
      { label: "Estate Counsel Engaged", evidence: "Significant outgoing ACH/wire to identified estate counsel IOLTA, often alongside recurring bill-pay for legal retainers.", type: "life-event" },
      { label: "Eldercare Gifting/Payments", evidence: "Consistent P2P (Zelle/Venmo) transfers to family/caregivers, coupled with ACH payments to assisted living or home health providers.", type: "behavioral" },
      { label: "Wealth Transfer Indication", evidence: "Large inbound wire deposits from estate accounts, or outgoing ACH to multiple individual beneficiaries following a life event.", type: "life-event" },
    ],
    estimatedAudience: 4_800_000,
    penetration: 0.010,
  },
  {
    id: "values-portfolio",
    name: "Values-Aligned Portfolio",
    category: "Wealth",
    icon: Leaf,
    positioning: "Sustainable and impact-aligned managed portfolios for values-driven investors.",
    signals: [
      { label: "Ethical retail alignment", evidence: "Consistent spend at certified B-corp merchants and specialty organic grocers across card and P2P rails.", type: "behavioral" },
      { label: "Impact-driven philanthropy", evidence: "Regular, multi-rail donations to environmental NGOs and social justice organizations, alongside impact-fund contributions.", type: "behavioral" },
      { label: "Green vehicle adoption", evidence: "EV charging network subscriptions, home charging installations (ACH), and state-level EV rebate deposits.", type: "life-event" },
    ],
    estimatedAudience: 11_200_000,
    penetration: 0.022,
  },
  {
    id: "401k-rollover",
    name: "401(k) Rollover Service",
    category: "Wealth",
    icon: RefreshCw,
    positioning: "Seamless rollover of employer-sponsored retirement assets into an IRA or advisory account.",
    signals: [
      { label: "Job change or separation", evidence: "Final payroll deposit from a prior employer, followed by a large inbound ACH from a 401(k) administrator.", type: "life-event" },
      { label: "Retirement account fragmentation", evidence: "Multiple small inbound ACHs from prior employer plans, indicating scattered retirement assets.", type: "behavioral" },
      { label: "Advisory engagement", evidence: "Outbound transfers to a brokerage or advisory firm after a rollover inflow.", type: "behavioral" },
    ],
    estimatedAudience: 14_000_000,
    penetration: 0.028,
  },
  {
    id: "able-savings",
    name: "ABLE / Special Needs Savings",
    category: "Wealth",
    icon: Accessibility,
    positioning: "Tax-advantaged savings for individuals with disabilities and their families.",
    signals: [
      { label: "Special needs support spend", evidence: "Recurring ACH or card payments to therapy providers, special education services, or adaptive equipment suppliers.", type: "behavioral" },
      { label: "Guardian or trustee activity", evidence: "Bill-pay or ACH to a special needs attorney, trust company, or state ABLE plan administrator.", type: "life-event" },
      { label: "Public benefits coordination", evidence: "Deposits from SSI or disability benefit administrators alongside medical and care-related outflows.", type: "behavioral" },
    ],
    estimatedAudience: 3_200_000,
    penetration: 0.006,
  },
  {
    id: "financial-planning-subscription",
    name: "Financial Planning Subscription",
    category: "Wealth",
    icon: FileSpreadsheet,
    positioning: "Ongoing digital financial planning with goal tracking, tax-aware advice, and annual check-ins.",
    signals: [
      { label: "DIY planning tools", evidence: "Subscription payments to budgeting or planning apps, plus recurring transfers to multiple savings goals.", type: "behavioral" },
      { label: "Life transition complexity", evidence: "Cluster of life-event signals (marriage, home purchase, new child) within a 12-month window.", type: "life-event" },
      { label: "Advisory fee comparison", evidence: "Outbound ACH to a fee-only planner or robo-advisor, indicating willingness to pay for guidance.", type: "behavioral" },
    ],
    estimatedAudience: 10_000_000,
    penetration: 0.020,
  },

  // ===== LENDING =====
  {
    id: "mortgage",
    name: "Mortgage",
    category: "Lending",
    icon: Building2,
    positioning: "Purchase and refinance mortgages for first-time and move-up buyers.",
    signals: [
      { label: "Rent payments above local median", evidence: "Consistent ACH debits for rent, recurring P2P payments to 'landlord', or bill-pay to property management companies exceed local 75th percentile.", type: "behavioral" },
      { label: "Significant savings for down payment", evidence: "Consistent, increasing balance across savings accounts, coupled with incoming transfers from investment accounts or matured CDs, beyond regular income.", type: "behavioral" },
      { label: "Home-related expense surge", evidence: "Increased card spend at home improvement stores, furniture retailers, and moving services, immediately following a large outflow for a down payment or closing costs.", type: "life-event" },
    ],
    estimatedAudience: 27_400_000,
    penetration: 0.055,
  },
  {
    id: "heloc",
    name: "Home Equity Line of Credit",
    category: "Lending",
    icon: Home,
    positioning: "Flexible credit secured by home equity for renovations or large expenses.",
    signals: [
      { label: "Significant home improvement outlays", evidence: "Accumulation of large ticket card charges at building material retailers and ACH payments to general contractors exceeding $5,000 within 3 months.", type: "behavioral" },
      { label: "Recurring property tax payments", evidence: "Consistent annual or semi-annual ACH debits to municipal tax authorities or large bill-pay disbursements to county treasurers.", type: "behavioral" },
      { label: "Established property ownership", evidence: "Mortgage payments, property tax records, and utility bill-pays indicate continuous homeownership for over five years.", type: "life-event" },
      { label: "Home equity unlock potential", evidence: "Large inbound ACH from a different bank followed by series of high-value home improvement transactions via card and ACH.", type: "life-event" },
    ],
    estimatedAudience: 19_600_000,
    penetration: 0.039,
    defaultActive: true,
  },
  {
    id: "auto-loan",
    name: "Auto Loan",
    category: "Lending",
    icon: Car,
    positioning: "Financing for new or used vehicle purchase, with refi for existing loans.",
    signals: [
      { label: "Auto shopping behavior", evidence: "Card spend at multiple dealerships, with parallel ACH inquiries and insurance prepayments within 30 days.", type: "behavioral" },
      { label: "Outbound auto loan payoff", evidence: "Large outbound wire or ACH to a captive auto lender, with concurrent DMV payment.", type: "life-event" },
      { label: "New auto loan origination", evidence: "Large inbound ACH from a financial institution followed by regular outbound ACH payments to an auto lender.", type: "life-event" },
    ],
    estimatedAudience: 23_000_000,
    penetration: 0.046,
  },
  {
    id: "auto-refi",
    name: "Auto Refinance",
    category: "Lending",
    icon: RefreshCw,
    positioning: "Lower-rate refinance for customers carrying a high-APR auto loan elsewhere.",
    signals: [
      { label: "Outbound auto loan payments", evidence: "Consistent ACH or bill-pay outflows to captive auto lenders, or transfers to external accounts followed by loan payments.", type: "behavioral" },
      { label: "Increased disposable income", evidence: "Sustained increase in direct-deposit payroll or P2P inflows, with no corresponding increase in recurring bill-pay or card outflows.", type: "life-event" },
      { label: "Refinance research behavior", evidence: "Frequent card transactions or ACH payments to credit reporting agencies, or inquiries to 'loan comparison' services.", type: "behavioral" },
    ],
    estimatedAudience: 14_600_000,
    penetration: 0.029,
  },
  {
    id: "personal-loan",
    name: "Personal Loan",
    category: "Lending",
    icon: HandCoins,
    positioning: "Unsecured installment loans for consolidation or one-time expenses.",
    signals: [
      { label: "Third-party lender repayment", evidence: "ACH debits to known captive lenders, matched with bill-pay to non-bank lenders or external card paydowns for credit products.", type: "behavioral" },
      { label: "Emergency cash injection", evidence: "Inbound P2P transfers from multiple individuals or cash-out activity from diverse sources like 'VEN*CASH-OUT' followed by immediate bill payments.", type: "life-event" },
      { label: "Debt spiral risk", evidence: "Consistent high-utilization credit card balances paired with increasing ACH debits to collection agencies or frequent 'STRP*LOAN' type transactions.", type: "behavioral" },
    ],
    estimatedAudience: 17_800_000,
    penetration: 0.036,
  },
  {
    id: "small-business-loan",
    name: "Small Business Loan",
    category: "Lending",
    icon: Store,
    positioning: "Working capital and term loans for sole proprietors and small businesses.",
    signals: [
      { label: "Emerging microbusiness revenue", evidence: "Regular deposits from payment processors like Stripe/Square/Paypal into a personal account, alongside business-category card spend.", type: "behavioral" },
      { label: "Business supplier network", evidence: "Multiple distinct ACH payments to known business suppliers, combined with online bill-pays to professional services or software vendors.", type: "behavioral" },
      { label: "Dedicated business operations", evidence: "Consistent card spending at office supply stores or SaaS providers, coupled with ACH transfers to a separate business account or payroll service.", type: "behavioral" },
    ],
    estimatedAudience: 6_400_000,
    penetration: 0.013,
  },
  {
    id: "rv-boat-loan",
    name: "RV / Boat Loan",
    category: "Lending",
    icon: Ship,
    positioning: "Recreational vehicle and marine financing for customers buying or refinancing RVs, boats, and watercraft.",
    signals: [
      { label: "Recreational vehicle shopping", evidence: "Card spend at RV dealerships, boat brokers, or marine supply stores, often paired with insurance prepayments.", type: "behavioral" },
      { label: "Marina and storage payments", evidence: "Recurring ACH or card payments to marinas, boat storage facilities, or RV parks during the off-season.", type: "behavioral" },
      { label: "Large leisure purchase deposit", evidence: "Substantial deposit or down payment to a recreational vehicle or boat dealer via wire or ACH.", type: "life-event" },
    ],
    estimatedAudience: 3_600_000,
    penetration: 0.007,
  },
  {
    id: "motorcycle-loan",
    name: "Motorcycle Loan",
    category: "Lending",
    icon: Bike,
    positioning: "Financing for new or used motorcycle and powersport purchases.",
    signals: [
      { label: "Powersport dealer engagement", evidence: "Card or ACH payments to motorcycle dealerships, powersport retailers, or accessory shops.", type: "behavioral" },
      { label: "Insurance quote trigger", evidence: "ACH or card payment to a motorcycle insurer shortly after a dealer deposit.", type: "life-event" },
      { label: "Competitive lender payoff", evidence: "Outbound ACH to a captive powersport lender, indicating an existing loan elsewhere.", type: "behavioral" },
    ],
    estimatedAudience: 2_800_000,
    penetration: 0.006,
  },
  {
    id: "construction-loan",
    name: "Construction Loan",
    category: "Lending",
    icon: Hammer,
    positioning: "Short-term financing for ground-up home construction or major renovation projects.",
    signals: [
      { label: "Land or lot acquisition", evidence: "Large outbound wire or ACH to a land seller, title company, or municipality for a buildable lot.", type: "life-event" },
      { label: "Builder draw schedule", evidence: "Recurring large-value ACH or wire payments to a general contractor or construction firm.", type: "behavioral" },
      { label: "Permit and architectural fees", evidence: "Payments to architects, structural engineers, or city permitting offices via ACH or bill-pay.", type: "life-event" },
    ],
    estimatedAudience: 1_400_000,
    penetration: 0.003,
  },
  {
    id: "lease-buyout-loan",
    name: "Lease Buyout Loan",
    category: "Lending",
    icon: Key,
    positioning: "Financing for customers buying out an existing auto, equipment, or real estate lease.",
    signals: [
      { label: "Lease-end residual payment", evidence: "Large outbound ACH or wire to a leasing company labeled 'lease buyout' or 'residual'.", type: "life-event" },
      { label: "Ongoing lease payments", evidence: "Consistent monthly ACH debits to a captive leasing company for 24+ months.", type: "behavioral" },
      { label: "Excess mileage or wear charges", evidence: "End-of-lease fees paid to the lessor, signaling the customer is closing the lease.", type: "life-event" },
    ],
    estimatedAudience: 4_200_000,
    penetration: 0.008,
  },

  // ===== DEPOSITS =====
  {
    id: "starter-checking",
    name: "Starter Checking",
    category: "Deposits",
    icon: Wallet,
    positioning: "No-overdraft checking for students, teens, and customers new to banking.",
    signals: [
      { label: "Educational Institution Inflows", evidence: "Consistent ACH credits from universities or vocational schools alongside P2P from guardian counterparties.", type: "life-event" },
      { label: "Emerging Financial Footprint", evidence: "Limited credit bureau data, with early-stage card and ACH activity showing reliance on cash alternatives and P2P payments.", type: "life-event" },
      { label: "Prepaid Card Ecosystem Engagement", evidence: "Regular bill-pay transfers to known prepaid card providers (e.g., \"CHIME\", \"GREEN DOT\") and P2P loads to digital wallets.", type: "behavioral" },
    ],
    estimatedAudience: 38_000_000,
    penetration: 0.076,
  },
  {
    id: "everyday-checking",
    name: "Everyday Checking",
    category: "Deposits",
    icon: Banknote,
    positioning: "Primary checking with direct deposit, bill pay, and broad ATM access.",
    signals: [
      { label: "Cross-rail payroll anchoring", evidence: "Consistent W-2 payroll inflow via ACH, coupled with minimal P2P cash-out or external account transfers.", type: "behavioral" },
      { label: "Bill-pay hub establishment", evidence: "Multiple bill-pay transactions to utilities, rent, and captive auto lenders, indicating primary bill management.", type: "behavioral" },
      { label: "Joint financial anchoring", evidence: "Shared address update alongside new joint account opening and recurring inter-account transfers to other known accounts.", type: "life-event" },
    ],
    estimatedAudience: 124_000_000,
    penetration: 0.248,
    defaultActive: true,
  },
  {
    id: "relationship-checking",
    name: "Relationship Checking",
    category: "Deposits",
    icon: HeartHandshake,
    positioning: "Premium checking with fee waivers and rate bonuses for multi-product households.",
    signals: [
      { label: "Multi-product household indicator", evidence: "Customer shows payments to captive auto lenders, mortgage servicers, and external credit cards across ACH and bill pay.", type: "behavioral" },
      { label: "High liquidity across rails", evidence: "Consistent high balances in checking, plus inbound transfers from brokerages and outbound bill pays to external investment platforms.", type: "behavioral" },
      { label: "Wealth management engagement", evidence: "Regular ACH transfers to/from known investment platforms and advisory firms, alongside bill pay for estate counsel fees.", type: "behavioral" },
    ],
    estimatedAudience: 19_000_000,
    penetration: 0.038,
  },
  {
    id: "core-savings",
    name: "Core Savings",
    category: "Deposits",
    icon: PiggyBank,
    positioning: "Companion savings account with automatic-transfer tools for everyday savers.",
    signals: [
      { label: "Consistent micro-savings behavior", evidence: "Daily small-dollar transfers from checking to savings, augmented by debit card round-up programs", type: "behavioral" },
      { label: "Dedicated savings goal", evidence: "Recurring transfers to a savings account, often with a unique memo like 'down payment' or 'tuition fund'", type: "behavioral" },
      { label: "Significant tax refund received", evidence: "Large annual inflow from tax authorities (IRS, state DOR) via ACH or direct deposit, frequently >$1,500", type: "life-event" },
    ],
    estimatedAudience: 68_000_000,
    penetration: 0.136,
    defaultActive: true,
  },
  {
    id: "high-yield-savings",
    name: "High-Yield Savings",
    category: "Deposits",
    icon: TrendingUp,
    positioning: "Premium savings yield for customers with idle checking balances.",
    signals: [
      { label: "High Checking Balance, Low-Yield", evidence: "Consistent checking account balances exceeding $25,000 for 90+ days, with minimal linked savings account activity.", type: "behavioral" },
      { label: "Outbound Yield-Seeking Transfers", evidence: "Recurring ACH transfers to known investment platforms, brokerage accounts, or high-yield fintech savings products.", type: "behavioral" },
      { label: "Competitive Product Funding", evidence: "Inbound ACH linked to a prominent challenger bank or investment product, followed by large outbound transfers from checking.", type: "life-event" },
    ],
    estimatedAudience: 37_200_000,
    penetration: 0.074,
    defaultActive: true,
  },
  {
    id: "certificate-of-deposit",
    name: "Certificate of Deposit",
    category: "Deposits",
    icon: Landmark,
    positioning: "Fixed-term, guaranteed-rate deposits for customers locking in yield.",
    signals: [
      { label: "External CD Matures", evidence: "Large inbound ACH or wire from another financial institution, paired with no matching outbound CD purchase.", type: "life-event" },
      { label: "Senior Wealth Builder", evidence: "Consistent inbound Social Security or pension ACH, coupled with recurring bill-pay to retirement community and medical providers.", type: "behavioral" },
      { label: "Fixed Income Seeker", evidence: "Frequent outbound transfers to online brokerage for bond/Treasury ETFs, or direct ACH to government treasury programs.", type: "behavioral" },
    ],
    estimatedAudience: 22_000_000,
    penetration: 0.044,
  },
  {
    id: "money-market-account",
    name: "Money Market Account",
    category: "Deposits",
    icon: BarChart3,
    positioning: "Liquid savings with check-writing access and tiered rates for customers parking larger cash reserves.",
    signals: [
      { label: "Large idle checking balance", evidence: "Consistent checking balances above $50,000 with limited outbound investment or spending activity.", type: "behavioral" },
      { label: "Competitive money market migration", evidence: "Inbound ACH from a brokerage sweep or external money market account.", type: "life-event" },
      { label: "Liquidity preference", evidence: "Recurring large transfers between checking and savings, but no long-term CD or investment purchases.", type: "behavioral" },
    ],
    estimatedAudience: 22_000_000,
    penetration: 0.044,
  },
  {
    id: "teen-youth-savings",
    name: "Teen / Youth Savings",
    category: "Deposits",
    icon: Smile,
    positioning: "Guardian-managed savings and debit tools to help teens build healthy money habits early.",
    signals: [
      { label: "Guardian-linked minor activity", evidence: "Recurring small ACH or P2P inflows from a parent, plus age-appropriate merchant spend at gaming or retail merchants.", type: "behavioral" },
      { label: "First job income", evidence: "New small-dollar payroll ACH deposits from an employer, often below typical adult thresholds.", type: "life-event" },
      { label: "Youth account migration signal", evidence: "Inbound transfers from external youth banking apps or prepaid teen cards.", type: "behavioral" },
    ],
    estimatedAudience: 14_000_000,
    penetration: 0.028,
  },
  {
    id: "holiday-club-savings",
    name: "Holiday Club Savings",
    category: "Deposits",
    icon: Gift,
    positioning: "Short-term goal account that auto-saves for seasonal spending and disburses ahead of the holidays.",
    signals: [
      { label: "Seasonal spend spike", evidence: "Significant Q4 card spend at toy stores, electronics retailers, and online gift merchants.", type: "behavioral" },
      { label: "Recurring small goal transfers", evidence: "Weekly or biweekly automatic transfers from checking into a labeled savings bucket.", type: "behavioral" },
      { label: "Post-holiday debt consolidation", evidence: "Large January ACH or bill-pay payments to credit cards after elevated December spend.", type: "life-event" },
    ],
    estimatedAudience: 9_600_000,
    penetration: 0.019,
  },

  // ===== CARDS =====
  {
    id: "category-cashback-card",
    name: "Category Cash Back Card",
    category: "Cards",
    icon: Tag,
    positioning: "Cash-back card with a customer-chosen bonus category for everyday spend.",
    signals: [
      { label: "Heavy discretionary category spend", evidence: "Consistent high spend on selected reward categories like dining, entertainment, or travel, visible across card and P2P rails.", type: "behavioral" },
      { label: "Competitor card funding", evidence: "Regular bill-pay or ACH transfers to other card issuers, indicating external card payments and usage.", type: "behavioral" },
      { label: "Growing card engagement", evidence: "Increasing monthly transaction volume and value on a single card, with new linked bill-pay or P2P activity.", type: "behavioral" },
    ],
    estimatedAudience: 48_000_000,
    penetration: 0.096,
    defaultActive: true,
  },
  {
    id: "flat-cashback-card",
    name: "Flat-Rate Cash Back Card",
    category: "Cards",
    icon: CreditCard,
    positioning: "Simple unlimited cash back on every purchase, no category tracking.",
    signals: [
      { label: "Diversified everyday spend profile", evidence: "Consistent multi-category general-purpose card spend across 50+ merchants, supplemented by recurring bill-pay and P2P for services.", type: "behavioral" },
      { label: "High share of wallet, everyday spend", evidence: "Large proportion of essential spending (groceries, fuel, dining) consistently captured on card, minimal external card paydown ACH.", type: "behavioral" },
      { label: "Simplified rewards preference", evidence: "Ignored category-activation prompts on card, consistent P2P/ACH for structured bills, suggests preference for flat-rate rewards.", type: "behavioral" },
      { label: "Cross-rail discretionary spending", evidence: "Balanced discretionary spending across card (e.g., entertainment, apparel) and P2P (e.g., VEN* for social activities or shared expenses).", type: "behavioral" },
    ],
    estimatedAudience: 42_000_000,
    penetration: 0.084,
  },
  {
    id: "travel-card",
    name: "Travel Rewards Card",
    category: "Cards",
    icon: Plane,
    positioning: "Mid-tier travel card with points, no foreign transaction fees, and travel protections.",
    signals: [
      { label: "Travel booked across providers", evidence: "Card spend and ACH debits to multiple airlines, online travel agencies, and hotel groups within 90 days, including 'ACME Travel' and 'Expedia'.", type: "behavioral" },
      { label: "Foreign transaction history", evidence: "Card foreign currency transactions, plus international wire transfers or P2P to foreign persons, within the last six months.", type: "behavioral" },
      { label: "Pre-travel spending surge", evidence: "Elevated card spend at specialty apparel, luggage, and duty-free merchants, correlated with upcoming travel-related debits and P2P payments.", type: "behavioral" },
    ],
    estimatedAudience: 24_200_000,
    penetration: 0.048,
  },
  {
    id: "premium-travel-card",
    name: "Premium Travel Card",
    category: "Cards",
    icon: Gem,
    positioning: "Premium travel card with lounge access, travel credits, and elevated earn rates.",
    signals: [
      { label: "Frequent business traveler", evidence: "Regular T&E transactions across corporate cards, personal cards and expense reimbursements for lodging and airfare.", type: "behavioral" },
      { label: "Luxury travel indulgence", evidence: "Consistent personal card spend at premium airlines, resorts, and fine dining establishments, often exceeding corporate travel budgets.", type: "behavioral" },
      { label: "Broad travel ecosystem spend", evidence: "Frequent transactions for ride-sharing, luggage, adaptive clothing, and travel medical, indicating extensive and diverse travel needs.", type: "behavioral" },
    ],
    estimatedAudience: 9_600_000,
    penetration: 0.019,
  },
  {
    id: "ultra-premium-travel-card",
    name: "Ultra-Premium Travel Card",
    category: "Cards",
    icon: Crown,
    positioning: "Top-tier travel card with concierge, hotel elite status, and global lounge network.",
    signals: [
      { label: "Premium travel ecosystem engagement", evidence: "Consistent spend at luxury hotels and airlines, often with global lounge network, across card and bill-pay rails.", type: "behavioral" },
      { label: "Affluent global traveler profile", evidence: "Frequent, high-value foreign currency transactions and cross-border payments for travel services via cards and wires.", type: "behavioral" },
      { label: "Concierge service dependency", evidence: "Repeated card transactions with known concierge merchant types, often followed by high-end travel or experience purchases.", type: "behavioral" },
    ],
    estimatedAudience: 2_200_000,
    penetration: 0.004,
  },
  {
    id: "balance-transfer-card",
    name: "Low-Rate Balance Transfer Card",
    category: "Cards",
    icon: RefreshCw,
    positioning: "Long 0% intro APR for customers carrying high-interest balances elsewhere.",
    signals: [
      { label: "External Card Debt Servicing", evidence: "Consistent bill-pay to multiple external card issuers, identified via semantic merchant resolution from cryptic descriptors.", type: "behavioral" },
      { label: "High-Cost Debt Indicators", evidence: "Recurring ACH transfers and bill-pays to non-bank lenders and credit card companies, showing high estimated interest payments.", type: "behavioral" },
      { label: "Opportunity for Wallet Share", evidence: "Significant external credit card payments observed across bill-pay and P2P, indicating potential to consolidate balances.", type: "behavioral" },
    ],
    estimatedAudience: 13_400_000,
    penetration: 0.027,
  },
  {
    id: "cobrand-card",
    name: "Co-Brand Partner Card",
    category: "Cards",
    icon: Globe,
    positioning: "Affinity card with branded rewards for loyal customers of a specific airline, cruise, or retailer.",
    signals: [
      { label: "Deep brand loyalty", evidence: "Majority of consumer spend at a single merchant and related ecosystem via card, with cross-rail recognition of brand payments.", type: "behavioral" },
      { label: "Competitive card wallet share", evidence: "Inbound ACH transfers from other financial institutions for credit card payments, indicating competitor usage within the same spend category.", type: "behavioral" },
      { label: "Brand-specific travel investment", evidence: "Card and bill-pay transactions show consistent booking and payment for a single airline, cruise line, or related travel provider.", type: "behavioral" },
    ],
    estimatedAudience: 6_800_000,
    penetration: 0.014,
  },
  {
    id: "secured-credit-card",
    name: "Secured Credit Card",
    category: "Cards",
    icon: Lock,
    positioning: "Credit-building card backed by a refundable security deposit for customers establishing or rebuilding credit.",
    signals: [
      { label: "Thin or rebuilding credit profile", evidence: "Limited traditional credit bureau data, reliance on debit, P2P, and prepaid products.", type: "behavioral" },
      { label: "Credit-builder product usage", evidence: "Recurring payments to credit-builder loan providers or secured card competitors.", type: "behavioral" },
      { label: "Recent denial or thin-file signal", evidence: "Hard inquiry followed by no new tradeline, plus continued use of cash alternatives.", type: "life-event" },
    ],
    estimatedAudience: 18_000_000,
    penetration: 0.036,
  },
  {
    id: "student-credit-card",
    name: "Student Credit Card",
    category: "Cards",
    icon: Backpack,
    positioning: "Starter card for college students with simple rewards and no annual fee.",
    signals: [
      { label: "College-affiliated spend", evidence: "Card and ACH activity at campus bookstores, meal plans, and university-related merchants.", type: "behavioral" },
      { label: "Student income pattern", evidence: "Small, irregular payroll deposits from campus or part-time employers.", type: "life-event" },
      { label: "First credit product search", evidence: "Inquiries or applications to known student-card issuers, often with a campus address.", type: "behavioral" },
    ],
    estimatedAudience: 8_400_000,
    penetration: 0.017,
  },
  {
    id: "business-credit-card",
    name: "Business Credit Card",
    category: "Cards",
    icon: Building,
    positioning: "Expense management card for small-business owners with employee cards and category rewards.",
    signals: [
      { label: "Business spend commingled", evidence: "Mixed business and personal card spend at office supply, SaaS, and trade-show merchants.", type: "behavioral" },
      { label: "Payment processor revenue", evidence: "Regular deposits from Stripe, Square, or PayPal into a personal account.", type: "behavioral" },
      { label: "Business supplier payments", evidence: "ACH or bill-pay to vendors, contractors, and professional services from a personal account.", type: "behavioral" },
    ],
    estimatedAudience: 12_000_000,
    penetration: 0.024,
  },

  // ===== INSURANCE =====
  {
    id: "life-insurance",
    name: "Term Life Insurance",
    category: "Insurance",
    icon: Shield,
    positioning: "Income protection for new families and primary earners.",
    signals: [
      { label: "New dependent expenses", evidence: "Increased spend at pediatric offices (card), daycare centers (ACH), and children's apparel (card) following birth-event cluster.", type: "life-event" },
      { label: "Increased housing costs", evidence: "New recurring ACH payments to a mortgage servicer or significantly larger rent payments (bill-pay) started recently.", type: "life-event" },
      { label: "Consolidated income dependency", evidence: "One primary income source (ACH payroll) increasingly covers household expenses and transfers to other accounts (P2P, bill-pay).", type: "behavioral" },
    ],
    estimatedAudience: 15_000_000,
    penetration: 0.030,
  },
  {
    id: "permanent-life",
    name: "Permanent Life Insurance",
    category: "Insurance",
    icon: Shield,
    positioning: "Lifetime coverage with cash-value accumulation for estate and legacy planning.",
    signals: [
      { label: "Substantial legal & accounting spend", evidence: "Consistent legal and accounting firm payments via ACH, wire, and bill pay, especially for trust and estate services.", type: "behavioral" },
      { label: "Diversified asset management", evidence: "Outflows to multiple brokerages, private equity firms or alternative investment vehicles via ACH and wire transfers.", type: "behavioral" },
      { label: "Intergenerational wealth transfer", evidence: "Regular P2P and wire transfers to multiple family members, often near annual gift tax exclusion limits.", type: "behavioral" },
    ],
    estimatedAudience: 4_400_000,
    penetration: 0.009,
  },
  {
    id: "ltc-insurance",
    name: "Long-Term Care Insurance",
    category: "Insurance",
    icon: Umbrella,
    positioning: "Coverage for in-home and facility-based long-term care needs.",
    signals: [
      { label: "Emerging Eldercare Costs", evidence: "Increased bill-pay to assisted-living facilities, recurring ACH to home healthcare agencies, and P2P payments for care services.", type: "behavioral" },
      { label: "Family Financial Reorganization", evidence: "New wires/ACH from family members, trust disbursements, or sudden large transfers to estate-counsel IOLTA accounts.", type: "life-event" },
      { label: "Complex Health Spend Uptick", evidence: "Rising card spend at specialized medical practices combined with increasing P2P to nursing support or medical supply vendors.", type: "behavioral" },
    ],
    estimatedAudience: 8_200_000,
    penetration: 0.016,
  },
  {
    id: "annuity",
    name: "Annuity",
    category: "Insurance",
    icon: Landmark,
    positioning: "Guaranteed income and tax-deferred growth for pre-retirees and retirees.",
    signals: [
      { label: "Pension liquidation and rollover", evidence: "Large inbound ACH from known pension administrator, followed by outbound wire to brokerage or mutual fund 'for deposit only'", type: "life-event" },
      { label: "Diversified retirement funding", evidence: "Regular inbound transfers from multiple sources including employment income, investment dividends, and external annuity payments across ACH/wire.", type: "behavioral" },
      { label: "Approaching retirement age", evidence: "Consistent payroll deposits declining in frequency or amount, paired with increased medical spending (copays, prescriptions) via card or ACH.", type: "life-event" },
    ],
    estimatedAudience: 7_200_000,
    penetration: 0.014,
  },
  {
    id: "pet-insurance",
    name: "Pet Insurance",
    category: "Insurance",
    icon: PawPrint,
    positioning: "Accident and illness coverage for dogs, cats, and other household pets.",
    signals: [
      { label: "Veterinary spend cluster", evidence: "Recurring card or ACH payments to veterinary clinics, pet hospitals, and prescription pet pharmacies.", type: "behavioral" },
      { label: "New pet acquisition", evidence: "Large one-time spend at breeders, pet stores, or animal shelters, followed by pet supply purchases.", type: "life-event" },
      { label: "Competitor policy payment", evidence: "Recurring ACH or card debits to a known pet insurance carrier.", type: "behavioral" },
    ],
    estimatedAudience: 11_000_000,
    penetration: 0.022,
  },
  {
    id: "identity-theft-protection",
    name: "Identity Theft Protection",
    category: "Insurance",
    icon: Fingerprint,
    positioning: "Credit monitoring, dark-web alerts, and identity restoration for security-conscious households.",
    signals: [
      { label: "Security-adjacent subscriptions", evidence: "Recurring payments to VPN, password-manager, or antivirus providers.", type: "behavioral" },
      { label: "Recent fraud incident", evidence: "Disputed transactions, replacement card shipments, or credit freeze fees.", type: "life-event" },
      { label: "Credit monitoring competitor", evidence: "Outbound ACH or card payments to a credit bureau or identity-protection service.", type: "behavioral" },
    ],
    estimatedAudience: 16_000_000,
    penetration: 0.032,
  },
  {
    id: "disability-insurance",
    name: "Disability Insurance",
    category: "Insurance",
    icon: HeartPulse,
    positioning: "Income-replacement coverage for primary earners during illness or injury.",
    signals: [
      { label: "Single-income dependency", evidence: "One dominant payroll ACH covers most household expenses and transfers to other accounts.", type: "behavioral" },
      { label: "New family responsibility", evidence: "Birth-event cluster followed by increased housing and dependent-care expenses.", type: "life-event" },
      { label: "Professional liability exposure", evidence: "Payments to professional associations or licensing bodies for high-income occupations.", type: "behavioral" },
    ],
    estimatedAudience: 13_400_000,
    penetration: 0.027,
  },
  {
    id: "auto-insurance",
    name: "Auto Insurance",
    category: "Insurance",
    icon: Car,
    positioning: "Bundled auto coverage for new vehicle purchases, lease requirements, and policy renewals.",
    signals: [
      { label: "New vehicle purchase", evidence: "Large ACH or wire to a dealership, followed by DMV/title fees and a new auto loan.", type: "life-event" },
      { label: "Competitor premium payments", evidence: "Recurring ACH or card payments to a known auto insurer.", type: "behavioral" },
      { label: "Lease or loan requirement", evidence: "New captive auto loan or lease payment, typically requiring full-coverage insurance.", type: "life-event" },
    ],
    estimatedAudience: 26_000_000,
    penetration: 0.052,
  },

  // ===== LIFE-EVENT FLOWS =====
  {
    id: "wedding-loan",
    name: "Wedding Personal Loan",
    category: "Lending",
    icon: Heart,
    positioning: "Fixed-rate financing for engagement, wedding, and honeymoon expenses.",
    signals: [
      { label: "High-value jewelry purchase", evidence: "Card spend over $2k at fine-jewelry MCCs, often followed by credit card paydown.", type: "life-event" },
      { label: "Recurring wedding vendor payments", evidence: "Clustered card, Bill-Pay, or ACH outflows to multiple wedding-related categories like venues, caterers, or event planners.", type: "life-event" },
      { label: "Honeymoon travel bookings", evidence: "Clusters of card or online travel agency (OTA) spend for flights, lodging, and experiences in common honeymoon destinations.", type: "life-event" },
    ],
    estimatedAudience: 4_800_000,
    penetration: 0.010,
  },
  {
    id: "solo-restart-checking",
    name: "Solo Restart Checking",
    category: "Deposits",
    icon: RefreshCw,
    positioning: "Fresh standalone checking with budgeting tools for customers re-establishing solo finances.",
    signals: [
      { label: "Emerging solo bill-pay pattern", evidence: "Formerly joint bill-payees (e.g., utility, rent) now exclusively single-payer via ACH or bill-pay, often with new account numbers.", type: "life-event" },
      { label: "Family law/legal services engagement", evidence: "Multiple disaggregated payments to legal services firms, ", type: "life-event" },
      { label: "New solo rent or mortgage payments", evidence: "First-time or new recurring rent/mortgage payments via ACH or bill-pay, linked to a single individual, following a period of joint housing payments.", type: "life-event" },
    ],
    estimatedAudience: 6_200_000,
    penetration: 0.012,
  },
  {
    id: "inherited-ira",
    name: "Inherited IRA",
    category: "Wealth",
    icon: Gift,
    positioning: "Beneficiary IRA structure preserving tax treatment for inherited retirement assets.",
    signals: [
      { label: "Estate settlement inflow", evidence: "Large inbound ACH or wire from an estate counsel IOLTA or trust disbursement, potentially preceded by multiple smaller legal/probate fees.", type: "life-event" },
      { label: "Recurring wealth transfer", evidence: "Consistent outbound ACHs or bill-pays to a financial advisor or brokerage, following a large estate inflow event.", type: "behavioral" },
      { label: "Beneficiary data update", evidence: "Digital engagement with beneficiary forms or account titling changes observed across multiple financial platforms or bank products.", type: "behavioral" },
    ],
    estimatedAudience: 3_800_000,
    penetration: 0.008,
  },
  {
    id: "second-home-mortgage",
    name: "Second Home Mortgage",
    category: "Lending",
    icon: Home,
    positioning: "Purchase financing for vacation or seasonal-use second properties.",
    signals: [
      { label: "Vacation area lodging and dining", evidence: "Card spend at resorts and restaurants in a distinct geographic region cross-referenced with ACH to local utilities or property management.", type: "behavioral" },
      { label: "Second property tax payments", evidence: "Multiple large-value ACH or bill-pay transactions to distinct county tax assessors with different geographic markers.", type: "behavioral" },
      { label: "Remote property maintenance payments", evidence: "Recurring card or bill-pay transactions to landscaping, pool, or home repair services in a non-primary residential area.", type: "behavioral" },
      { label: "Out-of-area contractor payments", evidence: "Large-value ACH or wire transfers to contractors and builders located outside the primary residence's metropolitan area.", type: "life-event" },
    ],
    estimatedAudience: 2_800_000,
    penetration: 0.006,
  },
  {
    id: "student-loan-refi",
    name: "Student Loan Refinance",
    category: "Lending",
    icon: GraduationCap,
    positioning: "Lower-rate refinance for borrowers carrying federal or private student loans.",
    signals: [
      { label: "Student loan consolidation inquiry", evidence: "Multiple recent hard credit inquiries from student lenders followed by a new recurring ACH to a consolidated servicer.", type: "life-event" },
      { label: "Career launch income surge", evidence: "Significant and sustained increase in payroll deposits, potentially combined with relocation expenses via card and bill pay.", type: "life-event" },
      { label: "Student loan wallet share shift", evidence: "Decreased or terminated ACH payments to original student loan servicers, replaced by new payments to a competing financial institution.", type: "behavioral" },
    ],
    estimatedAudience: 11_600_000,
    penetration: 0.023,
  },
  {
    id: "hsa",
    name: "Health Savings Account",
    category: "Deposits",
    icon: Heart,
    positioning: "Triple-tax-advantaged savings for customers on high-deductible health plans.",
    signals: [
      { label: "HSA Contribution Trend", evidence: "Regular inbound ACH transfers from employer payroll or personal funding to a health savings administrator; may see 'HSA' or 'HEALTH SA' in descriptor.", type: "behavioral" },
      { label: "High Deductible Plan Medical Outflows", evidence: "Consistent, out-of-pocket card or ACH payments to medical providers ('HOSPITAL', 'PEDIATRIC', 'RX') before typical insurance coverage limits are met.", type: "behavioral" },
      { label: "Catch-Up Contribution Eligibility", evidence: "Periodic, larger-than-normal ACH or P2P contributions to an HSA administrator, often occurring around age 55, indicating catch-up contributions.", type: "life-event" },
    ],
    estimatedAudience: 18_800_000,
    penetration: 0.038,
  },
  {
    id: "donor-advised-fund",
    name: "Donor-Advised Fund",
    category: "Wealth",
    icon: HeartHandshake,
    positioning: "Tax-efficient charitable giving vehicle with invested balances for long-term impact.",
    signals: [
      { label: "Significant annual giving", evidence: "Large Q4 bill-pay and ACH outflows to diverse charitable organizations, exceeding prior yearly averages by 2x.", type: "behavioral" },
      { label: "Diversified giving portfolio", evidence: "Consistent P2P, bill-pay, and card donations to multiple distinct non-profit categories (e.g., education, arts, social services).", type: "behavioral" },
      { label: "New philanthropic intent", evidence: "Initial large ACH or wire transfer to a DAF sponsor or community foundation, followed by segmented outflows to charities.", type: "life-event" },
    ],
    estimatedAudience: 4_200_000,
    penetration: 0.008,
  },
  {
    id: "personal-line-of-credit",
    name: "Personal Line of Credit",
    category: "Lending",
    icon: HandCoins,
    positioning: "Revolving unsecured line for flexible access during income gaps or large planned outflows.",
    signals: [
      { label: "Income Interruption Or Reduction", evidence: "Observed absence of typical payroll deposits or recurring income, or a sustained decrease in deposit amounts across ACH and P2P rails.", type: "life-event" },
      { label: "Emergency Savings Depletion/Creation", evidence: "Rapid, multi-rail cash-out movements to external accounts or P2P; or new, consistent inflows from an external investment or savings provider.", type: "life-event" },
      { label: "Sustained High Credit Utilization", evidence: "Consistent external credit card payments via bill-pay show increasing principal paydowns, indicating rising revolving debt across card rails.", type: "behavioral" },
      { label: "Increased Reliance On Non-Bank Financial Services", evidence: "Recurring outbound transfers to alternative lenders or 'pay-over-time' services, indicating use of external credit providers.", type: "behavioral" },
    ],
    estimatedAudience: 13_000_000,
    penetration: 0.026,
  },
  {
    id: "global-account",
    name: "Multi-Currency Global Account",
    category: "Deposits",
    icon: Globe,
    positioning: "Cross-border account with multi-currency holdings and reduced FX wire fees.",
    signals: [
      { label: "Foreign payroll income", evidence: "Recurring ACH or swift credits from foreign employer, with 'PAYROLL' or 'SALARY' in descriptor and non-USD original currency.", type: "life-event" },
      { label: "Multi-currency lifestyle indicator", evidence: "Sustained card spend in non-USD across multiple currencies, combined with P2P to international recipients.", type: "behavioral" },
      { label: "Frequent international transfers", evidence: "Recurring outbound or inbound wires/ACH to/from foreign counterparties, including 'SWIFT' or 'IBAN' references.", type: "behavioral" },
    ],
    estimatedAudience: 3_400_000,
    penetration: 0.007,
  },
  {
    id: "homeowners-insurance",
    name: "Homeowners Insurance",
    category: "Insurance",
    icon: Shield,
    positioning: "Bundled property and liability coverage for primary-residence homeowners.",
    signals: [
      { label: "Recent Home Purchase Mortgage", evidence: "New mortgage disbursements and principal payments via ACH and wire to a known lender.", type: "life-event" },
      { label: "Home Improvement Project Concluding", evidence: "Clustering of final large-dollar ACH payments to contractors and building material suppliers.", type: "life-event" },
      { label: "No Recurring Home Insurance", evidence: "Absence of recurring bill-pay or ACH payments to property & casualty insurers, despite property ownership.", type: "behavioral" },
    ],
    estimatedAudience: 9_800_000,
    penetration: 0.020,
  },
  {
    id: "umbrella-insurance",
    name: "Umbrella Insurance",
    category: "Insurance",
    icon: Umbrella,
    positioning: "Excess-liability coverage for households with material assets or higher exposure.",
    signals: [
      { label: "Multiple property tax footprint", evidence: "Recurring property tax payments via ACH/BillPay to multiple distinct county/municipality entities indicate ownership of multiple properties.", type: "behavioral" },
      { label: "Increased auto insurance premium", evidence: "Significant increase in recurring auto insurance payments (card or ACH) following a new driver addition or vehicle purchase event.", type: "life-event" },
      { label: "High-value asset transfers", evidence: "Large outbound wire transfers or ACH payments to known luxury good merchants or investment accounts, alongside inbound proceeds from asset sales.", type: "behavioral" },
    ],
    estimatedAudience: 6_400_000,
    penetration: 0.013,
  },
  {
    id: "move-financing",
    name: "Moving & Relocation Loan",
    category: "Lending",
    icon: Truck,
    positioning: "Short-term unsecured financing for moving costs, deposits, and relocation gaps.",
    signals: [
      { label: "Moving services & deposits payments", evidence: "Clustered card spend at movers, container services, and rental agencies, plus ACH/wire for security deposits and first month's rent.", type: "life-event" },
      { label: "Out-of-state utility & rent payments", evidence: "Concurrent bill-pay enrollment and recurring payments to utility providers and landlords in a new, distant geography.", type: "life-event" },
      { label: "New local-employer payroll deposit", evidence: "New recurring ACH payroll credits from an employer geographically distant from prior employer's location.", type: "life-event" },
    ],
    estimatedAudience: 5_200_000,
    penetration: 0.010,
  },
];

export function getProductFlow(id: string): ProductFlow | undefined {
  return PRODUCT_FLOWS.find((p) => p.id === id);
}
