import {
  GraduationCap,
  Home,
  Briefcase,
  Car,
  Building2,
  Building,
  PiggyBank,
  Plane,
  Store,
  HandCoins,
  Shield,
  Wallet,
  Banknote,
  Landmark,
  CreditCard,
  Receipt,
  TrendingUp,
  Wrench,
  LineChart,
  Bot,
  UserCheck,
  Crown,
  FileSpreadsheet,
  HeartHandshake,
  Umbrella,
  RefreshCw,
  Tag,
  Gem,
  Leaf,
  Scale,
  Globe,
  Heart,
  Truck,
  Gift,
  Ship,
  Bike,
  Hammer,
  Key,
  BarChart3,
  Smile,
  Lock,
  Backpack,
  PawPrint,
  Fingerprint,
  HeartPulse,
  Accessibility,
  Fuel,
  Users,
  HardHat,
  type LucideIcon,
} from "lucide-react";

export type FlowCategory =
  | "Lending"
  | "Wealth"
  | "Deposits"
  | "Cards"
  | "Insurance";

export type SignalType = "life-event" | "behavioral";

export interface FlowSignal {
  label: string;
  evidence: string;
  type: SignalType;
}

export interface ProductFlow {
  id: string;
  name: string;
  category: FlowCategory;
  icon: LucideIcon;
  positioning: string;
  signals: FlowSignal[];
  estimatedAudience: number; // out of ~250M
  penetration: number; // 0-1, share of base eligible
  defaultActive?: boolean;
}

export const PRODUCT_FLOWS: ProductFlow[] = [
  // ===== WEALTH =====
  {
    id: "529-plan",
    name: "529 College Savings Plan",
    category: "Wealth",
    icon: GraduationCap,
    positioning: "Tax-advantaged education savings for families with young or college-bound children.",
    signals: [
      { label: "New baby in the household", evidence: "Clustered spend at baby supply retailers, pediatric specialist copays (card), and daycare tuition (bank transfer) after a baby arrives.", type: "life-event" },
      { label: "Has a child heading to college", evidence: "Tuition payments to academic institutions (bank transfers or online bill payments), standardized test fees (card), and out-of-town travel to university towns.", type: "life-event" },
      { label: "Paying for education outside tuition", evidence: "Card and bank payments to tutoring services, test prep, enrichment programs and school fees through the academic year.", type: "behavioral" },
    ],
    estimatedAudience: 28_400_000,
    penetration: 0.057,
    defaultActive: true,
  },
  {
    id: "self-directed-brokerage",
    name: "Self-Directed Brokerage",
    category: "Wealth",
    icon: LineChart,
    positioning: "Commission-free online trading for customers who want to manage their own portfolio.",
    signals: [
      { label: "Investing at another firm", evidence: "Regular bank transfers or online bill payment to self-directed investment platforms beyond bank's offerings.", type: "behavioral" },
      { label: "Buys crypto on several exchanges", evidence: "Card or outgoing bank transfers to multiple cryptocurrency exchanges, including 'VEN*Crypto' or 'SQC*Coinbase'.", type: "behavioral" },
      { label: "Researching investments while holding cash", evidence: "Sustained high checking balances coupled with subscription payments to investment research services or financial news.", type: "behavioral" },
    ],
    estimatedAudience: 44_000_000,
    penetration: 0.088,
    defaultActive: true,
  },
  {
    id: "robo-portfolio",
    name: "Robo / Guided Portfolio",
    category: "Wealth",
    icon: Bot,
    positioning: "Algorithm-built diversified portfolio for hands-off investors at low cost.",
    signals: [
      { label: "New investor putting money away", evidence: "Multiple small-dollar app-to-app transfers and recurring automatic payments to investment platforms/brokerages like 'VEN*ACORN', 'CHASE INV' after initial funding.", type: "behavioral" },
      { label: "Sending money to a rival investment firm", evidence: "Significant outgoing bank transfers/wires from checking account to external brokerage or robo-advisor (~$5k+) not associated with existing bank-managed investments.", type: "behavioral" },
      { label: "Bringing retirement accounts together", evidence: "Large, infrequent incoming bank transfers credits/wires from pension or 401k administrators, followed by transfers to a new singular brokerage account with robo-advisor features.", type: "life-event" },
    ],
    estimatedAudience: 35_000_000,
    penetration: 0.070,
  },
  {
    id: "hybrid-advisor-portfolio",
    name: "Hybrid Advisor Portfolio",
    category: "Wealth",
    icon: UserCheck,
    positioning: "Managed portfolio with on-demand human advisor for mass-affluent households.",
    signals: [
      { label: "Came into a large sum", evidence: "Significant money coming in from estate payouts or business sale, followed by payments out to brokerage accounts or investment platforms.", type: "life-event" },
      { label: "Invests with another firm", evidence: "Recurring outgoing bank transfers to external brokerage firms or investment robo-advisors; no matching inbound investment income.", type: "behavioral" },
      { label: "Looking for professional advice", evidence: "Frequent online bill payment to wealth management firms, financial advisors, or estate planning attorneys, coupled with large-value bank transfers.", type: "behavioral" },
    ],
    estimatedAudience: 18_400_000,
    penetration: 0.037,
  },
  {
    id: "wealth-management",
    name: "Wealth Management",
    category: "Wealth",
    icon: Briefcase,
    positioning: "Holistic advisory for high-net-worth households and complex balance sheets.",
    signals: [
      { label: "Paid partly in company stock", evidence: "Significant quarterly money coming in from corporate payroll (bank transfer) and brokerage (wire) indicating stock grants vesting or employee stock purchases.", type: "behavioral" },
      { label: "Money spread across several firms", evidence: "Consistent outgoing bank transfers over $10k to external brokerage or private bank names, coupled with wire transfers.", type: "behavioral" },
      { label: "Private club and luxury memberships", evidence: "Recurring card charges and bank payments to known private clubs, golf courses, or fractional jet operators.", type: "behavioral" },
      { label: "Sold a major asset", evidence: "Large inbound wire transfer from an estate counsel trust account or real estate attorney, following irregular payments out.", type: "life-event" },
    ],
    estimatedAudience: 12_800_000,
    penetration: 0.026,
    defaultActive: true,
  },
  {
    id: "private-wealth",
    name: "Private Wealth Management",
    category: "Wealth",
    icon: Crown,
    positioning: "Ultra-high-net-worth advisory with dedicated team, lending, and trust services.",
    signals: [
      { label: "Large one-time windfall", evidence: "Large incoming bank transfers or wire transfers from a business-sale escrow, trust payouts, or capital gains, exceeding $5M.", type: "life-event" },
      { label: "Owns property in several places", evidence: "Recurring property tax payments via bank transfers or online bill payments to multiple distinct municipal or county entities.", type: "behavioral" },
      { label: "Runs complex finances", evidence: "Multiple payroll outgoing bank transfers, inter-entity transfers, and recurring wire payments to various specialized financial counterparties (e.g., trust, legal).", type: "behavioral" },
    ],
    estimatedAudience: 1_700_000,
    penetration: 0.003,
  },
  {
    id: "ira",
    name: "Individual Retirement Account",
    category: "Wealth",
    icon: PiggyBank,
    positioning: "Tax-advantaged retirement account with Traditional, Roth, and Rollover options.",
    signals: [
      { label: "Combining old retirement accounts", evidence: "Direct bank transfers from external brokerage accounts (", type: "life-event" },
      { label: "Invests through several platforms", evidence: "Regular, simultaneous bank transfers to multiple investment platforms (brokerage, robo-advisor, alternative assets).", type: "behavioral" },
      { label: "Windfall shortly before retirement", evidence: "Large, one-time inbound wire or bank transfer, followed by significant outbound investment vehicle funding transfers.", type: "life-event" },
    ],
    estimatedAudience: 56_000_000,
    penetration: 0.112,
    defaultActive: true,
  },
  {
    id: "trust-estate",
    name: "Trust & Estate Services",
    category: "Wealth",
    icon: Scale,
    positioning: "Multi-generational wealth structuring, trusteeship, and estate administration.",
    signals: [
      { label: "Working with an estate attorney", evidence: "Significant outgoing bank transfer or wire to identified estate counsel trust account, often alongside recurring online bill payment for legal retainers.", type: "life-event" },
      { label: "Helping pay for an aging parent", evidence: "Consistent app payments (Zelle/Venmo) transfers to family/caregivers, coupled with bank payments to assisted living or home health providers.", type: "behavioral" },
      { label: "Passing money to family", evidence: "Large inbound wire deposits from estate accounts, or outgoing bank transfer to multiple individual beneficiaries following a life event.", type: "life-event" },
    ],
    estimatedAudience: 4_800_000,
    penetration: 0.010,
  },
  {
    id: "values-portfolio",
    name: "Values-Aligned Portfolio",
    category: "Wealth",
    icon: Leaf,
    positioning: "Sustainable and impact-aligned managed portfolios for values-driven investors.",
    signals: [
      { label: "Shops with values-driven brands", evidence: "Consistent spend at certified B-corp merchants and specialty organic grocers across card and app-to-app payment types.", type: "behavioral" },
      { label: "Gives with a cause in mind", evidence: "Regular, across card, transfer and bill payments donations to environmental NGOs and social justice organizations, alongside impact-fund contributions.", type: "behavioral" },
      { label: "Switched to an electric car", evidence: "EV charging network subscriptions, home charging installations (bank transfer), and state-level EV rebate deposits.", type: "life-event" },
    ],
    estimatedAudience: 11_200_000,
    penetration: 0.022,
  },
  {
    id: "401k-rollover",
    name: "401(k) Rollover Service",
    category: "Wealth",
    icon: RefreshCw,
    positioning: "Seamless rollover of employer-sponsored retirement assets into an IRA or advisory account.",
    signals: [
      { label: "Changed or left a job", evidence: "Final payroll deposit from a prior employer, followed by a large incoming bank transfers from a 401(k) administrator.", type: "life-event" },
      { label: "Old retirement accounts scattered", evidence: "Multiple small incoming bank transfers from prior employer plans, indicating scattered retirement assets.", type: "behavioral" },
      { label: "Started working with an advisor", evidence: "Outbound transfers to a brokerage or advisory firm after a rollover money coming in.", type: "behavioral" },
    ],
    estimatedAudience: 14_000_000,
    penetration: 0.028,
  },
  {
    id: "able-savings",
    name: "ABLE / Special Needs Savings",
    category: "Wealth",
    icon: Accessibility,
    positioning: "Tax-advantaged savings for individuals with disabilities and their families.",
    signals: [
      { label: "Paying for special-needs care", evidence: "Recurring bank transfer or card payments to therapy providers, special education services, or adaptive equipment suppliers.", type: "behavioral" },
      { label: "Acting as guardian or trustee", evidence: "Bill-pay or bank transfer to a special needs attorney, trust company, or state disability savings plan administrator.", type: "life-event" },
      { label: "Receives disability benefits", evidence: "Deposits from Social Security disability or disability benefit administrators alongside medical and care-related payments out.", type: "behavioral" },
    ],
    estimatedAudience: 3_200_000,
    penetration: 0.006,
  },
  {
    id: "financial-planning-subscription",
    name: "Financial Planning Subscription",
    category: "Wealth",
    icon: FileSpreadsheet,
    positioning: "Ongoing digital financial planning with goal tracking, tax-aware advice, and annual check-ins.",
    signals: [
      { label: "Uses do-it-yourself planning tools", evidence: "Subscription payments to budgeting or planning apps, plus recurring transfers to multiple savings goals.", type: "behavioral" },
      { label: "Going through a big life change", evidence: "Cluster of life-event signals (marriage, home purchase, new child) within a 12-month window.", type: "life-event" },
      { label: "Paying for outside financial advice", evidence: "Outbound bank transfer to a fee-only planner or robo-advisor, indicating willingness to pay for guidance.", type: "behavioral" },
    ],
    estimatedAudience: 10_000_000,
    penetration: 0.020,
  },

  // ===== LENDING =====
  {
    id: "mortgage",
    name: "Mortgage",
    category: "Lending",
    icon: Building2,
    positioning: "Purchase and refinance mortgages for first-time and move-up buyers.",
    signals: [
      { label: "Pays more rent than most neighbors", evidence: "Consistent automatic payments for rent, recurring app-to-app payments to 'landlord', or online bill payment to property management companies exceed local 75th percent mark.", type: "behavioral" },
      { label: "Saving for a down payment", evidence: "Consistent, increasing balance across savings accounts, coupled with incoming transfers from investment accounts or matured CDs, beyond regular income.", type: "behavioral" },
      { label: "Just moved into a home", evidence: "Increased card spend at home improvement stores, furniture retailers, and moving services, immediately following a large money going out for a down payment or closing costs.", type: "life-event" },
    ],
    estimatedAudience: 27_400_000,
    penetration: 0.055,
  },
  {
    id: "heloc",
    name: "Home Equity Line of Credit",
    category: "Lending",
    icon: Home,
    positioning: "Flexible credit secured by home equity for renovations, large medical bills, tuition, or consolidation.",
    signals: [
      { label: "Major home renovation underway", evidence: "Accumulation of large-ticket card charges at building-material retailers and bank payments to general contractors within a 90-day window.", type: "life-event" },
      { label: "Large medical bills expected", evidence: "Recurring or large payments to hospitals, surgical centers, orthodontists, or out-of-network specialists signaling a financing need.", type: "life-event" },
      { label: "Large tuition payments starting", evidence: "New recurring tuition payments to academic institutions, test-prep services, or enrichment programs alongside a home-equity-rich profile.", type: "life-event" },
      { label: "Recent home purchase or sale with equity left behind", evidence: "Sale proceeds landing in deposit accounts, or a new mortgage plus moving and renovation spend indicating unlocked equity.", type: "life-event" },
      { label: "Long-time homeowner with strong equity", evidence: "Mortgage payments, property tax records, and utility payments indicate continuous homeownership for over five years.", type: "behavioral" },
      { label: "High-interest card balances carried monthly", evidence: "Persistent revolving balances with recurring interest charges and minimum-payment patterns on one or more cards.", type: "behavioral" },
      { label: "Funding projects from outside accounts", evidence: "Large incoming bank transfers from another bank followed by a series of high-value home-improvement transactions via card and bank transfer.", type: "behavioral" },
    ],
    estimatedAudience: 21_000_000,
    penetration: 0.042,
    defaultActive: true,
  },

  {
    id: "auto-loan",
    name: "Auto Loan",
    category: "Lending",
    icon: Car,
    positioning: "Financing for new or used vehicle purchase, with refi for existing loans.",
    signals: [
      { label: "Shopping for a car", evidence: "Card spend at multiple dealerships, with parallel bank transfer inquiries and insurance prepayments within 30 days.", type: "behavioral" },
      { label: "Paid off a car loan elsewhere", evidence: "Large outbound wire or bank transfer to a car-company lenders, with concurrent motor vehicle department payment.", type: "life-event" },
      { label: "Took out a car loan elsewhere", evidence: "Large incoming bank transfers from a financial institution followed by regular outgoing bank transfers payments to an auto lender.", type: "life-event" },
    ],
    estimatedAudience: 23_000_000,
    penetration: 0.046,
  },
  {
    id: "auto-refi",
    name: "Auto Refinance",
    category: "Lending",
    icon: RefreshCw,
    positioning: "Lower-rate refinance for customers carrying a high-APR auto loan elsewhere.",
    signals: [
      { label: "Pays a car loan at another lender", evidence: "Consistent bank transfers or online bill payments payments out to car-company lenders, or transfers to external accounts followed by loan payments.", type: "behavioral" },
      { label: "More money left over each month", evidence: "Sustained increase in direct-deposit payroll or app-to-app money coming in, with no corresponding increase in recurring online bill payment or card payments out.", type: "life-event" },
      { label: "Looking into refinancing", evidence: "Frequent card transactions or bank payments to credit reporting agencies, or inquiries to 'loan comparison' services.", type: "behavioral" },
    ],
    estimatedAudience: 14_600_000,
    penetration: 0.029,
  },
  {
    id: "personal-loan",
    name: "Personal Loan",
    category: "Lending",
    icon: HandCoins,
    positioning: "Unsecured installment loans for consolidation or one-time expenses.",
    signals: [
      { label: "Repaying an outside lender", evidence: "automatic payments to known car-company lenders, matched with online bill payment to non-bank lenders or external card paydowns for credit products.", type: "behavioral" },
      { label: "Needed cash in a hurry", evidence: "Inbound app-to-app transfers from multiple individuals or cash-out activity from diverse sources like 'VEN*CASH-OUT' followed by immediate bill payments.", type: "life-event" },
      { label: "Debt building up", evidence: "Consistent high-utilization credit card balances paired with increasing automatic payments to collection agencies or frequent 'STRP*LOAN' type transactions.", type: "behavioral" },
    ],
    estimatedAudience: 17_800_000,
    penetration: 0.036,
  },
  {
    id: "small-business-loan",
    name: "Small Business Loan",
    category: "Lending",
    icon: Store,
    positioning: "Working capital and term loans for sole proprietors and small businesses.",
    signals: [
      { label: "Small business income starting up", evidence: "Regular deposits from payment processors like Stripe/Square/Paypal into a personal account, alongside business-category card spend.", type: "behavioral" },
      { label: "Pays business suppliers", evidence: "Multiple distinct bank payments to known business suppliers, combined with online online bill payments to professional services or software vendors.", type: "behavioral" },
      { label: "Runs real business operations", evidence: "Consistent card spending at office supply stores or software providers, coupled with bank transfers to a separate business account or payroll service.", type: "behavioral" },
    ],
    estimatedAudience: 6_400_000,
    penetration: 0.013,
  },
  {
    id: "rv-boat-loan",
    name: "RV / Boat Loan",
    category: "Lending",
    icon: Ship,
    positioning: "Recreational vehicle and marine financing for customers buying or refinancing RVs, boats, and watercraft.",
    signals: [
      { label: "Shopping for a boat or RV", evidence: "Card spend at RV dealerships, boat brokers, or marine supply stores, often paired with insurance prepayments.", type: "behavioral" },
      { label: "Pays for boat or RV storage", evidence: "Recurring bank transfer or card payments to marinas, boat storage facilities, or RV parks during the off-season.", type: "behavioral" },
      { label: "Put money down on a boat or RV", evidence: "Substantial deposit or down payment to a recreational vehicle or boat dealer via wire or bank transfer.", type: "life-event" },
    ],
    estimatedAudience: 3_600_000,
    penetration: 0.007,
  },
  {
    id: "motorcycle-loan",
    name: "Motorcycle Loan",
    category: "Lending",
    icon: Bike,
    positioning: "Financing for new or used motorcycle and powersport purchases.",
    signals: [
      { label: "Shopping at powersport dealers", evidence: "Card or bank payments to motorcycle dealerships, powersport retailers, or accessory shops.", type: "behavioral" },
      { label: "Getting insurance quotes", evidence: "bank transfer or card payment to a motorcycle insurer shortly after a dealer deposit.", type: "life-event" },
      { label: "Paying a loan at another lender", evidence: "Outbound bank transfer to a captive powersport lender, indicating an existing loan elsewhere.", type: "behavioral" },
    ],
    estimatedAudience: 2_800_000,
    penetration: 0.006,
  },
  {
    id: "construction-loan",
    name: "Construction Loan",
    category: "Lending",
    icon: Hammer,
    positioning: "Short-term financing for ground-up home construction or major renovation projects.",
    signals: [
      { label: "Bought land", evidence: "Large outbound wire or bank transfer to a land seller, title company, or municipality for a buildable lot.", type: "life-event" },
      { label: "Paying a builder in stages", evidence: "Recurring large-value bank transfer or wire payments to a general contractor or construction firm.", type: "behavioral" },
      { label: "Paying permit and architect fees", evidence: "Payments to architects, structural engineers, or city permitting offices via bank transfers or online bill payments.", type: "life-event" },
    ],
    estimatedAudience: 1_400_000,
    penetration: 0.003,
  },
  {
    id: "lease-buyout-loan",
    name: "Lease Buyout Loan",
    category: "Lending",
    icon: Key,
    positioning: "Financing for customers buying out an existing auto, equipment, or real estate lease.",
    signals: [
      { label: "Car lease coming to an end", evidence: "Large outgoing bank transfers or wire to a leasing company labeled 'lease buyout' or 'residual'.", type: "life-event" },
      { label: "Pays a car lease", evidence: "Consistent monthly automatic payments to a captive leasing company for 24+ months.", type: "behavioral" },
      { label: "Charged for extra mileage or wear", evidence: "End-of-lease fees paid to the lessor, signaling the customer is closing the lease.", type: "life-event" },
    ],
    estimatedAudience: 4_200_000,
    penetration: 0.008,
  },

  // ===== DEPOSITS =====
  {
    id: "starter-checking",
    name: "Starter Checking",
    category: "Deposits",
    icon: Wallet,
    positioning: "No-overdraft checking for students, teens, and customers new to banking.",
    signals: [
      { label: "Money coming from a school", evidence: "Consistent incoming bank transfers from universities or vocational schools alongside app-to-app from guardian counterparties.", type: "life-event" },
      { label: "Just starting to build a financial life", evidence: "Limited credit bureau data, with early-stage card and bank transfer activity showing reliance on cash alternatives and app-to-app payments.", type: "life-event" },
      { label: "Relies on prepaid cards", evidence: "Regular online bill payment transfers to known prepaid card providers (e.g., \\\"CHIME\\\", \\\"GREEN DOT\\\") and app-to-app loads to digital wallets.", type: "behavioral" },
    ],
    estimatedAudience: 38_000_000,
    penetration: 0.076,
  },
  {
    id: "everyday-checking",
    name: "Everyday Checking",
    category: "Deposits",
    icon: Banknote,
    positioning: "Primary checking with direct deposit, bill pay, and broad ATM access.",
    signals: [
      { label: "Paycheck anchors all their spending", evidence: "Consistent W-2 payroll money coming in via bank transfer, coupled with minimal app-to-app cash-out or external account transfers.", type: "behavioral" },
      { label: "Made us their bill-paying bank", evidence: "Multiple online bill payment transactions to utilities, rent and loan payments, showing they run their bills through us.", type: "behavioral" },
      { label: "Sharing money with a partner", evidence: "Shared address update alongside new joint account opening and recurring inter-account transfers to other known accounts.", type: "life-event" },
    ],
    estimatedAudience: 124_000_000,
    penetration: 0.248,
    defaultActive: true,
  },
  {
    id: "relationship-checking",
    name: "Relationship Checking",
    category: "Deposits",
    icon: HeartHandshake,
    positioning: "Premium checking with fee waivers and rate bonuses for multi-product households.",
    signals: [
      { label: "Household uses several products", evidence: "Customer shows payments to car-company lenders, mortgage servicers, and external credit cards across bank transfer and bill pay.", type: "behavioral" },
      { label: "Plenty of cash on hand", evidence: "Consistent high balances in checking, plus inbound transfers from brokerages and outbound bill pays to external investment platforms.", type: "behavioral" },
      { label: "Works with a wealth manager", evidence: "Regular bank transfers to/from known investment platforms and advisory firms, alongside bill pay for estate counsel fees.", type: "behavioral" },
    ],
    estimatedAudience: 19_000_000,
    penetration: 0.038,
  },
  {
    id: "core-savings",
    name: "Core Savings",
    category: "Deposits",
    icon: PiggyBank,
    positioning: "Companion savings account with automatic-transfer tools for everyday savers.",
    signals: [
      { label: "Saves small amounts often", evidence: "Daily small-dollar transfers from checking to savings, augmented by debit card round-up programs", type: "behavioral" },
      { label: "Saving toward something specific", evidence: "Recurring transfers to a savings account, often with a unique memo like 'down payment' or 'tuition fund'", type: "behavioral" },
      { label: "Got a big tax refund", evidence: "Large annual money coming in from tax authorities (IRS, state DOR) via bank transfer or direct deposit, frequently >$1,500", type: "life-event" },
    ],
    estimatedAudience: 68_000_000,
    penetration: 0.136,
    defaultActive: true,
  },
  {
    id: "high-yield-savings",
    name: "High-Yield Savings",
    category: "Deposits",
    icon: TrendingUp,
    positioning: "Premium savings yield for customers with idle checking balances.",
    signals: [
      { label: "Big checking balance earning nothing", evidence: "Consistent checking account balances exceeding $25,000 for 90+ days, with minimal linked savings account activity.", type: "behavioral" },
      { label: "Moving savings out for a better rate", evidence: "Recurring bank transfers to known investment platforms, brokerage accounts, or high-yield fintech savings products.", type: "behavioral" },
      { label: "Funding a rival product", evidence: "Inbound bank transfer linked to a prominent challenger bank or investment product, followed by large outbound transfers from checking.", type: "life-event" },
    ],
    estimatedAudience: 37_200_000,
    penetration: 0.074,
    defaultActive: true,
  },
  {
    id: "certificate-of-deposit",
    name: "Certificate of Deposit",
    category: "Deposits",
    icon: Landmark,
    positioning: "Fixed-term, guaranteed-rate deposits for customers locking in yield.",
    signals: [
      { label: "A CD elsewhere is maturing", evidence: "Large incoming bank transfers or wire from another financial institution, paired with no matching outbound CD purchase.", type: "life-event" },
      { label: "Older saver still building wealth", evidence: "Consistent inbound Social Security or pension bank transfer, coupled with recurring online bill payment to retirement community and medical providers.", type: "behavioral" },
      { label: "Wants steady, predictable income", evidence: "Frequent outbound transfers to online brokerage for bond/Treasury ETFs, or direct bank transfer to government treasury programs.", type: "behavioral" },
    ],
    estimatedAudience: 22_000_000,
    penetration: 0.044,
  },
  {
    id: "money-market-account",
    name: "Money Market Account",
    category: "Deposits",
    icon: BarChart3,
    positioning: "Liquid savings with check-writing access and tiered rates for customers parking larger cash reserves.",
    signals: [
      { label: "Large balance sitting in checking", evidence: "Consistent checking balances above $50,000 with limited outbound investment or spending activity.", type: "behavioral" },
      { label: "Moving savings to another bank", evidence: "Inbound bank transfer from a brokerage sweep or external money market account.", type: "life-event" },
      { label: "Wants money kept easy to reach", evidence: "Recurring large transfers between checking and savings, but no long-term CD or investment purchases.", type: "behavioral" },
    ],
    estimatedAudience: 22_000_000,
    penetration: 0.044,
  },
  {
    id: "teen-youth-savings",
    name: "Teen / Youth Savings",
    category: "Deposits",
    icon: Smile,
    positioning: "Guardian-managed savings and debit tools to help teens build healthy money habits early.",
    signals: [
      { label: "Parent managing a child's account", evidence: "Recurring small bank transfer or app-to-app money coming in from a parent, plus age-appropriate merchant spend at gaming or retail merchants.", type: "behavioral" },
      { label: "Started their first job", evidence: "New small-dollar payroll direct deposits from an employer, often below typical adult thresholds.", type: "life-event" },
      { label: "Teen outgrowing a youth account", evidence: "Inbound transfers from external youth banking apps or prepaid teen cards.", type: "behavioral" },
    ],
    estimatedAudience: 14_000_000,
    penetration: 0.028,
  },
  {
    id: "holiday-club-savings",
    name: "Holiday Club Savings",
    category: "Deposits",
    icon: Gift,
    positioning: "Short-term goal account that auto-saves for seasonal spending and disburses ahead of the holidays.",
    signals: [
      { label: "Spending spikes in one season", evidence: "Significant Q4 card spend at toy stores, electronics retailers, and online gift merchants.", type: "behavioral" },
      { label: "Puts money aside for a goal", evidence: "Weekly or biweekly automatic transfers from checking into a labeled savings bucket.", type: "behavioral" },
      { label: "Cleaning up holiday debt", evidence: "Large January bank transfers or online bill payments payments to credit cards after elevated December spend.", type: "life-event" },
    ],
    estimatedAudience: 9_600_000,
    penetration: 0.019,
  },

  // ===== CARDS =====
  {
    id: "category-cashback-card",
    name: "Category Cash Back Card",
    category: "Cards",
    icon: Tag,
    positioning: "Cash-back card with a customer-chosen bonus category for everyday spend.",
    signals: [
      { label: "Big spender on extras", evidence: "Consistent high spend on selected reward categories like dining, entertainment, or travel, visible across card and app-to-app payment types.", type: "behavioral" },
      { label: "Pays off another bank's card", evidence: "Regular online bill payment or bank transfers to other card issuers, indicating external card payments and usage.", type: "behavioral" },
      { label: "Using the card more each month", evidence: "Increasing monthly transaction volume and value on a single card, with new linked online bill payment or app-to-app activity.", type: "behavioral" },
    ],
    estimatedAudience: 48_000_000,
    penetration: 0.096,
    defaultActive: true,
  },
  {
    id: "flat-cashback-card",
    name: "Flat-Rate Cash Back Card",
    category: "Cards",
    icon: CreditCard,
    positioning: "Simple unlimited cash back on every purchase, no category tracking.",
    signals: [
      { label: "Spends across many categories", evidence: "Consistent multi-category general-purpose card spend across 50+ merchants, supplemented by recurring online bill payment and app-to-app for services.", type: "behavioral" },
      { label: "Uses our card for most purchases", evidence: "Large proportion of essential spending (groceries, fuel, dining) consistently captured on card, minimal external card paydown bank transfer.", type: "behavioral" },
      { label: "Prefers simple rewards", evidence: "Ignored category-activation prompts on card, consistent app-to-app/bank transfer for structured bills, suggests preference for flat-rate rewards.", type: "behavioral" },
      { label: "Spends freely across card and transfers", evidence: "Balanced discretionary spending across card (e.g., entertainment, apparel) and app-to-app (e.g., VEN* for social activities or shared expenses).", type: "behavioral" },
    ],
    estimatedAudience: 42_000_000,
    penetration: 0.084,
  },
  {
    id: "travel-card",
    name: "Travel Rewards Card",
    category: "Cards",
    icon: Plane,
    positioning: "Mid-tier travel card with points, no foreign transaction fees, and travel protections.",
    signals: [
      { label: "Books travel through many sites", evidence: "Card spend and automatic payments to multiple airlines, online travel agencies, and hotel groups within 90 days, including 'ACME Travel' and 'Expedia'.", type: "behavioral" },
      { label: "Spends abroad regularly", evidence: "Card foreign currency transactions, plus international wire transfers or app-to-app to foreign persons, within the last six months.", type: "behavioral" },
      { label: "Getting ready for a trip", evidence: "Elevated card spend at specialty apparel, luggage, and duty-free merchants, correlated with upcoming travel-related payments and app-to-app payments.", type: "behavioral" },
    ],
    estimatedAudience: 24_200_000,
    penetration: 0.048,
  },
  {
    id: "premium-travel-card",
    name: "Premium Travel Card",
    category: "Cards",
    icon: Gem,
    positioning: "Premium travel card with lounge access, travel credits, and elevated earn rates.",
    signals: [
      { label: "Travels for work often", evidence: "Regular T&E transactions across corporate cards, personal cards and expense reimbursements for lodging and airfare.", type: "behavioral" },
      { label: "Takes luxury trips", evidence: "Consistent personal card spend at premium airlines, resorts, and fine dining establishments, often exceeding corporate travel budgets.", type: "behavioral" },
      { label: "Spends across many travel brands", evidence: "Frequent transactions for ride-sharing, luggage, adaptive clothing, and travel medical, indicating extensive and diverse travel needs.", type: "behavioral" },
    ],
    estimatedAudience: 9_600_000,
    penetration: 0.019,
  },
  {
    id: "ultra-premium-travel-card",
    name: "Ultra-Premium Travel Card",
    category: "Cards",
    icon: Crown,
    positioning: "Top-tier travel card with concierge, hotel elite status, and global lounge network.",
    signals: [
      { label: "Books premium travel", evidence: "Consistent spend at luxury hotels and airlines, often with global lounge network, across card and online bill payment payment types.", type: "behavioral" },
      { label: "Well-off frequent international traveler", evidence: "Frequent, high-value foreign currency transactions and cross-border payments for travel services via cards and wires.", type: "behavioral" },
      { label: "Relies on concierge services", evidence: "Repeated card transactions with known concierge merchant types, often followed by high-end travel or experience purchases.", type: "behavioral" },
    ],
    estimatedAudience: 2_200_000,
    penetration: 0.004,
  },
  {
    id: "balance-transfer-card",
    name: "Low-Rate Balance Transfer Card",
    category: "Cards",
    icon: RefreshCw,
    positioning: "Long 0% intro APR for customers carrying high-interest balances elsewhere.",
    signals: [
      { label: "Paying down another bank's card", evidence: "Consistent online bill payment to multiple external card issuers, identified via semantic merchant resolution from cryptic descriptors.", type: "behavioral" },
      { label: "Carrying expensive debt", evidence: "Recurring bank transfers and online bill payments to non-bank lenders and credit card companies, showing high estimated interest payments.", type: "behavioral" },
      { label: "Everyday spending going elsewhere", evidence: "Significant external credit card payments observed across online bill payment and app-to-app, indicating potential to consolidate balances.", type: "behavioral" },
    ],
    estimatedAudience: 13_400_000,
    penetration: 0.027,
  },
  {
    id: "cobrand-card",
    name: "Co-Brand Partner Card",
    category: "Cards",
    icon: Globe,
    positioning: "Affinity card with branded rewards for loyal customers of a specific airline, cruise, or retailer.",
    signals: [
      { label: "Loyal to one brand", evidence: "Majority of consumer spend at a single merchant and related ecosystem via card, with across card, transfer and bill payments recognition of brand payments.", type: "behavioral" },
      { label: "Uses another bank's card most", evidence: "Inbound bank transfers from other financial institutions for credit card payments, indicating competitor usage within the same spend category.", type: "behavioral" },
      { label: "Loyal to one airline or hotel", evidence: "Card and online bill payment transactions show consistent booking and payment for a single airline, cruise line, or related travel provider.", type: "behavioral" },
    ],
    estimatedAudience: 6_800_000,
    penetration: 0.014,
  },
  {
    id: "secured-credit-card",
    name: "Secured Credit Card",
    category: "Cards",
    icon: Lock,
    positioning: "Credit-building card backed by a refundable security deposit for customers establishing or rebuilding credit.",
    signals: [
      { label: "Building or rebuilding credit", evidence: "Limited traditional credit bureau data, reliance on debit, app-to-app, and prepaid products.", type: "behavioral" },
      { label: "Using credit-builder products", evidence: "Recurring payments to credit-builder loan providers or secured card competitors.", type: "behavioral" },
      { label: "Little credit history so far", evidence: "Hard inquiry followed by no new credit records, plus continued use of cash alternatives.", type: "life-event" },
    ],
    estimatedAudience: 18_000_000,
    penetration: 0.036,
  },
  {
    id: "student-credit-card",
    name: "Student Credit Card",
    category: "Cards",
    icon: Backpack,
    positioning: "Starter card for college students with simple rewards and no annual fee.",
    signals: [
      { label: "Spending around a college campus", evidence: "Card and bank transfer activity at campus bookstores, meal plans, and university-related merchants.", type: "behavioral" },
      { label: "Income looks like a student's", evidence: "Small, irregular payroll deposits from campus or part-time employers.", type: "life-event" },
      { label: "Looking for a first credit card", evidence: "Inquiries or applications to known student-card issuers, often with a campus address.", type: "behavioral" },
    ],
    estimatedAudience: 8_400_000,
    penetration: 0.017,
  },
  {
    id: "business-credit-card",
    name: "Business Credit Card",
    category: "Cards",
    icon: Building,
    positioning: "Expense management card for small-business owners with employee cards and category rewards.",
    signals: [
      { label: "Business and personal spending mixed", evidence: "Mixed business and personal card spend at office supply, software, and trade-show merchants.", type: "behavioral" },
      { label: "Paid through a card processor", evidence: "Regular deposits from Stripe, Square, or PayPal into a personal account.", type: "behavioral" },
      { label: "Pays business suppliers", evidence: "bank transfers or online bill payments to vendors, contractors, and professional services from a personal account.", type: "behavioral" },
    ],
    estimatedAudience: 12_000_000,
    penetration: 0.024,
  },

  // ===== INSURANCE =====
  {
    id: "life-insurance",
    name: "Term Life Insurance",
    category: "Insurance",
    icon: Shield,
    positioning: "Income protection for new families and primary earners.",
    signals: [
      { label: "Paying for a new dependent", evidence: "Increased spend at pediatric offices (card), daycare centers (bank transfer), and children's apparel (card) following birth-event cluster.", type: "life-event" },
      { label: "Housing costs went up", evidence: "New recurring bank payments to a mortgage servicer or significantly larger rent payments (online bill payment) started recently.", type: "life-event" },
      { label: "Everything rides on one paycheck", evidence: "One primary income source (bank transfer payroll) increasingly covers household expenses and transfers to other accounts (app-to-app, online bill payment).", type: "behavioral" },
    ],
    estimatedAudience: 15_000_000,
    penetration: 0.030,
  },
  {
    id: "permanent-life",
    name: "Permanent Life Insurance",
    category: "Insurance",
    icon: Shield,
    positioning: "Lifetime coverage with cash-value accumulation for estate and legacy planning.",
    signals: [
      { label: "Pays a lot for legal and accounting", evidence: "Consistent legal and accounting firm payments via bank transfer, wire, and bill pay, especially for trust and estate services.", type: "behavioral" },
      { label: "Assets managed in several places", evidence: "Outflows to multiple brokerages, private equity firms or alternative investment vehicles via bank transfer and wire transfers.", type: "behavioral" },
      { label: "Passing wealth to the next generation", evidence: "Regular app-to-app and wire transfers to multiple family members, often near annual gift tax exclusion limits.", type: "behavioral" },
    ],
    estimatedAudience: 4_400_000,
    penetration: 0.009,
  },
  {
    id: "ltc-insurance",
    name: "Long-Term Care Insurance",
    category: "Insurance",
    icon: Umbrella,
    positioning: "Coverage for in-home and facility-based long-term care needs.",
    signals: [
      { label: "Eldercare costs starting up", evidence: "Increased online bill payment to assisted-living facilities, recurring bank transfer to home healthcare agencies, and app-to-app payments for care services.", type: "behavioral" },
      { label: "Household finances being rearranged", evidence: "New wires/bank transfer from family members, trust payouts, or sudden large transfers to estate-counsel trust account accounts.", type: "life-event" },
      { label: "Medical costs climbing", evidence: "Rising card spend at specialized medical practices combined with increasing app-to-app to nursing support or medical supply vendors.", type: "behavioral" },
    ],
    estimatedAudience: 8_200_000,
    penetration: 0.016,
  },
  {
    id: "annuity",
    name: "Annuity",
    category: "Insurance",
    icon: Landmark,
    positioning: "Guaranteed income and tax-deferred growth for pre-retirees and retirees.",
    signals: [
      { label: "Cashing out a pension", evidence: "Large incoming bank transfers from known pension administrator, followed by outbound wire to brokerage or mutual fund 'for deposit only'", type: "life-event" },
      { label: "Saves for retirement in several places", evidence: "Regular inbound transfers from multiple sources including employment income, investment dividends, and external annuity payments across bank transfer or wire.", type: "behavioral" },
      { label: "Nearing retirement", evidence: "Consistent payroll deposits declining in frequency or amount, paired with increased medical spending (copays, prescriptions) via card or bank transfer.", type: "life-event" },
    ],
    estimatedAudience: 7_200_000,
    penetration: 0.014,
  },
  {
    id: "pet-insurance",
    name: "Pet Insurance",
    category: "Insurance",
    icon: PawPrint,
    positioning: "Accident and illness coverage for dogs, cats, and other household pets.",
    signals: [
      { label: "Regular vet visits", evidence: "Recurring card or bank payments to veterinary clinics, pet hospitals, and prescription pet pharmacies.", type: "behavioral" },
      { label: "Just got a pet", evidence: "Large one-time spend at breeders, pet stores, or animal shelters, followed by pet supply purchases.", type: "life-event" },
      { label: "Insured somewhere else", evidence: "Recurring bank transfer or card payments to a known pet insurance carrier.", type: "behavioral" },
    ],
    estimatedAudience: 11_000_000,
    penetration: 0.022,
  },
  {
    id: "identity-theft-protection",
    name: "Identity Theft Protection",
    category: "Insurance",
    icon: Fingerprint,
    positioning: "Credit monitoring, dark-web alerts, and identity restoration for security-conscious households.",
    signals: [
      { label: "Pays for security services", evidence: "Recurring payments to VPN, password-manager, or antivirus providers.", type: "behavioral" },
      { label: "Hit by fraud recently", evidence: "Disputed transactions, replacement card shipments, or credit freeze fees.", type: "life-event" },
      { label: "Pays for outside credit monitoring", evidence: "Outbound bank transfer or card payments to a credit bureau or identity-protection service.", type: "behavioral" },
    ],
    estimatedAudience: 16_000_000,
    penetration: 0.032,
  },
  {
    id: "disability-insurance",
    name: "Disability Insurance",
    category: "Insurance",
    icon: HeartPulse,
    positioning: "Income-replacement coverage for primary earners during illness or injury.",
    signals: [
      { label: "One income supports the household", evidence: "One dominant payroll bank transfer covers most household expenses and transfers to other accounts.", type: "behavioral" },
      { label: "New person to take care of", evidence: "Birth-event cluster followed by increased housing and dependent-care expenses.", type: "life-event" },
      { label: "Works in a liability-heavy field", evidence: "Payments to professional associations or licensing bodies for high-income occupations.", type: "behavioral" },
    ],
    estimatedAudience: 13_400_000,
    penetration: 0.027,
  },
  {
    id: "auto-insurance",
    name: "Auto Insurance",
    category: "Insurance",
    icon: Car,
    positioning: "Bundled auto coverage for new vehicle purchases, lease requirements, and policy renewals.",
    signals: [
      { label: "Bought a car", evidence: "Large bank transfer or wire to a dealership, followed by motor vehicle department/title fees and a new auto loan.", type: "life-event" },
      { label: "Pays premiums to another insurer", evidence: "Recurring bank transfer or card payments to a known auto insurer.", type: "behavioral" },
      { label: "Insurance required by a lease or loan", evidence: "New captive auto loan or lease payment, typically requiring full-coverage insurance.", type: "life-event" },
    ],
    estimatedAudience: 26_000_000,
    penetration: 0.052,
  },

  // ===== LIFE-EVENT FLOWS =====
  {
    id: "wedding-loan",
    name: "Wedding Personal Loan",
    category: "Lending",
    icon: Heart,
    positioning: "Fixed-rate financing for engagement, wedding, and honeymoon expenses.",
    signals: [
      { label: "Bought expensive jewelry", evidence: "Card spend over $2k at fine-jewelry stores, often followed by credit card paydown.", type: "life-event" },
      { label: "Paying wedding vendors", evidence: "Clustered card, Bill-Pay, or outgoing bank transfers to multiple wedding-related categories like venues, caterers, or event planners.", type: "life-event" },
      { label: "Booking a honeymoon", evidence: "Clusters of card or online travel agency (OTA) spend for flights, lodging, and experiences in common honeymoon destinations.", type: "life-event" },
    ],
    estimatedAudience: 4_800_000,
    penetration: 0.010,
  },
  {
    id: "solo-restart-checking",
    name: "Solo Restart Checking",
    category: "Deposits",
    icon: RefreshCw,
    positioning: "Fresh standalone checking with budgeting tools for customers re-establishing solo finances.",
    signals: [
      { label: "Now paying the bills alone", evidence: "Formerly joint online bill paymentees (e.g., utility, rent) now exclusively single-payer via bank transfers or online bill payments, often with new account numbers.", type: "life-event" },
      { label: "Working with a family lawyer", evidence: "Multiple disaggregated payments to legal services firms, ", type: "life-event" },
      { label: "Paying rent or mortgage on their own", evidence: "First-time or new recurring rent/mortgage payments via bank transfers or online bill payments, linked to a single individual, following a period of joint housing payments.", type: "life-event" },
    ],
    estimatedAudience: 6_200_000,
    penetration: 0.012,
  },
  {
    id: "inherited-ira",
    name: "Inherited IRA",
    category: "Wealth",
    icon: Gift,
    positioning: "Beneficiary IRA structure preserving tax treatment for inherited retirement assets.",
    signals: [
      { label: "Received money from an estate", evidence: "Large incoming bank transfers or wire from an estate counsel trust account or trust payouts, potentially preceded by multiple smaller legal/probate fees.", type: "life-event" },
      { label: "Regularly gives money to family", evidence: "Consistent outgoing bank transfers or online bill payments to a financial advisor or brokerage, following a large estate money coming in event.", type: "behavioral" },
      { label: "Updated who inherits their accounts", evidence: "Digital engagement with beneficiary forms or account titling changes observed across multiple financial platforms or bank products.", type: "behavioral" },
    ],
    estimatedAudience: 3_800_000,
    penetration: 0.008,
  },
  {
    id: "second-home-mortgage",
    name: "Second Home Mortgage",
    category: "Lending",
    icon: Home,
    positioning: "Purchase financing for vacation or seasonal-use second properties.",
    signals: [
      { label: "Spends time in a vacation area", evidence: "Card spend at resorts and restaurants in a distinct geographic region cross-referenced with bank transfer to local utilities or property management.", type: "behavioral" },
      { label: "Pays taxes on a second home", evidence: "Multiple large-value bank transfers or online bill payments transactions to distinct county tax assessors with different geographic markers.", type: "behavioral" },
      { label: "Maintains a property elsewhere", evidence: "Recurring card or online bill payment transactions to landscaping, pool, or home repair services in a non-primary residential area.", type: "behavioral" },
      { label: "Paying contractors far from home", evidence: "Large-value bank transfer or wire transfers to contractors and builders located outside the primary residence's metropolitan area.", type: "life-event" },
    ],
    estimatedAudience: 2_800_000,
    penetration: 0.006,
  },
  {
    id: "student-loan-refi",
    name: "Student Loan Refinance",
    category: "Lending",
    icon: GraduationCap,
    positioning: "Lower-rate refinance for borrowers carrying federal or private student loans.",
    signals: [
      { label: "Looking at combining student loans", evidence: "Multiple recent hard credit inquiries from student lenders followed by a new recurring bank transfer to a consolidated servicer.", type: "life-event" },
      { label: "First real paycheck", evidence: "Significant and sustained increase in payroll deposits, potentially combined with relocation expenses via card and bill pay.", type: "life-event" },
      { label: "Student loan payments moved elsewhere", evidence: "Decreased or terminated bank payments to original student loan servicers, replaced by new payments to a competing financial institution.", type: "behavioral" },
    ],
    estimatedAudience: 11_600_000,
    penetration: 0.023,
  },
  {
    id: "hsa",
    name: "Health Savings Account",
    category: "Deposits",
    icon: Heart,
    positioning: "Triple-tax-advantaged savings for customers on high-deductible health plans.",
    signals: [
      { label: "Contributes to a health savings account", evidence: "Regular incoming bank transfers from employer payroll or personal funding to a health savings administrator; may see 'HSA' or 'HEALTH SA' in descriptor.", type: "behavioral" },
      { label: "Paying medical bills out of pocket", evidence: "Consistent, out-of-pocket card or bank payments to medical providers ('HOSPITAL', 'PEDIATRIC', 'RX') before typical insurance coverage limits are met.", type: "behavioral" },
      { label: "Old enough for extra retirement contributions", evidence: "Periodic, larger-than-normal bank transfer or app-to-app contributions to an HSA administrator, often occurring around age 55, indicating catch-up contributions.", type: "life-event" },
    ],
    estimatedAudience: 18_800_000,
    penetration: 0.038,
  },
  {
    id: "donor-advised-fund",
    name: "Donor-Advised Fund",
    category: "Wealth",
    icon: HeartHandshake,
    positioning: "Tax-efficient charitable giving vehicle with invested balances for long-term impact.",
    signals: [
      { label: "Gives a lot each year", evidence: "Large Q4 online bill payment and outgoing bank transfers to diverse charitable organizations, exceeding prior yearly averages by 2x.", type: "behavioral" },
      { label: "Gives to many charities", evidence: "Consistent app-to-app, online bill payment, and card donations to multiple distinct non-profit categories (e.g., education, arts, social services).", type: "behavioral" },
      { label: "Starting to give seriously", evidence: "Initial large bank transfer or wire transfer to a DAF sponsor or community foundation, followed by segmented payments out to charities.", type: "life-event" },
    ],
    estimatedAudience: 4_200_000,
    penetration: 0.008,
  },
  {
    id: "personal-line-of-credit",
    name: "Personal Line of Credit",
    category: "Lending",
    icon: HandCoins,
    positioning: "Revolving unsecured line for flexible access during income gaps or large planned outflows.",
    signals: [
      { label: "Paycheck stopped or shrank", evidence: "Observed absence of typical payroll deposits or recurring income, or a sustained decrease in deposit amounts across bank transfer and app-to-app payment types.", type: "life-event" },
      { label: "Emergency savings moving fast", evidence: "Rapid, across card, transfer and bill payments cash-out movements to external accounts or app-to-app; or new, consistent money coming in from an external investment or savings provider.", type: "life-event" },
      { label: "Card stays near the limit", evidence: "Consistent external credit card payments via online bill payment show increasing principal paydowns, indicating rising revolving debt across card payment types.", type: "behavioral" },
      { label: "Leaning on check cashers and payday services", evidence: "Recurring outbound transfers to alternative lenders or 'pay-over-time' services, indicating use of external credit providers.", type: "behavioral" },
    ],
    estimatedAudience: 13_000_000,
    penetration: 0.026,
  },
  {
    id: "global-account",
    name: "Multi-Currency Global Account",
    category: "Deposits",
    icon: Globe,
    positioning: "Cross-border account with multi-currency holdings and reduced FX wire fees.",
    signals: [
      { label: "Paid by an overseas employer", evidence: "Recurring bank transfer or swift credits from foreign employer, with 'PAYROLL' or 'SALARY' in descriptor and non-USD original currency.", type: "life-event" },
      { label: "Spends in several currencies", evidence: "Sustained card spend in non-USD across multiple currencies, combined with app-to-app to international recipients.", type: "behavioral" },
      { label: "Sends money abroad often", evidence: "Recurring outbound or inbound wires/bank transfer to/from foreign counterparties, including 'SWIFT' or 'IBAN' references.", type: "behavioral" },
    ],
    estimatedAudience: 3_400_000,
    penetration: 0.007,
  },
  {
    id: "homeowners-insurance",
    name: "Homeowners Insurance",
    category: "Insurance",
    icon: Shield,
    positioning: "Bundled property and liability coverage for primary-residence homeowners.",
    signals: [
      { label: "Recently bought a home", evidence: "New mortgage payouts and principal payments via bank transfer and wire to a known lender.", type: "life-event" },
      { label: "Home project wrapping up", evidence: "Clustering of final large-dollar bank payments to contractors and building material suppliers.", type: "life-event" },
      { label: "No home insurance payments on file", evidence: "Absence of recurring online bill payment or bank payments to property & casualty insurers, despite property ownership.", type: "behavioral" },
    ],
    estimatedAudience: 9_800_000,
    penetration: 0.020,
  },
  {
    id: "umbrella-insurance",
    name: "Umbrella Insurance",
    category: "Insurance",
    icon: Umbrella,
    positioning: "Excess-liability coverage for households with material assets or higher exposure.",
    signals: [
      { label: "Pays taxes on more than one property", evidence: "Recurring property tax payments via bank transfer/BillPay to multiple distinct county/municipality entities indicate ownership of multiple properties.", type: "behavioral" },
      { label: "Car insurance went up", evidence: "Significant increase in recurring auto insurance payments (card or bank transfer) following a new driver addition or vehicle purchase event.", type: "life-event" },
      { label: "Moves large sums around", evidence: "Large outbound wire transfers or bank payments to known luxury good merchants or investment accounts, alongside inbound proceeds from asset sales.", type: "behavioral" },
    ],
    estimatedAudience: 6_400_000,
    penetration: 0.013,
  },
  {
    id: "move-financing",
    name: "Moving & Relocation Loan",
    category: "Lending",
    icon: Truck,
    positioning: "Short-term unsecured financing for moving costs, deposits, and relocation gaps.",
    signals: [
      { label: "Paying movers and deposits", evidence: "Clustered card spend at movers, container services, and rental agencies, plus bank transfer or wire for security deposits and first month's rent.", type: "life-event" },
      { label: "Bills starting up in a new state", evidence: "Concurrent online bill payment enrollment and recurring payments to utility providers and landlords in a new, distant geography.", type: "life-event" },
      { label: "New paycheck from a local employer", evidence: "New recurring bank transfer payroll credits from an employer geographically distant from prior employer's location.", type: "life-event" },
    ],
    estimatedAudience: 5_200_000,
    penetration: 0.010,
  },

  // ===== BUSINESS-OWNER INFERRED =====
  {
    id: "sba-loan",
    name: "SBA 7(a) / 504 Loan",
    category: "Lending",
    icon: Landmark,
    positioning: "Government-guaranteed financing for expansion, equipment, or owner-occupied property.",
    signals: [
      { label: "Owner-run business cash flow", evidence: "Recurring card-processor settlement credits (e.g. 'SQ *DEPOSIT', 'STRIPE TRANSFER', 'TOAST checkout') landing in a personal or hybrid checking account.", type: "behavioral" },
      { label: "Spending on expansion", evidence: "Clustered bank transfer to commercial contractors, equipment dealers, and permit/licensing authorities beyond normal operating spend.", type: "life-event" },
      { label: "No business loans today", evidence: "Absence of recurring commercial loan payments despite sustained business receipts and supplier bank transfer volume.", type: "behavioral" },
    ],
    estimatedAudience: 3_100_000,
    penetration: 0.006,
  },
  {
    id: "business-line-of-credit",
    name: "Business Line of Credit",
    category: "Lending",
    icon: HandCoins,
    positioning: "Revolving working capital to smooth seasonal receipts and payables timing.",
    signals: [
      { label: "Income swings by season", evidence: "Processor settlement credits swinging materially quarter to quarter, with balances dipping ahead of payroll payments.", type: "behavioral" },
      { label: "Struggling to pay suppliers on time", evidence: "Supplier and wholesale automatic payments clearing late in the cycle, occasional overdraft or transfer-in to cover payroll provider payments.", type: "behavioral" },
      { label: "Using expensive short-term business cash", evidence: "Daily or weekly fixed automatic payments to alternative-finance providers, a signature of high-cost MCA repayment.", type: "behavioral" },
    ],
    estimatedAudience: 4_200_000,
    penetration: 0.008,
  },
  {
    id: "equipment-financing",
    name: "Equipment Financing",
    category: "Lending",
    icon: Wrench,
    positioning: "Term financing secured by the equipment, replacing recurring rental spend.",
    signals: [
      { label: "Rents equipment every month", evidence: "Monthly bank transfer or card payments to equipment rental and leasing companies sustained over multiple quarters.", type: "behavioral" },
      { label: "Spending more on home repairs", evidence: "Increasing card spend at industrial repair, parts, and service vendors indicating aging owned equipment.", type: "behavioral" },
      { label: "Buys from trade suppliers", evidence: "Ongoing bank transfer to wholesale trade distributors and B2B suppliers consistent with an operating business.", type: "behavioral" },
    ],
    estimatedAudience: 2_600_000,
    penetration: 0.005,
  },
  {
    id: "commercial-real-estate-mortgage",
    name: "Commercial Real Estate Mortgage",
    category: "Lending",
    icon: Building2,
    positioning: "Owner-occupied commercial property financing to replace business rent.",
    signals: [
      { label: "Pays rent on a business space", evidence: "Recurring large bank transfers or online bill payments to an LLC or property management entity, separate from residential housing payments.", type: "behavioral" },
      { label: "Pays business utilities", evidence: "Recurring commercial-rate utility, waste, and alarm/monitoring payments tied to a non-residential address.", type: "behavioral" },
      { label: "Steady business income for years", evidence: "Consistent processor settlements and B2B incoming bank transfers over 24+ months supporting debt-service capacity.", type: "behavioral" },
    ],
    estimatedAudience: 2_100_000,
    penetration: 0.004,
  },
  {
    id: "business-checking",
    name: "Business Checking",
    category: "Deposits",
    icon: Store,
    positioning: "Dedicated operating account that separates business receipts from personal funds.",
    signals: [
      { label: "Business sales landing in a personal account", evidence: "Card-processor settlement credits and marketplace payouts depositing directly into a consumer checking account.", type: "behavioral" },
      { label: "Pays taxes four times a year", evidence: "Recurring quarterly automatic payments to 'IRS USATAXPYMT' and state revenue departments, sized to self-employment income.", type: "behavioral" },
      { label: "Just formed a business", evidence: "One-time payments to secretary of state filing services, registered agents, or business formation platforms.", type: "life-event" },
    ],
    estimatedAudience: 8_600_000,
    penetration: 0.017,
  },
  {
    id: "business-savings-sweep",
    name: "Business Savings & Sweep",
    category: "Deposits",
    icon: PiggyBank,
    positioning: "Yield on idle operating cash with automatic sweep above a working-capital floor.",
    signals: [
      { label: "Business cash sitting idle", evidence: "Sustained balances well above the trailing payroll and supplier money going out run rate, with no interest-bearing counterpart.", type: "behavioral" },
      { label: "Setting money aside for taxes", evidence: "Balance build-up between quarterly IRS estimated tax payments, drawn down at each filing date.", type: "behavioral" },
      { label: "Shopping for business banking elsewhere", evidence: "Outbound bank transfer to money-market or treasury platforms marketed to small businesses.", type: "behavioral" },
    ],
    estimatedAudience: 5_400_000,
    penetration: 0.011,
  },
  {
    id: "merchant-services",
    name: "Merchant Services & Payment Acceptance",
    category: "Deposits",
    icon: Receipt,
    positioning: "Bank-provided card acceptance with next-day funding and lower blended fees.",
    signals: [
      { label: "Pays outside processing fees", evidence: "Recurring monthly fee payments from external payment processors alongside their settlement credits.", type: "behavioral" },
      { label: "Buying checkout hardware", evidence: "Card purchases of terminals, readers, and checkout subscription software from non-bank providers.", type: "behavioral" },
      { label: "Funds accounts late", evidence: "Settlement credits arriving on multi-day lag relative to observed sales schedule, indicating slower external funding.", type: "behavioral" },
    ],
    estimatedAudience: 3_900_000,
    penetration: 0.008,
  },
  {
    id: "corporate-purchasing-card",
    name: "Corporate / Purchasing Card",
    category: "Cards",
    icon: CreditCard,
    positioning: "Multi-user spend controls, expense categorization, and supplier rebates.",
    signals: [
      { label: "Several employees buying supplies", evidence: "Business supplier and B2B software charges appearing across several cards on the same household relationship.", type: "behavioral" },
      { label: "Business costs on a personal card", evidence: "Wholesale, freight, and advertising-platform charges concentrated on a personal credit card.", type: "behavioral" },
      { label: "Pays for expense software", evidence: "Recurring charges to expense-management or accounting platforms indicating spend-control need.", type: "behavioral" },
    ],
    estimatedAudience: 3_300_000,
    penetration: 0.007,
  },
  {
    id: "fleet-fuel-card",
    name: "Fuel & Fleet Card",
    category: "Cards",
    icon: Fuel,
    positioning: "Per-vehicle fuel controls and rebates for businesses running a vehicle fleet.",
    signals: [
      { label: "Fills up the tank often", evidence: "Fuel purchases materially above household norms, often multiple transactions per day across separate stations.", type: "behavioral" },
      { label: "Keeps up with car maintenance", evidence: "Recurring card spend at commercial tire, fleet service, and truck repair vendors.", type: "behavioral" },
      { label: "Pays for work vehicles", evidence: "Recurring payments for commercial auto insurance, DOT/registration fees, or toll fleet accounts.", type: "behavioral" },
    ],
    estimatedAudience: 2_400_000,
    penetration: 0.005,
  },
  {
    id: "solo-401k-sep-ira",
    name: "Solo 401(k) / SEP-IRA",
    category: "Wealth",
    icon: Briefcase,
    positioning: "High-limit retirement plan for owner-operators and the self-employed.",
    signals: [
      { label: "Self-employed with no work retirement plan", evidence: "Processor settlements and self-employment-style incoming bank transfers with no employer payroll credit and no retirement plan deduction.", type: "behavioral" },
      { label: "Pays taxes four times a year", evidence: "Recurring IRS and state estimated tax payments indicating taxable income that a qualified plan could shelter.", type: "behavioral" },
      { label: "Saves for retirement when they can", evidence: "Irregular lump-sum transfers to external IRA providers, typically clustered near filing deadlines.", type: "behavioral" },
    ],
    estimatedAudience: 6_100_000,
    penetration: 0.012,
  },
  {
    id: "business-succession-planning",
    name: "Business Succession & Exit Planning",
    category: "Wealth",
    icon: Scale,
    positioning: "Valuation, transition, and liquidity planning for owners approaching exit.",
    signals: [
      { label: "Older business owner", evidence: "Long-tenured business receipts alongside retirement-age demographic markers and rising retained balances.", type: "behavioral" },
      { label: "Started working with an advisor", evidence: "Bill-pay to M&A advisors, business brokers, valuation firms, or transaction attorneys.", type: "life-event" },
      { label: "Getting ready for a big payout", evidence: "Escrow-related wires or attorney trust account transfers preceding a business sale.", type: "life-event" },
    ],
    estimatedAudience: 1_900_000,
    penetration: 0.004,
  },
  {
    id: "payroll-services",
    name: "Payroll Services",
    category: "Wealth",
    icon: Users,
    positioning: "Integrated payroll, tax filing, and benefits administration for employers.",
    signals: [
      { label: "Uses another payroll provider", evidence: "Recurring automatic payments to third-party payroll providers on a strict bi-weekly or semi-monthly schedule.", type: "behavioral" },
      { label: "Just started paying employees", evidence: "Initial payroll-provider setup fee followed by the first employee payouts batch, indicating a newly hiring employer.", type: "life-event" },
      { label: "Pays employment taxes", evidence: "Recurring federal and state employment tax deposits ('EFTPS', state withholding) separate from personal tax activity.", type: "behavioral" },
    ],
    estimatedAudience: 3_600_000,
    penetration: 0.007,
  },
  {
    id: "business-owners-policy",
    name: "Business Owner's Policy (BOP)",
    category: "Insurance",
    icon: Shield,
    positioning: "Bundled property, liability, and business-interruption coverage for small operators.",
    signals: [
      { label: "Business insured elsewhere", evidence: "Recurring premium payments to commercial P&C carriers or brokers rather than a bank-affiliated program.", type: "behavioral" },
      { label: "Business looks uninsured", evidence: "Commercial lease, utility, and supplier activity with no observable commercial insurance premium.", type: "behavioral" },
      { label: "Buying business equipment", evidence: "Large equipment and fixture purchases increasing insurable value at the business location.", type: "life-event" },
    ],
    estimatedAudience: 4_800_000,
    penetration: 0.010,
  },
  {
    id: "workers-compensation",
    name: "Workers' Compensation",
    category: "Insurance",
    icon: HardHat,
    positioning: "Statutory coverage for employers with W-2 staff, priced off actual payroll.",
    signals: [
      { label: "Has employees but no workers' comp", evidence: "Consistent payroll-provider payments and employment tax deposits with no matching workers' comp carrier payment.", type: "behavioral" },
      { label: "Hiring more people", evidence: "Rising payroll debit amounts and batch sizes over consecutive cycles, indicating added employees.", type: "life-event" },
      { label: "Works in a higher-risk trade", evidence: "Supplier and tooling spend concentrated in construction, trades, or food service categories with elevated comp exposure.", type: "behavioral" },
    ],
    estimatedAudience: 2_800_000,
    penetration: 0.006,
  },
  {
    id: "key-person-life-insurance",
    name: "Key Person Life Insurance",
    category: "Insurance",
    icon: HeartHandshake,
    positioning: "Coverage protecting the business against loss of an owner or critical employee.",
    signals: [
      { label: "Business depends on the owner", evidence: "Business receipts concentrated in a single operating relationship with minimal payroll depth behind the owner.", type: "behavioral" },
      { label: "Pays business loans", evidence: "Active commercial loan or lease payments that would survive the loss of the principal.", type: "behavioral" },
      { label: "Business has multiple owners", evidence: "Recurring inter-partner distributions or buy-sell agreement legal fees indicating multiple principals.", type: "behavioral" },
    ],
    estimatedAudience: 2_200_000,
    penetration: 0.004,
  },
];

export function getProductFlow(id: string): ProductFlow | undefined {
  return PRODUCT_FLOWS.find((p) => p.id === id);
}
