import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';
import { compileGrowthPlayContract } from './growth-play-contract.mjs';
import { estimateSensitivity, refineMetricRow, replayFeatures } from './play-sensitivity.mjs';
import { merrillRelationshipDetector } from './standalone-growth-play-detectors.mjs';

const drafts = JSON.parse(readFileSync(new URL('../fixtures/evaluation/growth-play-drafts.json', import.meta.url), 'utf8'));
const merrill = compileGrowthPlayContract(drafts[1]);
const cases = buildCases();

test('replay reports decision-side features over historical records', () => {
  const features = replayFeatures({ contract: merrill, detector: merrillRelationshipDetector, cases });
  // Declared trigger is 100k; households run 25k-500k in 25k steps, so 17 of 20 qualify.
  assert.equal(features.evaluated, 20);
  assert.equal(features.qualified, 17);
  assert.equal(features.qualified_rate, 0.85);
  assert.equal(features.mean_confidence, 0.89);
  assert.equal(features.precision, null, 'precision requires labels');
  assert.equal(features.errors, 0);

  const labelled = replayFeatures({
    contract: merrill,
    detector: merrillRelationshipDetector,
    cases,
    labelledHouseholds: cases.filter((item) => item.transferAmount >= 150_000).map((item) => item.householdToken),
  });
  // 15 of the 17 selected households are ones the expert acted on.
  assert.equal(labelled.precision, 0.882353);
});

test('finite-difference sensitivity recovers the sign of every knob', () => {
  const sensitivity = estimateSensitivity({ contract: merrill, detector: merrillRelationshipDetector, cases });

  // Raising the transfer threshold must reduce qualified volume.
  assert.ok(sensitivity.jacobian.min_transfer_amount.qualified_rate < 0);
  assert.equal(sensitivity.signs.min_transfer_amount.qualified_rate, -1);
  // Requiring more corroborating signals cannot increase volume.
  assert.ok(sensitivity.jacobian.min_corroborating_signals.qualified_rate <= 0);
  // Confidence is a reporting knob here: it moves confidence, not selection.
  assert.equal(sensitivity.jacobian.qualified_confidence.qualified_rate, 0);
  assert.ok(sensitivity.jacobian.qualified_confidence.mean_confidence > 0);

  assert.equal(sensitivity.baseline.qualified_rate, 0.85);
  assert.equal(sensitivity.outcomeRowIncluded, false, 'replay cannot observe the P&L metric');
  assert.deepEqual(sensitivity.saturatedParameters, []);
});

test('sensitivity is expressed per normalized approved step', () => {
  const sensitivity = estimateSensitivity({ contract: merrill, detector: merrillRelationshipDetector, cases });
  const spec = merrill.parameters.min_transfer_amount;
  const high = replayFeatures({
    contract: merrill, detector: merrillRelationshipDetector, cases, values: { min_transfer_amount: spec.value + spec.max_step },
  });
  const low = replayFeatures({
    contract: merrill, detector: merrillRelationshipDetector, cases, values: { min_transfer_amount: spec.value - spec.max_step },
  });
  assert.equal(sensitivity.steps.min_transfer_amount.normalizedSpan, 2);
  assert.equal(
    sensitivity.jacobian.min_transfer_amount.qualified_rate,
    Number(((high.qualified_rate - low.qualified_rate) / 2).toFixed(6)),
  );
});

test('the metric row falls back to its prior and improves once waves exist', () => {
  const parameterNames = ['min_transfer_amount', 'min_corroborating_signals', 'qualified_confidence'];
  const prior = { min_transfer_amount: 8000, min_corroborating_signals: 0, qualified_confidence: 0 };

  const cold = refineMetricRow({ waves: [], parameterNames, feature: 'absolute_lift', priorRow: prior });
  assert.equal(cold.source, 'prior');
  assert.equal(cold.usedWaves, 0);
  assert.deepEqual(cold.row, prior);

  // Four waves generated by a true sensitivity of 5000 per normalized step.
  const waves = [0.8, -0.5, 1, -0.25].map((step) => ({
    normalizedDelta: { min_transfer_amount: step, min_corroborating_signals: 0, qualified_confidence: 0 },
    featureDelta: { absolute_lift: 5000 * step },
  }));
  const refined = refineMetricRow({ waves, parameterNames, feature: 'absolute_lift', priorRow: prior });
  assert.equal(refined.source, 'observed_waves');
  assert.equal(refined.usedWaves, 4);
  assert.ok(Math.abs(refined.row.min_transfer_amount - 5000) < 250, 'refit should approach the true sensitivity');
  assert.ok(refined.identified);
  // The prior mis-states the slope by 3000 per step; the refit explains the waves far better.
  const priorResidualRms = Math.sqrt([0.8, -0.5, 1, -0.25]
    .reduce((sum, step) => sum + ((5000 - prior.min_transfer_amount) * step) ** 2, 0) / 4);
  assert.ok(priorResidualRms > 1500);
  assert.ok(refined.residualRms < 300, `refined residual ${refined.residualRms} should be small`);
});

function buildCases() {
  const built = [];
  for (let step = 1; step <= 20; step += 1) {
    const transferAmount = step * 25_000;
    built.push({
      householdToken: `tok_household_${String(step).padStart(6, '0')}`,
      transferAmount,
      policies: merrill.policy.required_policy_ids.map((policyId) => ({ policy_id: policyId, verdict: 'clear' })),
      records: [
        { transaction_id: `tx_transfer_${step}`, source_system: 'merrill_transfer_workflow', rail: 'acats', amount: transferAmount },
        { transaction_id: `tx_books_${step}`, source_system: 'merrill_books', rail: 'account', amount: 0 },
        { transaction_id: `tx_digital_${step}`, source_system: 'merrill_digital', rail: 'digital', amount: 1 },
      ],
    });
  }
  return built;
}
