// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-bank-products.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";
var CATEGORIES = [
  {
    id: "cards",
    label: "Cards",
    products: [
      { id: "premium-travel", name: "Premium Travel Card", pricing: "60,000 pt bonus", terms: "3x travel, no FX fees" },
      { id: "cash-back", name: "Everyday Cash Back Card", pricing: "2% unlimited", terms: "No annual fee" }
    ]
  },
  {
    id: "deposits",
    label: "Deposits",
    products: [
      { id: "hy-savings", name: "High-Yield Savings", pricing: "4.25% APY", terms: "No minimum, FDIC insured" },
      { id: "cd-12mo", name: "12-Month CD", pricing: "4.75% APY", terms: "$1,000 minimum" }
    ]
  },
  {
    id: "lending",
    label: "Lending",
    products: [
      { id: "auto-refi", name: "Auto Refinance", pricing: "from 5.99% APR", terms: "60-72 mo terms" },
      { id: "heloc", name: "HELOC", pricing: "from Prime + 0.5%", terms: "10-yr draw / 20-yr repay" },
      { id: "mortgage-30", name: "30-Year Fixed Mortgage", pricing: "from 6.75% APR", terms: "Conforming, 20% down" }
    ]
  },
  {
    id: "wealth",
    label: "Wealth",
    products: [
      { id: "managed-portfolio", name: "Managed Portfolio", pricing: "0.75% AUM", terms: "$25k minimum" },
      { id: "advisor-access", name: "Dedicated Advisor Access", pricing: "Included at $250k+ AUM", terms: "Quarterly reviews" }
    ]
  }
];
var list_bank_products_default = defineTool({
  name: "list_bank_products",
  title: "List bank products",
  description: "List Ventus reference bank product categories and products (cards, deposits, lending, wealth) with sample pricing and terms.",
  inputSchema: {
    category: z.enum(["cards", "deposits", "lending", "wealth"]).optional().describe("Optional category filter. Omit to return all categories.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ category }) => {
    const data = category ? CATEGORIES.filter((c) => c.id === category) : CATEGORIES;
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { categories: data }
    };
  }
});

// src/lib/mcp/tools/search-bank-products.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
var PRODUCTS = [
  { id: "premium-travel", name: "Premium Travel Card", category: "cards", pricing: "60,000 pt bonus", terms: "3x travel, no FX fees", keywords: ["travel", "points", "airline", "hotel", "premium"] },
  { id: "cash-back", name: "Everyday Cash Back Card", category: "cards", pricing: "2% unlimited", terms: "No annual fee", keywords: ["cash", "everyday", "grocery", "gas"] },
  { id: "hy-savings", name: "High-Yield Savings", category: "deposits", pricing: "4.25% APY", terms: "No minimum, FDIC insured", keywords: ["savings", "yield", "apy", "emergency fund"] },
  { id: "cd-12mo", name: "12-Month CD", category: "deposits", pricing: "4.75% APY", terms: "$1,000 minimum", keywords: ["cd", "certificate", "deposit", "fixed"] },
  { id: "auto-refi", name: "Auto Refinance", category: "lending", pricing: "from 5.99% APR", terms: "60-72 mo terms", keywords: ["auto", "car", "refinance", "loan"] },
  { id: "heloc", name: "HELOC", category: "lending", pricing: "from Prime + 0.5%", terms: "10-yr draw / 20-yr repay", keywords: ["home equity", "heloc", "renovation"] },
  { id: "mortgage-30", name: "30-Year Fixed Mortgage", category: "lending", pricing: "from 6.75% APR", terms: "Conforming, 20% down", keywords: ["mortgage", "home", "purchase"] },
  { id: "managed-portfolio", name: "Managed Portfolio", category: "wealth", pricing: "0.75% AUM", terms: "$25k minimum", keywords: ["invest", "portfolio", "wealth", "managed"] },
  { id: "advisor-access", name: "Dedicated Advisor Access", category: "wealth", pricing: "Included at $250k+ AUM", terms: "Quarterly reviews", keywords: ["advisor", "wealth", "planning"] }
];
var search_bank_products_default = defineTool2({
  name: "search_bank_products",
  title: "Search bank products",
  description: "Search Ventus reference bank products by keyword (e.g. 'travel', 'refinance', 'savings'). Returns matching products with pricing and terms.",
  inputSchema: {
    query: z2.string().min(1).describe("Search text. Matched against product name, category, and keywords."),
    limit: z2.number().int().min(1).max(20).optional().describe("Max results (default 5).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ query, limit }) => {
    const q = query.trim().toLowerCase();
    const scored = PRODUCTS.map((p) => {
      const hay = [p.name, p.category, ...p.keywords].join(" ").toLowerCase();
      const score = hay.includes(q) ? 1 : q.split(/\s+/).filter((t) => hay.includes(t)).length;
      return { p, score };
    }).filter((s) => s.score > 0).sort((a, b) => b.score - a.score).slice(0, limit ?? 5).map((s) => s.p);
    return {
      content: [{ type: "text", text: JSON.stringify(scored, null, 2) }],
      structuredContent: { results: scored }
    };
  }
});

// src/lib/mcp/tools/get-demo-signals.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.25.76";
var SIGNALS = [
  {
    id: "auto-loan-renewal",
    bucket: "life_event",
    label: "Car Loan Renewal in ~2 Months",
    detail: "Auto Loan \xB7 VW Credit",
    monthly_amount_band: "~$685/mo",
    confidence: 0.92,
    recommended_products: ["auto-refi", "premium-travel"]
  },
  {
    id: "college-prep",
    bucket: "life_event",
    label: "College Preparation",
    detail: "Dependent transitioning to college",
    confidence: 0.9,
    recommended_products: ["hy-savings", "managed-portfolio"]
  },
  {
    id: "home-purchase-bay-area",
    bucket: "life_event",
    label: "Home Purchase in the SF Bay Area",
    detail: "Escrow + inspection activity",
    confidence: 0.95,
    recommended_products: ["mortgage-30", "heloc"]
  }
];
var get_demo_signals_default = defineTool3({
  name: "get_demo_signals",
  title: "Get Ventus demo signals",
  description: "Return the public demo 'external intelligence' signals used in the Ventus bank demo (life events, financial signals) along with sample product recommendations.",
  inputSchema: {
    bucket: z3.enum(["life_event", "financial_signal", "demographic_shift", "behavioral"]).optional().describe("Optional filter by signal bucket. Omit to return all.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ bucket }) => {
    const data = bucket ? SIGNALS.filter((s) => s.bucket === bucket) : SIGNALS;
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { signals: data }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "ventus-ai-mcp",
  title: "Ventus AI",
  version: "0.1.0",
  instructions: "Tools for exploring Ventus AI's reference bank product catalog and public demo intelligence signals. Use `list_bank_products` to browse categories, `search_bank_products` for keyword lookups, and `get_demo_signals` to see the sample life-event and financial signals used in the /bankdemo experience. All data returned is public demo/reference content.",
  tools: [list_bank_products_default, search_bank_products_default, get_demo_signals_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
