// backend/shared/coworker/render.mjs
//
// Rendering for the Coworker's outbound email. Pure functions, no I/O.
//
// Governance rules enforced here (not left to the model):
//  - Every attribute that comes from a third-party / modeled source is tagged
//    with a visible "third-party modeled" badge.
//  - Quantified financial figures are shown as ranges (bands), never as false
//    precision, and always carry an assumption note.
//  - Every reply ends with a single, concrete forward move.
//  - A standing disclaimer footer is appended to every message.

const MODELED_BADGE = 'third-party modeled';

/** HTML-escape a string for safe interpolation into the email body. */
export function esc(value) {
  return String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

/**
 * Render a modeled-attribute chip. Use for any value sourced from enrichment /
 * third-party inference so the advisor always sees provenance inline.
 */
export function modeledBadge(label = MODELED_BADGE) {
  return `<span style="display:inline-block;font-size:11px;line-height:1;padding:2px 6px;margin-left:6px;border:1px solid #c9b458;border-radius:4px;color:#7a6a1f;background:#faf6e6;vertical-align:middle;">${esc(label)}</span>`;
}

/**
 * Format a dollar figure as a band (range) to avoid false precision.
 * Widens by +/- the given fraction and rounds to a readable step.
 * @returns {string} e.g. "$3,800-$4,600"
 */
export function formatBand(value, { fraction = 0.1 } = {}) {
  const n = Number(value);
  if (!Number.isFinite(n) || n === 0) return 'not estimable';
  const lo = roundStep(n * (1 - fraction));
  const hi = roundStep(n * (1 + fraction));
  return `${usd(lo)}-${usd(hi)}`;
}

function roundStep(n) {
  const abs = Math.abs(n);
  const step = abs >= 100000 ? 5000 : abs >= 10000 ? 500 : abs >= 1000 ? 50 : 10;
  return Math.round(n / step) * step;
}

function usd(n) {
  return `$${Math.round(n).toLocaleString('en-US')}`;
}

/**
 * Render the shared HTML shell (peer tone, plain and readable in mail clients).
 *
 * @param {object} opts
 * @param {string} opts.greeting          e.g. "Hi Dana,"
 * @param {string[]} opts.paragraphs       intro/body paragraphs (already plain text)
 * @param {object[]} [opts.sections]       [{ heading, html }]
 * @param {string} opts.forwardMove        the single concrete next step
 * @param {string} [opts.signoff]          defaults to a peer sign-off
 * @param {string} [opts.disclaimer]       footer disclaimer
 */
export function renderShell({ greeting, paragraphs = [], sections = [], forwardMove, signoff = 'Ventus Coworker', disclaimer = DEFAULT_DISCLAIMER }) {
  const paras = paragraphs.map((p) => `<p style="margin:0 0 12px;">${esc(p)}</p>`).join('');
  const secs = sections
    .map(
      (s) =>
        `<div style="margin:0 0 16px;"><div style="font-weight:600;margin:0 0 6px;">${esc(s.heading)}</div>${s.html}</div>`
    )
    .join('');
  const forward = forwardMove
    ? `<p style="margin:16px 0 0;"><strong>Next:</strong> ${esc(forwardMove)}</p>`
    : '';
  return `<div style="font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;font-size:14px;color:#1a1a1a;line-height:1.5;max-width:640px;">
<p style="margin:0 0 12px;">${esc(greeting)}</p>
${paras}
${secs}
${forward}
<p style="margin:16px 0 0;">— ${esc(signoff)}</p>
<hr style="border:none;border-top:1px solid #e5e5e5;margin:20px 0 8px;" />
<p style="font-size:11px;color:#888;margin:0;">${esc(disclaimer)}</p>
</div>`;
}

export const DEFAULT_DISCLAIMER =
  'Generated by an AI coworker for internal advisor use. Attributes tagged "third-party modeled" are inferred, not verified. Dollar figures are modeled estimates shown as ranges and require review before any client action.';

/**
 * Render a ranked audience table for the audience-build task. Each candidate row
 * shows the household, fit rationale, and a modeled benefit band. Suppressed
 * households are listed separately with the gating reason.
 */
export function renderAudienceTable({ candidates = [], suppressed = [] }) {
  const rows = candidates
    .map(
      (c, i) => `<tr>
<td style="padding:6px 8px;border-bottom:1px solid #eee;">${i + 1}</td>
<td style="padding:6px 8px;border-bottom:1px solid #eee;">${esc(c.household_name || c.household_id)}</td>
<td style="padding:6px 8px;border-bottom:1px solid #eee;">${esc(c.rationale)} ${modeledBadge()}</td>
<td style="padding:6px 8px;border-bottom:1px solid #eee;white-space:nowrap;">${esc(formatBand(c.modeled_annual_benefit_usd))}</td>
</tr>`
    )
    .join('');
  const table = `<table style="border-collapse:collapse;width:100%;font-size:13px;">
<thead><tr>
<th style="text-align:left;padding:6px 8px;border-bottom:2px solid #ddd;">#</th>
<th style="text-align:left;padding:6px 8px;border-bottom:2px solid #ddd;">Household</th>
<th style="text-align:left;padding:6px 8px;border-bottom:2px solid #ddd;">Why (modeled)</th>
<th style="text-align:left;padding:6px 8px;border-bottom:2px solid #ddd;">Modeled annual benefit</th>
</tr></thead>
<tbody>${rows || '<tr><td colspan="4" style="padding:8px;color:#888;">No qualifying households.</td></tr>'}</tbody>
</table>`;
  const supp = suppressed.length
    ? `<div style="margin-top:10px;font-size:12px;color:#8a3a3a;">Suppressed (${suppressed.length}): ${suppressed
        .map((s) => `${esc(s.household_name || s.household_id)} (${esc(s.reason)})`)
        .join('; ')}</div>`
    : '';
  return table + supp;
}

/**
 * Render the digest table: one row per household showing the best-fit product
 * and its modeled benefit band. Used by the scheduled digest sender.
 */
export function renderDigestTable(items = []) {
  const rows = items
    .map(
      (i) => `<tr>
<td style="padding:6px 8px;border-bottom:1px solid #eee;">${esc(i.household_name || i.household_id)}</td>
<td style="padding:6px 8px;border-bottom:1px solid #eee;">${esc(i.product?.name || '')} ${modeledBadge()}</td>
<td style="padding:6px 8px;border-bottom:1px solid #eee;">${esc(i.rationale)}</td>
<td style="padding:6px 8px;border-bottom:1px solid #eee;white-space:nowrap;">${esc(formatBand(i.modeled_annual_benefit_usd))}</td>
</tr>`
    )
    .join('');
  return `<table style="border-collapse:collapse;width:100%;font-size:13px;">
<thead><tr>
<th style="text-align:left;padding:6px 8px;border-bottom:2px solid #ddd;">Household</th>
<th style="text-align:left;padding:6px 8px;border-bottom:2px solid #ddd;">Best-fit product</th>
<th style="text-align:left;padding:6px 8px;border-bottom:2px solid #ddd;">Why (modeled)</th>
<th style="text-align:left;padding:6px 8px;border-bottom:2px solid #ddd;">Modeled annual benefit</th>
</tr></thead>
<tbody>${rows || '<tr><td colspan="4" style="padding:8px;color:#888;">No opportunities surfaced this cycle.</td></tr>'}</tbody>
</table>`;
}

/** Render a simple bulleted evidence list (each item already plain text). */
export function renderBullets(items = []) {
  if (!items.length) return '<p style="color:#888;margin:0;">No evidence found.</p>';
  return `<ul style="margin:0;padding-left:20px;">${items
    .map((i) => `<li style="margin:0 0 4px;">${esc(i)}</li>`)
    .join('')}</ul>`;
}
