import assert from 'node:assert/strict';
import test from 'node:test';
import {
  esc,
  formatBand,
  modeledBadge,
  renderAudienceTable,
  renderBullets,
  renderDigestTable,
  renderShell,
} from './render.mjs';

test('esc neutralizes HTML', () => {
  assert.equal(esc('<b>"a"&</b>'), '&lt;b&gt;&quot;a&quot;&amp;&lt;/b&gt;');
});

test('formatBand produces a range and handles non-estimable', () => {
  const band = formatBand(1500);
  assert.match(band, /^\$[\d,]+-\$[\d,]+$/);
  assert.equal(formatBand(0), 'not estimable');
  assert.equal(formatBand('nope'), 'not estimable');
});

test('modeledBadge carries the provenance label', () => {
  assert.match(modeledBadge(), /third-party modeled/);
});

test('renderShell includes greeting, forward move, and disclaimer', () => {
  const html = renderShell({
    greeting: 'Hi Dana,',
    paragraphs: ['One.', 'Two.'],
    forwardMove: 'Do the thing?',
  });
  assert.match(html, /Hi Dana,/);
  assert.match(html, /Do the thing\?/);
  assert.match(html, /Next:/);
  // Disclaimer is HTML-escaped in the footer, so match a quote-free substring.
  assert.match(html, /Generated by an AI coworker for internal advisor use/);
});

test('renderAudienceTable lists candidates and suppressed households', () => {
  const html = renderAudienceTable({
    candidates: [
      { household_id: 'hh_a', household_name: 'A HH', rationale: 'Matches X.', modeled_annual_benefit_usd: 1500 },
    ],
    suppressed: [{ household_id: 'hh_b', household_name: 'B HH', reason: 'nsf_overdraft_cluster' }],
  });
  assert.match(html, /A HH/);
  assert.match(html, /third-party modeled/);
  assert.match(html, /Suppressed \(1\)/);
  assert.match(html, /nsf_overdraft_cluster/);
});

test('renderDigestTable renders rows and an empty state', () => {
  const html = renderDigestTable([
    { household_id: 'hh_a', household_name: 'A HH', product: { id: 'p', name: 'Prod' }, rationale: 'why', modeled_annual_benefit_usd: 2000 },
  ]);
  assert.match(html, /A HH/);
  assert.match(html, /Prod/);
  assert.match(html, /third-party modeled/);
  assert.match(renderDigestTable([]), /No opportunities surfaced/);
});

test('renderBullets handles empty and non-empty', () => {
  assert.match(renderBullets([]), /No evidence/);
  assert.match(renderBullets(['a', 'b']), /<li[^>]*>a<\/li>/);
});
